package com.peerstouch.mobile.core.theme

import androidx.compose.ui.graphics.Color

val PeersPrimary = Color(0xFF6B46C1)
val PeersOnPrimary = Color(0xFFFFFFFF)
val PeersPrimaryContainer = Color(0xFFEDE9FE)
val PeersOnPrimaryContainer = Color(0xFF2E1065)
val PeersSecondary = Color(0xFF3B82F6)
val PeersOnSecondary = Color(0xFFFFFFFF)
val PeersSecondaryContainer = Color(0xFFDBEAFE)
val PeersOnSecondaryContainer = Color(0xFF1E3A5F)
val PeersTertiary = Color(0xFF22C55E)
val PeersOnTertiary = Color(0xFFFFFFFF)
val PeersBackground = Color(0xFFF9FAFB)
val PeersOnBackground = Color(0xFF111827)
val PeersSurface = Color(0xFFFFFFFF)
val PeersOnSurface = Color(0xFF111827)
val PeersSurfaceVariant = Color(0xFFF3F4F6)
val PeersOnSurfaceVariant = Color(0xFF6B7280)
val PeersOutline = Color(0xFFE5E7EB)
val PeersOutlineVariant = Color(0xFFF3F4F6)
val PeersError = Color(0xFFEF4444)
val PeersOnError = Color(0xFFFFFFFF)

val PeersPrimaryDark = Color(0xFFA78BFA)
val PeersOnPrimaryDark = Color(0xFF2E1065)
val PeersPrimaryContainerDark = Color(0xFF4C1D95)
val PeersOnPrimaryContainerDark = Color(0xFFEDE9FE)
val PeersSecondaryDark = Color(0xFF60A5FA)
val PeersOnSecondaryDark = Color(0xFF1E3A5F)
val PeersSecondaryContainerDark = Color(0xFF1E40AF)
val PeersOnSecondaryContainerDark = Color(0xFFDBEAFE)
val PeersTertiaryDark = Color(0xFF4ADE80)
val PeersOnTertiaryDark = Color(0xFF052E16)
val PeersBackgroundDark = Color(0xFF111111)
val PeersOnBackgroundDark = Color(0xFFF9FAFB)
val PeersSurfaceDark = Color(0xFF1A1A1A)
val PeersOnSurfaceDark = Color(0xFFF9FAFB)
val PeersSurfaceVariantDark = Color(0xFF262626)
val PeersOnSurfaceVariantDark = Color(0xFF9CA3AF)
val PeersOutlineDark = Color(0xFF374151)
val PeersOutlineVariantDark = Color(0xFF262626)
val PeersErrorDark = Color(0xFFF87171)
val PeersOnErrorDark = Color(0xFF7F1D1D)
