export const EVENT = {
  AUTH_IDENTITY_CHANGED: 'auth.identity_changed',
  AUTH_SESSION_REVOKED: 'auth.session_revoked',
  OAUTH_CONNECTIONS_CHANGED: 'oauth.connections_changed',
  NAVIGATION_REQUESTED: 'navigation.requested',
  AGENT_BUILDER_STREAM_ENDED: 'agent.builder.stream_ended',
  AGENT_TURN_STREAM_EVENT: 'agent.turn_stream_event',
  AGENT_TURN_RECOVERY_RETRY_REQUESTED: 'agent.turn_recovery_retry_requested',
  GLOBAL_CONTEXT_UPDATED: 'global_context.updated',
  GLOBAL_CONTEXT_PIPELINE_STARTED: 'global_context.pipeline_started',
  GLOBAL_CONTEXT_PIPELINE_FINISHED: 'global_context.pipeline_finished',
  GLOBAL_CONTEXT_PIPELINE_FAILED: 'global_context.pipeline_failed',
  REALTIME_MESSAGE_RECEIVED: 'realtime.message_received',
  REALTIME_PRESENCE_FLIP: 'realtime.presence_flip',
  REALTIME_RESYNC: 'realtime.resync',
  REALTIME_CONNECTION_STATE: 'realtime.connection_state',
  REALTIME_CALL_SIGNAL: 'realtime.call_signal',
  REALTIME_MESSAGE_RECEIPT: 'realtime.message_receipt',
  REALTIME_TYPING_STATE: 'realtime.typing_state',
  REALTIME_MESSAGE_MUTATION: 'realtime.message_mutation',
  REALTIME_GROUP_MEMBERSHIP_CHANGE: 'realtime.group_membership_change',
  REALTIME_GROUP_FEDERATION_EVENT: 'realtime.group_federation_event',
  REALTIME_ENVELOPE_DELIVERED: 'realtime.envelope_delivered',
  REALTIME_CONVERSATION_SETTINGS_CHANGED: 'realtime.conversation_settings_changed',
  REALTIME_SOCIAL_GRAPH_EVENT: 'realtime.social_graph_event',
  MOMENT_CREATED: 'moment.created',
  MOMENT_DELETED: 'moment.deleted',
  MOMENT_COMMENTED: 'moment.commented',
  MOMENT_REACTED: 'moment.reacted',
  MOMENT_RESYNC_REQUESTED: 'moment.resync_requested',
  RELATIONSHIP_CHANGED: 'relationship.changed',
} as const;

export type EventType = (typeof EVENT)[keyof typeof EVENT];
export const EVENT_NAMES: EventType[] = Object.values(EVENT);
