// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: domain/chat/envelope_api.proto

package chat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitEnvelopeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelope      *StationEnvelope       `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitEnvelopeRequest) Reset() {
	*x = SubmitEnvelopeRequest{}
	mi := &file_domain_chat_envelope_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitEnvelopeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitEnvelopeRequest) ProtoMessage() {}

func (x *SubmitEnvelopeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_chat_envelope_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitEnvelopeRequest.ProtoReflect.Descriptor instead.
func (*SubmitEnvelopeRequest) Descriptor() ([]byte, []int) {
	return file_domain_chat_envelope_api_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitEnvelopeRequest) GetEnvelope() *StationEnvelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

type SubmitEnvelopeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvelopeId    string                 `protobuf:"bytes,1,opt,name=envelope_id,json=envelopeId,proto3" json:"envelope_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitEnvelopeResponse) Reset() {
	*x = SubmitEnvelopeResponse{}
	mi := &file_domain_chat_envelope_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitEnvelopeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitEnvelopeResponse) ProtoMessage() {}

func (x *SubmitEnvelopeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_chat_envelope_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitEnvelopeResponse.ProtoReflect.Descriptor instead.
func (*SubmitEnvelopeResponse) Descriptor() ([]byte, []int) {
	return file_domain_chat_envelope_api_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitEnvelopeResponse) GetEnvelopeId() string {
	if x != nil {
		return x.EnvelopeId
	}
	return ""
}

type AckEnvelopeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	InboxItemId   string                 `protobuf:"bytes,2,opt,name=inbox_item_id,json=inboxItemId,proto3" json:"inbox_item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckEnvelopeRequest) Reset() {
	*x = AckEnvelopeRequest{}
	mi := &file_domain_chat_envelope_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckEnvelopeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckEnvelopeRequest) ProtoMessage() {}

func (x *AckEnvelopeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_chat_envelope_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckEnvelopeRequest.ProtoReflect.Descriptor instead.
func (*AckEnvelopeRequest) Descriptor() ([]byte, []int) {
	return file_domain_chat_envelope_api_proto_rawDescGZIP(), []int{2}
}

func (x *AckEnvelopeRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *AckEnvelopeRequest) GetInboxItemId() string {
	if x != nil {
		return x.InboxItemId
	}
	return ""
}

type AckEnvelopeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckEnvelopeResponse) Reset() {
	*x = AckEnvelopeResponse{}
	mi := &file_domain_chat_envelope_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckEnvelopeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckEnvelopeResponse) ProtoMessage() {}

func (x *AckEnvelopeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_chat_envelope_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckEnvelopeResponse.ProtoReflect.Descriptor instead.
func (*AckEnvelopeResponse) Descriptor() ([]byte, []int) {
	return file_domain_chat_envelope_api_proto_rawDescGZIP(), []int{3}
}

type ResumeEnvelopesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	AfterCursor   string                 `protobuf:"bytes,2,opt,name=after_cursor,json=afterCursor,proto3" json:"after_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeEnvelopesRequest) Reset() {
	*x = ResumeEnvelopesRequest{}
	mi := &file_domain_chat_envelope_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeEnvelopesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeEnvelopesRequest) ProtoMessage() {}

func (x *ResumeEnvelopesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_chat_envelope_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeEnvelopesRequest.ProtoReflect.Descriptor instead.
func (*ResumeEnvelopesRequest) Descriptor() ([]byte, []int) {
	return file_domain_chat_envelope_api_proto_rawDescGZIP(), []int{4}
}

func (x *ResumeEnvelopesRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ResumeEnvelopesRequest) GetAfterCursor() string {
	if x != nil {
		return x.AfterCursor
	}
	return ""
}

type ResumeEnvelopesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*DeviceInboxItem     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeEnvelopesResponse) Reset() {
	*x = ResumeEnvelopesResponse{}
	mi := &file_domain_chat_envelope_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeEnvelopesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeEnvelopesResponse) ProtoMessage() {}

func (x *ResumeEnvelopesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_chat_envelope_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeEnvelopesResponse.ProtoReflect.Descriptor instead.
func (*ResumeEnvelopesResponse) Descriptor() ([]byte, []int) {
	return file_domain_chat_envelope_api_proto_rawDescGZIP(), []int{5}
}

func (x *ResumeEnvelopesResponse) GetItems() []*DeviceInboxItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type FederationDeliverEnvelopeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelope      *StationEnvelope       `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FederationDeliverEnvelopeRequest) Reset() {
	*x = FederationDeliverEnvelopeRequest{}
	mi := &file_domain_chat_envelope_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FederationDeliverEnvelopeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FederationDeliverEnvelopeRequest) ProtoMessage() {}

func (x *FederationDeliverEnvelopeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_chat_envelope_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FederationDeliverEnvelopeRequest.ProtoReflect.Descriptor instead.
func (*FederationDeliverEnvelopeRequest) Descriptor() ([]byte, []int) {
	return file_domain_chat_envelope_api_proto_rawDescGZIP(), []int{6}
}

func (x *FederationDeliverEnvelopeRequest) GetEnvelope() *StationEnvelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

type FederationDeliverEnvelopeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FederationDeliverEnvelopeResponse) Reset() {
	*x = FederationDeliverEnvelopeResponse{}
	mi := &file_domain_chat_envelope_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FederationDeliverEnvelopeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FederationDeliverEnvelopeResponse) ProtoMessage() {}

func (x *FederationDeliverEnvelopeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_chat_envelope_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FederationDeliverEnvelopeResponse.ProtoReflect.Descriptor instead.
func (*FederationDeliverEnvelopeResponse) Descriptor() ([]byte, []int) {
	return file_domain_chat_envelope_api_proto_rawDescGZIP(), []int{7}
}

var File_domain_chat_envelope_api_proto protoreflect.FileDescriptor

const file_domain_chat_envelope_api_proto_rawDesc = "" +
	"\n" +
	"\x1edomain/chat/envelope_api.proto\x12\x19peers_touch.model.chat.v1\x1a\x1adomain/chat/envelope.proto\"_\n" +
	"\x15SubmitEnvelopeRequest\x12F\n" +
	"\benvelope\x18\x01 \x01(\v2*.peers_touch.model.chat.v1.StationEnvelopeR\benvelope\"9\n" +
	"\x16SubmitEnvelopeResponse\x12\x1f\n" +
	"\venvelope_id\x18\x01 \x01(\tR\n" +
	"envelopeId\"U\n" +
	"\x12AckEnvelopeRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\"\n" +
	"\rinbox_item_id\x18\x02 \x01(\tR\vinboxItemId\"\x15\n" +
	"\x13AckEnvelopeResponse\"X\n" +
	"\x16ResumeEnvelopesRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12!\n" +
	"\fafter_cursor\x18\x02 \x01(\tR\vafterCursor\"[\n" +
	"\x17ResumeEnvelopesResponse\x12@\n" +
	"\x05items\x18\x01 \x03(\v2*.peers_touch.model.chat.v1.DeviceInboxItemR\x05items\"j\n" +
	" FederationDeliverEnvelopeRequest\x12F\n" +
	"\benvelope\x18\x01 \x01(\v2*.peers_touch.model.chat.v1.StationEnvelopeR\benvelope\"#\n" +
	"!FederationDeliverEnvelopeResponseBGZEgithub.com/peers-labs/peers-touch/station/frame/touch/model/chat;chatb\x06proto3"

var (
	file_domain_chat_envelope_api_proto_rawDescOnce sync.Once
	file_domain_chat_envelope_api_proto_rawDescData []byte
)

func file_domain_chat_envelope_api_proto_rawDescGZIP() []byte {
	file_domain_chat_envelope_api_proto_rawDescOnce.Do(func() {
		file_domain_chat_envelope_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_chat_envelope_api_proto_rawDesc), len(file_domain_chat_envelope_api_proto_rawDesc)))
	})
	return file_domain_chat_envelope_api_proto_rawDescData
}

var file_domain_chat_envelope_api_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_domain_chat_envelope_api_proto_goTypes = []any{
	(*SubmitEnvelopeRequest)(nil),             // 0: peers_touch.model.chat.v1.SubmitEnvelopeRequest
	(*SubmitEnvelopeResponse)(nil),            // 1: peers_touch.model.chat.v1.SubmitEnvelopeResponse
	(*AckEnvelopeRequest)(nil),                // 2: peers_touch.model.chat.v1.AckEnvelopeRequest
	(*AckEnvelopeResponse)(nil),               // 3: peers_touch.model.chat.v1.AckEnvelopeResponse
	(*ResumeEnvelopesRequest)(nil),            // 4: peers_touch.model.chat.v1.ResumeEnvelopesRequest
	(*ResumeEnvelopesResponse)(nil),           // 5: peers_touch.model.chat.v1.ResumeEnvelopesResponse
	(*FederationDeliverEnvelopeRequest)(nil),  // 6: peers_touch.model.chat.v1.FederationDeliverEnvelopeRequest
	(*FederationDeliverEnvelopeResponse)(nil), // 7: peers_touch.model.chat.v1.FederationDeliverEnvelopeResponse
	(*StationEnvelope)(nil),                   // 8: peers_touch.model.chat.v1.StationEnvelope
	(*DeviceInboxItem)(nil),                   // 9: peers_touch.model.chat.v1.DeviceInboxItem
}
var file_domain_chat_envelope_api_proto_depIdxs = []int32{
	8, // 0: peers_touch.model.chat.v1.SubmitEnvelopeRequest.envelope:type_name -> peers_touch.model.chat.v1.StationEnvelope
	9, // 1: peers_touch.model.chat.v1.ResumeEnvelopesResponse.items:type_name -> peers_touch.model.chat.v1.DeviceInboxItem
	8, // 2: peers_touch.model.chat.v1.FederationDeliverEnvelopeRequest.envelope:type_name -> peers_touch.model.chat.v1.StationEnvelope
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_domain_chat_envelope_api_proto_init() }
func file_domain_chat_envelope_api_proto_init() {
	if File_domain_chat_envelope_api_proto != nil {
		return
	}
	file_domain_chat_envelope_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_chat_envelope_api_proto_rawDesc), len(file_domain_chat_envelope_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_chat_envelope_api_proto_goTypes,
		DependencyIndexes: file_domain_chat_envelope_api_proto_depIdxs,
		MessageInfos:      file_domain_chat_envelope_api_proto_msgTypes,
	}.Build()
	File_domain_chat_envelope_api_proto = out.File
	file_domain_chat_envelope_api_proto_goTypes = nil
	file_domain_chat_envelope_api_proto_depIdxs = nil
}
