// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: domain/chat/federation.proto

package chat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConversationFollowerProjection struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	FormatVersion           uint32                 `protobuf:"varint,1,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`
	AuthorityStationPeerId  string                 `protobuf:"bytes,2,opt,name=authority_station_peer_id,json=authorityStationPeerId,proto3" json:"authority_station_peer_id,omitempty"`
	TargetHomeStationPeerId string                 `protobuf:"bytes,3,opt,name=target_home_station_peer_id,json=targetHomeStationPeerId,proto3" json:"target_home_station_peer_id,omitempty"`
	ConversationEvent       *ConversationEvent     `protobuf:"bytes,4,opt,name=conversation_event,json=conversationEvent,proto3" json:"conversation_event,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ConversationFollowerProjection) Reset() {
	*x = ConversationFollowerProjection{}
	mi := &file_domain_chat_federation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationFollowerProjection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationFollowerProjection) ProtoMessage() {}

func (x *ConversationFollowerProjection) ProtoReflect() protoreflect.Message {
	mi := &file_domain_chat_federation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationFollowerProjection.ProtoReflect.Descriptor instead.
func (*ConversationFollowerProjection) Descriptor() ([]byte, []int) {
	return file_domain_chat_federation_proto_rawDescGZIP(), []int{0}
}

func (x *ConversationFollowerProjection) GetFormatVersion() uint32 {
	if x != nil {
		return x.FormatVersion
	}
	return 0
}

func (x *ConversationFollowerProjection) GetAuthorityStationPeerId() string {
	if x != nil {
		return x.AuthorityStationPeerId
	}
	return ""
}

func (x *ConversationFollowerProjection) GetTargetHomeStationPeerId() string {
	if x != nil {
		return x.TargetHomeStationPeerId
	}
	return ""
}

func (x *ConversationFollowerProjection) GetConversationEvent() *ConversationEvent {
	if x != nil {
		return x.ConversationEvent
	}
	return nil
}

type ConversationEventProjectionGrant struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	EventId                 string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TargetHomeStationPeerId string                 `protobuf:"bytes,2,opt,name=target_home_station_peer_id,json=targetHomeStationPeerId,proto3" json:"target_home_station_peer_id,omitempty"`
	EntitlementReason       string                 `protobuf:"bytes,3,opt,name=entitlement_reason,json=entitlementReason,proto3" json:"entitlement_reason,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ConversationEventProjectionGrant) Reset() {
	*x = ConversationEventProjectionGrant{}
	mi := &file_domain_chat_federation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationEventProjectionGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationEventProjectionGrant) ProtoMessage() {}

func (x *ConversationEventProjectionGrant) ProtoReflect() protoreflect.Message {
	mi := &file_domain_chat_federation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationEventProjectionGrant.ProtoReflect.Descriptor instead.
func (*ConversationEventProjectionGrant) Descriptor() ([]byte, []int) {
	return file_domain_chat_federation_proto_rawDescGZIP(), []int{1}
}

func (x *ConversationEventProjectionGrant) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ConversationEventProjectionGrant) GetTargetHomeStationPeerId() string {
	if x != nil {
		return x.TargetHomeStationPeerId
	}
	return ""
}

func (x *ConversationEventProjectionGrant) GetEntitlementReason() string {
	if x != nil {
		return x.EntitlementReason
	}
	return ""
}

type GetConversationFollowerEventsRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	FormatVersion           uint32                 `protobuf:"varint,1,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`
	ConversationId          string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	AuthorityStationPeerId  string                 `protobuf:"bytes,3,opt,name=authority_station_peer_id,json=authorityStationPeerId,proto3" json:"authority_station_peer_id,omitempty"`
	TargetHomeStationPeerId string                 `protobuf:"bytes,4,opt,name=target_home_station_peer_id,json=targetHomeStationPeerId,proto3" json:"target_home_station_peer_id,omitempty"`
	AfterSequence           int64                  `protobuf:"varint,5,opt,name=after_sequence,json=afterSequence,proto3" json:"after_sequence,omitempty"`
	AfterEventHash          []byte                 `protobuf:"bytes,6,opt,name=after_event_hash,json=afterEventHash,proto3" json:"after_event_hash,omitempty"`
	RequestNonce            []byte                 `protobuf:"bytes,7,opt,name=request_nonce,json=requestNonce,proto3" json:"request_nonce,omitempty"`
	PageLimit               uint32                 `protobuf:"varint,8,opt,name=page_limit,json=pageLimit,proto3" json:"page_limit,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GetConversationFollowerEventsRequest) Reset() {
	*x = GetConversationFollowerEventsRequest{}
	mi := &file_domain_chat_federation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationFollowerEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationFollowerEventsRequest) ProtoMessage() {}

func (x *GetConversationFollowerEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_chat_federation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationFollowerEventsRequest.ProtoReflect.Descriptor instead.
func (*GetConversationFollowerEventsRequest) Descriptor() ([]byte, []int) {
	return file_domain_chat_federation_proto_rawDescGZIP(), []int{2}
}

func (x *GetConversationFollowerEventsRequest) GetFormatVersion() uint32 {
	if x != nil {
		return x.FormatVersion
	}
	return 0
}

func (x *GetConversationFollowerEventsRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *GetConversationFollowerEventsRequest) GetAuthorityStationPeerId() string {
	if x != nil {
		return x.AuthorityStationPeerId
	}
	return ""
}

func (x *GetConversationFollowerEventsRequest) GetTargetHomeStationPeerId() string {
	if x != nil {
		return x.TargetHomeStationPeerId
	}
	return ""
}

func (x *GetConversationFollowerEventsRequest) GetAfterSequence() int64 {
	if x != nil {
		return x.AfterSequence
	}
	return 0
}

func (x *GetConversationFollowerEventsRequest) GetAfterEventHash() []byte {
	if x != nil {
		return x.AfterEventHash
	}
	return nil
}

func (x *GetConversationFollowerEventsRequest) GetRequestNonce() []byte {
	if x != nil {
		return x.RequestNonce
	}
	return nil
}

func (x *GetConversationFollowerEventsRequest) GetPageLimit() uint32 {
	if x != nil {
		return x.PageLimit
	}
	return 0
}

type ConversationFollowerEventsPage struct {
	state                   protoimpl.MessageState              `protogen:"open.v1"`
	FormatVersion           uint32                              `protobuf:"varint,1,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`
	AuthorityStationPeerId  string                              `protobuf:"bytes,2,opt,name=authority_station_peer_id,json=authorityStationPeerId,proto3" json:"authority_station_peer_id,omitempty"`
	TargetHomeStationPeerId string                              `protobuf:"bytes,3,opt,name=target_home_station_peer_id,json=targetHomeStationPeerId,proto3" json:"target_home_station_peer_id,omitempty"`
	ConversationId          string                              `protobuf:"bytes,4,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	RequestNonce            []byte                              `protobuf:"bytes,5,opt,name=request_nonce,json=requestNonce,proto3" json:"request_nonce,omitempty"`
	ConversationEvents      []*ConversationEvent                `protobuf:"bytes,6,rep,name=conversation_events,json=conversationEvents,proto3" json:"conversation_events,omitempty"`
	EventProjectionGrants   []*ConversationEventProjectionGrant `protobuf:"bytes,7,rep,name=event_projection_grants,json=eventProjectionGrants,proto3" json:"event_projection_grants,omitempty"`
	NextSequence            int64                               `protobuf:"varint,8,opt,name=next_sequence,json=nextSequence,proto3" json:"next_sequence,omitempty"`
	HasMore                 bool                                `protobuf:"varint,9,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	GeneratedAt             *timestamppb.Timestamp              `protobuf:"bytes,10,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	ExpiresAt               *timestamppb.Timestamp              `protobuf:"bytes,11,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	SigningKeyId            string                              `protobuf:"bytes,12,opt,name=signing_key_id,json=signingKeyId,proto3" json:"signing_key_id,omitempty"`
	AuthoritySignature      []byte                              `protobuf:"bytes,13,opt,name=authority_signature,json=authoritySignature,proto3" json:"authority_signature,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ConversationFollowerEventsPage) Reset() {
	*x = ConversationFollowerEventsPage{}
	mi := &file_domain_chat_federation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationFollowerEventsPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationFollowerEventsPage) ProtoMessage() {}

func (x *ConversationFollowerEventsPage) ProtoReflect() protoreflect.Message {
	mi := &file_domain_chat_federation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationFollowerEventsPage.ProtoReflect.Descriptor instead.
func (*ConversationFollowerEventsPage) Descriptor() ([]byte, []int) {
	return file_domain_chat_federation_proto_rawDescGZIP(), []int{3}
}

func (x *ConversationFollowerEventsPage) GetFormatVersion() uint32 {
	if x != nil {
		return x.FormatVersion
	}
	return 0
}

func (x *ConversationFollowerEventsPage) GetAuthorityStationPeerId() string {
	if x != nil {
		return x.AuthorityStationPeerId
	}
	return ""
}

func (x *ConversationFollowerEventsPage) GetTargetHomeStationPeerId() string {
	if x != nil {
		return x.TargetHomeStationPeerId
	}
	return ""
}

func (x *ConversationFollowerEventsPage) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ConversationFollowerEventsPage) GetRequestNonce() []byte {
	if x != nil {
		return x.RequestNonce
	}
	return nil
}

func (x *ConversationFollowerEventsPage) GetConversationEvents() []*ConversationEvent {
	if x != nil {
		return x.ConversationEvents
	}
	return nil
}

func (x *ConversationFollowerEventsPage) GetEventProjectionGrants() []*ConversationEventProjectionGrant {
	if x != nil {
		return x.EventProjectionGrants
	}
	return nil
}

func (x *ConversationFollowerEventsPage) GetNextSequence() int64 {
	if x != nil {
		return x.NextSequence
	}
	return 0
}

func (x *ConversationFollowerEventsPage) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *ConversationFollowerEventsPage) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

func (x *ConversationFollowerEventsPage) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *ConversationFollowerEventsPage) GetSigningKeyId() string {
	if x != nil {
		return x.SigningKeyId
	}
	return ""
}

func (x *ConversationFollowerEventsPage) GetAuthoritySignature() []byte {
	if x != nil {
		return x.AuthoritySignature
	}
	return nil
}

type ConversationFollowerEventsPageSigningInput struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	FormatVersion               uint32                 `protobuf:"varint,1,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`
	AuthorityStationPeerId      string                 `protobuf:"bytes,2,opt,name=authority_station_peer_id,json=authorityStationPeerId,proto3" json:"authority_station_peer_id,omitempty"`
	TargetHomeStationPeerId     string                 `protobuf:"bytes,3,opt,name=target_home_station_peer_id,json=targetHomeStationPeerId,proto3" json:"target_home_station_peer_id,omitempty"`
	ConversationId              string                 `protobuf:"bytes,4,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	RequestNonce                []byte                 `protobuf:"bytes,5,opt,name=request_nonce,json=requestNonce,proto3" json:"request_nonce,omitempty"`
	AfterSequence               int64                  `protobuf:"varint,6,opt,name=after_sequence,json=afterSequence,proto3" json:"after_sequence,omitempty"`
	AfterEventHash              []byte                 `protobuf:"bytes,7,opt,name=after_event_hash,json=afterEventHash,proto3" json:"after_event_hash,omitempty"`
	EventsSha256                []byte                 `protobuf:"bytes,8,opt,name=events_sha256,json=eventsSha256,proto3" json:"events_sha256,omitempty"`
	EventProjectionGrantsSha256 []byte                 `protobuf:"bytes,9,opt,name=event_projection_grants_sha256,json=eventProjectionGrantsSha256,proto3" json:"event_projection_grants_sha256,omitempty"`
	NextSequence                int64                  `protobuf:"varint,10,opt,name=next_sequence,json=nextSequence,proto3" json:"next_sequence,omitempty"`
	HasMore                     bool                   `protobuf:"varint,11,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	GeneratedAt                 *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	ExpiresAt                   *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	SigningKeyId                string                 `protobuf:"bytes,14,opt,name=signing_key_id,json=signingKeyId,proto3" json:"signing_key_id,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *ConversationFollowerEventsPageSigningInput) Reset() {
	*x = ConversationFollowerEventsPageSigningInput{}
	mi := &file_domain_chat_federation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationFollowerEventsPageSigningInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationFollowerEventsPageSigningInput) ProtoMessage() {}

func (x *ConversationFollowerEventsPageSigningInput) ProtoReflect() protoreflect.Message {
	mi := &file_domain_chat_federation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationFollowerEventsPageSigningInput.ProtoReflect.Descriptor instead.
func (*ConversationFollowerEventsPageSigningInput) Descriptor() ([]byte, []int) {
	return file_domain_chat_federation_proto_rawDescGZIP(), []int{4}
}

func (x *ConversationFollowerEventsPageSigningInput) GetFormatVersion() uint32 {
	if x != nil {
		return x.FormatVersion
	}
	return 0
}

func (x *ConversationFollowerEventsPageSigningInput) GetAuthorityStationPeerId() string {
	if x != nil {
		return x.AuthorityStationPeerId
	}
	return ""
}

func (x *ConversationFollowerEventsPageSigningInput) GetTargetHomeStationPeerId() string {
	if x != nil {
		return x.TargetHomeStationPeerId
	}
	return ""
}

func (x *ConversationFollowerEventsPageSigningInput) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ConversationFollowerEventsPageSigningInput) GetRequestNonce() []byte {
	if x != nil {
		return x.RequestNonce
	}
	return nil
}

func (x *ConversationFollowerEventsPageSigningInput) GetAfterSequence() int64 {
	if x != nil {
		return x.AfterSequence
	}
	return 0
}

func (x *ConversationFollowerEventsPageSigningInput) GetAfterEventHash() []byte {
	if x != nil {
		return x.AfterEventHash
	}
	return nil
}

func (x *ConversationFollowerEventsPageSigningInput) GetEventsSha256() []byte {
	if x != nil {
		return x.EventsSha256
	}
	return nil
}

func (x *ConversationFollowerEventsPageSigningInput) GetEventProjectionGrantsSha256() []byte {
	if x != nil {
		return x.EventProjectionGrantsSha256
	}
	return nil
}

func (x *ConversationFollowerEventsPageSigningInput) GetNextSequence() int64 {
	if x != nil {
		return x.NextSequence
	}
	return 0
}

func (x *ConversationFollowerEventsPageSigningInput) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *ConversationFollowerEventsPageSigningInput) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

func (x *ConversationFollowerEventsPageSigningInput) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *ConversationFollowerEventsPageSigningInput) GetSigningKeyId() string {
	if x != nil {
		return x.SigningKeyId
	}
	return ""
}

var File_domain_chat_federation_proto protoreflect.FileDescriptor

const file_domain_chat_federation_proto_rawDesc = "" +
	"\n" +
	"\x1cdomain/chat/federation.proto\x12\x19peers_touch.model.chat.v1\x1a\x17domain/chat/event.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9d\x02\n" +
	"\x1eConversationFollowerProjection\x12%\n" +
	"\x0eformat_version\x18\x01 \x01(\rR\rformatVersion\x129\n" +
	"\x19authority_station_peer_id\x18\x02 \x01(\tR\x16authorityStationPeerId\x12<\n" +
	"\x1btarget_home_station_peer_id\x18\x03 \x01(\tR\x17targetHomeStationPeerId\x12[\n" +
	"\x12conversation_event\x18\x04 \x01(\v2,.peers_touch.model.chat.v1.ConversationEventR\x11conversationEvent\"\xaa\x01\n" +
	" ConversationEventProjectionGrant\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12<\n" +
	"\x1btarget_home_station_peer_id\x18\x02 \x01(\tR\x17targetHomeStationPeerId\x12-\n" +
	"\x12entitlement_reason\x18\x03 \x01(\tR\x11entitlementReason\"\x84\x03\n" +
	"$GetConversationFollowerEventsRequest\x12%\n" +
	"\x0eformat_version\x18\x01 \x01(\rR\rformatVersion\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x129\n" +
	"\x19authority_station_peer_id\x18\x03 \x01(\tR\x16authorityStationPeerId\x12<\n" +
	"\x1btarget_home_station_peer_id\x18\x04 \x01(\tR\x17targetHomeStationPeerId\x12%\n" +
	"\x0eafter_sequence\x18\x05 \x01(\x03R\rafterSequence\x12(\n" +
	"\x10after_event_hash\x18\x06 \x01(\fR\x0eafterEventHash\x12#\n" +
	"\rrequest_nonce\x18\a \x01(\fR\frequestNonce\x12\x1d\n" +
	"\n" +
	"page_limit\x18\b \x01(\rR\tpageLimit\"\xf3\x05\n" +
	"\x1eConversationFollowerEventsPage\x12%\n" +
	"\x0eformat_version\x18\x01 \x01(\rR\rformatVersion\x129\n" +
	"\x19authority_station_peer_id\x18\x02 \x01(\tR\x16authorityStationPeerId\x12<\n" +
	"\x1btarget_home_station_peer_id\x18\x03 \x01(\tR\x17targetHomeStationPeerId\x12'\n" +
	"\x0fconversation_id\x18\x04 \x01(\tR\x0econversationId\x12#\n" +
	"\rrequest_nonce\x18\x05 \x01(\fR\frequestNonce\x12]\n" +
	"\x13conversation_events\x18\x06 \x03(\v2,.peers_touch.model.chat.v1.ConversationEventR\x12conversationEvents\x12s\n" +
	"\x17event_projection_grants\x18\a \x03(\v2;.peers_touch.model.chat.v1.ConversationEventProjectionGrantR\x15eventProjectionGrants\x12#\n" +
	"\rnext_sequence\x18\b \x01(\x03R\fnextSequence\x12\x19\n" +
	"\bhas_more\x18\t \x01(\bR\ahasMore\x12=\n" +
	"\fgenerated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\x129\n" +
	"\n" +
	"expires_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12$\n" +
	"\x0esigning_key_id\x18\f \x01(\tR\fsigningKeyId\x12/\n" +
	"\x13authority_signature\x18\r \x01(\fR\x12authoritySignature\"\xb5\x05\n" +
	"*ConversationFollowerEventsPageSigningInput\x12%\n" +
	"\x0eformat_version\x18\x01 \x01(\rR\rformatVersion\x129\n" +
	"\x19authority_station_peer_id\x18\x02 \x01(\tR\x16authorityStationPeerId\x12<\n" +
	"\x1btarget_home_station_peer_id\x18\x03 \x01(\tR\x17targetHomeStationPeerId\x12'\n" +
	"\x0fconversation_id\x18\x04 \x01(\tR\x0econversationId\x12#\n" +
	"\rrequest_nonce\x18\x05 \x01(\fR\frequestNonce\x12%\n" +
	"\x0eafter_sequence\x18\x06 \x01(\x03R\rafterSequence\x12(\n" +
	"\x10after_event_hash\x18\a \x01(\fR\x0eafterEventHash\x12#\n" +
	"\revents_sha256\x18\b \x01(\fR\feventsSha256\x12C\n" +
	"\x1eevent_projection_grants_sha256\x18\t \x01(\fR\x1beventProjectionGrantsSha256\x12#\n" +
	"\rnext_sequence\x18\n" +
	" \x01(\x03R\fnextSequence\x12\x19\n" +
	"\bhas_more\x18\v \x01(\bR\ahasMore\x12=\n" +
	"\fgenerated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\x129\n" +
	"\n" +
	"expires_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12$\n" +
	"\x0esigning_key_id\x18\x0e \x01(\tR\fsigningKeyIdBGZEgithub.com/peers-labs/peers-touch/station/frame/touch/model/chat;chatb\x06proto3"

var (
	file_domain_chat_federation_proto_rawDescOnce sync.Once
	file_domain_chat_federation_proto_rawDescData []byte
)

func file_domain_chat_federation_proto_rawDescGZIP() []byte {
	file_domain_chat_federation_proto_rawDescOnce.Do(func() {
		file_domain_chat_federation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_chat_federation_proto_rawDesc), len(file_domain_chat_federation_proto_rawDesc)))
	})
	return file_domain_chat_federation_proto_rawDescData
}

var file_domain_chat_federation_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_domain_chat_federation_proto_goTypes = []any{
	(*ConversationFollowerProjection)(nil),             // 0: peers_touch.model.chat.v1.ConversationFollowerProjection
	(*ConversationEventProjectionGrant)(nil),           // 1: peers_touch.model.chat.v1.ConversationEventProjectionGrant
	(*GetConversationFollowerEventsRequest)(nil),       // 2: peers_touch.model.chat.v1.GetConversationFollowerEventsRequest
	(*ConversationFollowerEventsPage)(nil),             // 3: peers_touch.model.chat.v1.ConversationFollowerEventsPage
	(*ConversationFollowerEventsPageSigningInput)(nil), // 4: peers_touch.model.chat.v1.ConversationFollowerEventsPageSigningInput
	(*ConversationEvent)(nil),                          // 5: peers_touch.model.chat.v1.ConversationEvent
	(*timestamppb.Timestamp)(nil),                      // 6: google.protobuf.Timestamp
}
var file_domain_chat_federation_proto_depIdxs = []int32{
	5, // 0: peers_touch.model.chat.v1.ConversationFollowerProjection.conversation_event:type_name -> peers_touch.model.chat.v1.ConversationEvent
	5, // 1: peers_touch.model.chat.v1.ConversationFollowerEventsPage.conversation_events:type_name -> peers_touch.model.chat.v1.ConversationEvent
	1, // 2: peers_touch.model.chat.v1.ConversationFollowerEventsPage.event_projection_grants:type_name -> peers_touch.model.chat.v1.ConversationEventProjectionGrant
	6, // 3: peers_touch.model.chat.v1.ConversationFollowerEventsPage.generated_at:type_name -> google.protobuf.Timestamp
	6, // 4: peers_touch.model.chat.v1.ConversationFollowerEventsPage.expires_at:type_name -> google.protobuf.Timestamp
	6, // 5: peers_touch.model.chat.v1.ConversationFollowerEventsPageSigningInput.generated_at:type_name -> google.protobuf.Timestamp
	6, // 6: peers_touch.model.chat.v1.ConversationFollowerEventsPageSigningInput.expires_at:type_name -> google.protobuf.Timestamp
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_domain_chat_federation_proto_init() }
func file_domain_chat_federation_proto_init() {
	if File_domain_chat_federation_proto != nil {
		return
	}
	file_domain_chat_event_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_chat_federation_proto_rawDesc), len(file_domain_chat_federation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_chat_federation_proto_goTypes,
		DependencyIndexes: file_domain_chat_federation_proto_depIdxs,
		MessageInfos:      file_domain_chat_federation_proto_msgTypes,
	}.Build()
	File_domain_chat_federation_proto = out.File
	file_domain_chat_federation_proto_goTypes = nil
	file_domain_chat_federation_proto_depIdxs = nil
}
