// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: domain/chat/receipt.proto

package chat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceConsumptionReceipt struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ReceiptId      string                 `protobuf:"bytes,1,opt,name=receipt_id,json=receiptId,proto3" json:"receipt_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	EventId        string                 `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Consumer       *CryptoEndpoint        `protobuf:"bytes,4,opt,name=consumer,proto3" json:"consumer,omitempty"`
	EventSequence  int64                  `protobuf:"varint,5,opt,name=event_sequence,json=eventSequence,proto3" json:"event_sequence,omitempty"`
	LaneSequence   int64                  `protobuf:"varint,6,opt,name=lane_sequence,json=laneSequence,proto3" json:"lane_sequence,omitempty"`
	PayloadSha256  []byte                 `protobuf:"bytes,7,opt,name=payload_sha256,json=payloadSha256,proto3" json:"payload_sha256,omitempty"`
	ConsumedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=consumed_at,json=consumedAt,proto3" json:"consumed_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeviceConsumptionReceipt) Reset() {
	*x = DeviceConsumptionReceipt{}
	mi := &file_domain_chat_receipt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceConsumptionReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceConsumptionReceipt) ProtoMessage() {}

func (x *DeviceConsumptionReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_domain_chat_receipt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceConsumptionReceipt.ProtoReflect.Descriptor instead.
func (*DeviceConsumptionReceipt) Descriptor() ([]byte, []int) {
	return file_domain_chat_receipt_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceConsumptionReceipt) GetReceiptId() string {
	if x != nil {
		return x.ReceiptId
	}
	return ""
}

func (x *DeviceConsumptionReceipt) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *DeviceConsumptionReceipt) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *DeviceConsumptionReceipt) GetConsumer() *CryptoEndpoint {
	if x != nil {
		return x.Consumer
	}
	return nil
}

func (x *DeviceConsumptionReceipt) GetEventSequence() int64 {
	if x != nil {
		return x.EventSequence
	}
	return 0
}

func (x *DeviceConsumptionReceipt) GetLaneSequence() int64 {
	if x != nil {
		return x.LaneSequence
	}
	return 0
}

func (x *DeviceConsumptionReceipt) GetPayloadSha256() []byte {
	if x != nil {
		return x.PayloadSha256
	}
	return nil
}

func (x *DeviceConsumptionReceipt) GetConsumedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConsumedAt
	}
	return nil
}

type ActorReadCursor struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ConversationId   string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ReaderPtid       string                 `protobuf:"bytes,2,opt,name=reader_ptid,json=readerPtid,proto3" json:"reader_ptid,omitempty"`
	LastReadSequence int64                  `protobuf:"varint,3,opt,name=last_read_sequence,json=lastReadSequence,proto3" json:"last_read_sequence,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ActorReadCursor) Reset() {
	*x = ActorReadCursor{}
	mi := &file_domain_chat_receipt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorReadCursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorReadCursor) ProtoMessage() {}

func (x *ActorReadCursor) ProtoReflect() protoreflect.Message {
	mi := &file_domain_chat_receipt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorReadCursor.ProtoReflect.Descriptor instead.
func (*ActorReadCursor) Descriptor() ([]byte, []int) {
	return file_domain_chat_receipt_proto_rawDescGZIP(), []int{1}
}

func (x *ActorReadCursor) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ActorReadCursor) GetReaderPtid() string {
	if x != nil {
		return x.ReaderPtid
	}
	return ""
}

func (x *ActorReadCursor) GetLastReadSequence() int64 {
	if x != nil {
		return x.LastReadSequence
	}
	return 0
}

func (x *ActorReadCursor) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type MessageDeliveryAggregate struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ConversationId      string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	EventId             string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventSequence       int64                  `protobuf:"varint,3,opt,name=event_sequence,json=eventSequence,proto3" json:"event_sequence,omitempty"`
	RequiredDeviceCount uint32                 `protobuf:"varint,4,opt,name=required_device_count,json=requiredDeviceCount,proto3" json:"required_device_count,omitempty"`
	ConsumedDeviceCount uint32                 `protobuf:"varint,5,opt,name=consumed_device_count,json=consumedDeviceCount,proto3" json:"consumed_device_count,omitempty"`
	RevokedDeviceCount  uint32                 `protobuf:"varint,6,opt,name=revoked_device_count,json=revokedDeviceCount,proto3" json:"revoked_device_count,omitempty"`
	Delivered           bool                   `protobuf:"varint,7,opt,name=delivered,proto3" json:"delivered,omitempty"`
	FullyDelivered      bool                   `protobuf:"varint,8,opt,name=fully_delivered,json=fullyDelivered,proto3" json:"fully_delivered,omitempty"`
	Read                bool                   `protobuf:"varint,9,opt,name=read,proto3" json:"read,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MessageDeliveryAggregate) Reset() {
	*x = MessageDeliveryAggregate{}
	mi := &file_domain_chat_receipt_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageDeliveryAggregate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageDeliveryAggregate) ProtoMessage() {}

func (x *MessageDeliveryAggregate) ProtoReflect() protoreflect.Message {
	mi := &file_domain_chat_receipt_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageDeliveryAggregate.ProtoReflect.Descriptor instead.
func (*MessageDeliveryAggregate) Descriptor() ([]byte, []int) {
	return file_domain_chat_receipt_proto_rawDescGZIP(), []int{2}
}

func (x *MessageDeliveryAggregate) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *MessageDeliveryAggregate) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *MessageDeliveryAggregate) GetEventSequence() int64 {
	if x != nil {
		return x.EventSequence
	}
	return 0
}

func (x *MessageDeliveryAggregate) GetRequiredDeviceCount() uint32 {
	if x != nil {
		return x.RequiredDeviceCount
	}
	return 0
}

func (x *MessageDeliveryAggregate) GetConsumedDeviceCount() uint32 {
	if x != nil {
		return x.ConsumedDeviceCount
	}
	return 0
}

func (x *MessageDeliveryAggregate) GetRevokedDeviceCount() uint32 {
	if x != nil {
		return x.RevokedDeviceCount
	}
	return 0
}

func (x *MessageDeliveryAggregate) GetDelivered() bool {
	if x != nil {
		return x.Delivered
	}
	return false
}

func (x *MessageDeliveryAggregate) GetFullyDelivered() bool {
	if x != nil {
		return x.FullyDelivered
	}
	return false
}

func (x *MessageDeliveryAggregate) GetRead() bool {
	if x != nil {
		return x.Read
	}
	return false
}

type SubmitConversationReadCursorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        *ActorReadCursor       `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitConversationReadCursorRequest) Reset() {
	*x = SubmitConversationReadCursorRequest{}
	mi := &file_domain_chat_receipt_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitConversationReadCursorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitConversationReadCursorRequest) ProtoMessage() {}

func (x *SubmitConversationReadCursorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_chat_receipt_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitConversationReadCursorRequest.ProtoReflect.Descriptor instead.
func (*SubmitConversationReadCursorRequest) Descriptor() ([]byte, []int) {
	return file_domain_chat_receipt_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitConversationReadCursorRequest) GetCursor() *ActorReadCursor {
	if x != nil {
		return x.Cursor
	}
	return nil
}

type SubmitConversationReadCursorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        *ActorReadCursor       `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitConversationReadCursorResponse) Reset() {
	*x = SubmitConversationReadCursorResponse{}
	mi := &file_domain_chat_receipt_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitConversationReadCursorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitConversationReadCursorResponse) ProtoMessage() {}

func (x *SubmitConversationReadCursorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_chat_receipt_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitConversationReadCursorResponse.ProtoReflect.Descriptor instead.
func (*SubmitConversationReadCursorResponse) Descriptor() ([]byte, []int) {
	return file_domain_chat_receipt_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitConversationReadCursorResponse) GetCursor() *ActorReadCursor {
	if x != nil {
		return x.Cursor
	}
	return nil
}

type SubmitConversationDeliveryReceiptRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Receipt       *DeviceConsumptionReceipt `protobuf:"bytes,1,opt,name=receipt,proto3" json:"receipt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitConversationDeliveryReceiptRequest) Reset() {
	*x = SubmitConversationDeliveryReceiptRequest{}
	mi := &file_domain_chat_receipt_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitConversationDeliveryReceiptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitConversationDeliveryReceiptRequest) ProtoMessage() {}

func (x *SubmitConversationDeliveryReceiptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_chat_receipt_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitConversationDeliveryReceiptRequest.ProtoReflect.Descriptor instead.
func (*SubmitConversationDeliveryReceiptRequest) Descriptor() ([]byte, []int) {
	return file_domain_chat_receipt_proto_rawDescGZIP(), []int{5}
}

func (x *SubmitConversationDeliveryReceiptRequest) GetReceipt() *DeviceConsumptionReceipt {
	if x != nil {
		return x.Receipt
	}
	return nil
}

type SubmitConversationDeliveryReceiptResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Delivery      *MessageDeliveryAggregate `protobuf:"bytes,1,opt,name=delivery,proto3" json:"delivery,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitConversationDeliveryReceiptResponse) Reset() {
	*x = SubmitConversationDeliveryReceiptResponse{}
	mi := &file_domain_chat_receipt_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitConversationDeliveryReceiptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitConversationDeliveryReceiptResponse) ProtoMessage() {}

func (x *SubmitConversationDeliveryReceiptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_chat_receipt_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitConversationDeliveryReceiptResponse.ProtoReflect.Descriptor instead.
func (*SubmitConversationDeliveryReceiptResponse) Descriptor() ([]byte, []int) {
	return file_domain_chat_receipt_proto_rawDescGZIP(), []int{6}
}

func (x *SubmitConversationDeliveryReceiptResponse) GetDelivery() *MessageDeliveryAggregate {
	if x != nil {
		return x.Delivery
	}
	return nil
}

var File_domain_chat_receipt_proto protoreflect.FileDescriptor

const file_domain_chat_receipt_proto_rawDesc = "" +
	"\n" +
	"\x19domain/chat/receipt.proto\x12\x19peers_touch.model.chat.v1\x1a\x1adomain/chat/endpoint.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf4\x02\n" +
	"\x18DeviceConsumptionReceipt\x12\x1d\n" +
	"\n" +
	"receipt_id\x18\x01 \x01(\tR\treceiptId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\x12E\n" +
	"\bconsumer\x18\x04 \x01(\v2).peers_touch.model.chat.v1.CryptoEndpointR\bconsumer\x12%\n" +
	"\x0eevent_sequence\x18\x05 \x01(\x03R\reventSequence\x12#\n" +
	"\rlane_sequence\x18\x06 \x01(\x03R\flaneSequence\x12%\n" +
	"\x0epayload_sha256\x18\a \x01(\fR\rpayloadSha256\x12;\n" +
	"\vconsumed_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"consumedAt\"\xc4\x01\n" +
	"\x0fActorReadCursor\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x1f\n" +
	"\vreader_ptid\x18\x02 \x01(\tR\n" +
	"readerPtid\x12,\n" +
	"\x12last_read_sequence\x18\x03 \x01(\x03R\x10lastReadSequence\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xfa\x02\n" +
	"\x18MessageDeliveryAggregate\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12%\n" +
	"\x0eevent_sequence\x18\x03 \x01(\x03R\reventSequence\x122\n" +
	"\x15required_device_count\x18\x04 \x01(\rR\x13requiredDeviceCount\x122\n" +
	"\x15consumed_device_count\x18\x05 \x01(\rR\x13consumedDeviceCount\x120\n" +
	"\x14revoked_device_count\x18\x06 \x01(\rR\x12revokedDeviceCount\x12\x1c\n" +
	"\tdelivered\x18\a \x01(\bR\tdelivered\x12'\n" +
	"\x0ffully_delivered\x18\b \x01(\bR\x0efullyDelivered\x12\x12\n" +
	"\x04read\x18\t \x01(\bR\x04read\"i\n" +
	"#SubmitConversationReadCursorRequest\x12B\n" +
	"\x06cursor\x18\x01 \x01(\v2*.peers_touch.model.chat.v1.ActorReadCursorR\x06cursor\"j\n" +
	"$SubmitConversationReadCursorResponse\x12B\n" +
	"\x06cursor\x18\x01 \x01(\v2*.peers_touch.model.chat.v1.ActorReadCursorR\x06cursor\"y\n" +
	"(SubmitConversationDeliveryReceiptRequest\x12M\n" +
	"\areceipt\x18\x01 \x01(\v23.peers_touch.model.chat.v1.DeviceConsumptionReceiptR\areceipt\"|\n" +
	")SubmitConversationDeliveryReceiptResponse\x12O\n" +
	"\bdelivery\x18\x01 \x01(\v23.peers_touch.model.chat.v1.MessageDeliveryAggregateR\bdeliveryBGZEgithub.com/peers-labs/peers-touch/station/frame/touch/model/chat;chatb\x06proto3"

var (
	file_domain_chat_receipt_proto_rawDescOnce sync.Once
	file_domain_chat_receipt_proto_rawDescData []byte
)

func file_domain_chat_receipt_proto_rawDescGZIP() []byte {
	file_domain_chat_receipt_proto_rawDescOnce.Do(func() {
		file_domain_chat_receipt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_chat_receipt_proto_rawDesc), len(file_domain_chat_receipt_proto_rawDesc)))
	})
	return file_domain_chat_receipt_proto_rawDescData
}

var file_domain_chat_receipt_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_domain_chat_receipt_proto_goTypes = []any{
	(*DeviceConsumptionReceipt)(nil),                  // 0: peers_touch.model.chat.v1.DeviceConsumptionReceipt
	(*ActorReadCursor)(nil),                           // 1: peers_touch.model.chat.v1.ActorReadCursor
	(*MessageDeliveryAggregate)(nil),                  // 2: peers_touch.model.chat.v1.MessageDeliveryAggregate
	(*SubmitConversationReadCursorRequest)(nil),       // 3: peers_touch.model.chat.v1.SubmitConversationReadCursorRequest
	(*SubmitConversationReadCursorResponse)(nil),      // 4: peers_touch.model.chat.v1.SubmitConversationReadCursorResponse
	(*SubmitConversationDeliveryReceiptRequest)(nil),  // 5: peers_touch.model.chat.v1.SubmitConversationDeliveryReceiptRequest
	(*SubmitConversationDeliveryReceiptResponse)(nil), // 6: peers_touch.model.chat.v1.SubmitConversationDeliveryReceiptResponse
	(*CryptoEndpoint)(nil),                            // 7: peers_touch.model.chat.v1.CryptoEndpoint
	(*timestamppb.Timestamp)(nil),                     // 8: google.protobuf.Timestamp
}
var file_domain_chat_receipt_proto_depIdxs = []int32{
	7, // 0: peers_touch.model.chat.v1.DeviceConsumptionReceipt.consumer:type_name -> peers_touch.model.chat.v1.CryptoEndpoint
	8, // 1: peers_touch.model.chat.v1.DeviceConsumptionReceipt.consumed_at:type_name -> google.protobuf.Timestamp
	8, // 2: peers_touch.model.chat.v1.ActorReadCursor.updated_at:type_name -> google.protobuf.Timestamp
	1, // 3: peers_touch.model.chat.v1.SubmitConversationReadCursorRequest.cursor:type_name -> peers_touch.model.chat.v1.ActorReadCursor
	1, // 4: peers_touch.model.chat.v1.SubmitConversationReadCursorResponse.cursor:type_name -> peers_touch.model.chat.v1.ActorReadCursor
	0, // 5: peers_touch.model.chat.v1.SubmitConversationDeliveryReceiptRequest.receipt:type_name -> peers_touch.model.chat.v1.DeviceConsumptionReceipt
	2, // 6: peers_touch.model.chat.v1.SubmitConversationDeliveryReceiptResponse.delivery:type_name -> peers_touch.model.chat.v1.MessageDeliveryAggregate
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_domain_chat_receipt_proto_init() }
func file_domain_chat_receipt_proto_init() {
	if File_domain_chat_receipt_proto != nil {
		return
	}
	file_domain_chat_endpoint_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_chat_receipt_proto_rawDesc), len(file_domain_chat_receipt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_chat_receipt_proto_goTypes,
		DependencyIndexes: file_domain_chat_receipt_proto_depIdxs,
		MessageInfos:      file_domain_chat_receipt_proto_msgTypes,
	}.Build()
	File_domain_chat_receipt_proto = out.File
	file_domain_chat_receipt_proto_goTypes = nil
	file_domain_chat_receipt_proto_depIdxs = nil
}
