// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: domain/chat/recovery.proto

package chat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecoveryArchiveSectionKind int32

const (
	RecoveryArchiveSectionKind_RECOVERY_ARCHIVE_SECTION_KIND_UNSPECIFIED         RecoveryArchiveSectionKind = 0
	RecoveryArchiveSectionKind_RECOVERY_ARCHIVE_SECTION_KIND_ACTOR_IDENTITY      RecoveryArchiveSectionKind = 1
	RecoveryArchiveSectionKind_RECOVERY_ARCHIVE_SECTION_KIND_MESSAGE_HISTORY     RecoveryArchiveSectionKind = 2
	RecoveryArchiveSectionKind_RECOVERY_ARCHIVE_SECTION_KIND_ATTACHMENT_METADATA RecoveryArchiveSectionKind = 3
	RecoveryArchiveSectionKind_RECOVERY_ARCHIVE_SECTION_KIND_TRUST               RecoveryArchiveSectionKind = 4
)

// Enum value maps for RecoveryArchiveSectionKind.
var (
	RecoveryArchiveSectionKind_name = map[int32]string{
		0: "RECOVERY_ARCHIVE_SECTION_KIND_UNSPECIFIED",
		1: "RECOVERY_ARCHIVE_SECTION_KIND_ACTOR_IDENTITY",
		2: "RECOVERY_ARCHIVE_SECTION_KIND_MESSAGE_HISTORY",
		3: "RECOVERY_ARCHIVE_SECTION_KIND_ATTACHMENT_METADATA",
		4: "RECOVERY_ARCHIVE_SECTION_KIND_TRUST",
	}
	RecoveryArchiveSectionKind_value = map[string]int32{
		"RECOVERY_ARCHIVE_SECTION_KIND_UNSPECIFIED":         0,
		"RECOVERY_ARCHIVE_SECTION_KIND_ACTOR_IDENTITY":      1,
		"RECOVERY_ARCHIVE_SECTION_KIND_MESSAGE_HISTORY":     2,
		"RECOVERY_ARCHIVE_SECTION_KIND_ATTACHMENT_METADATA": 3,
		"RECOVERY_ARCHIVE_SECTION_KIND_TRUST":               4,
	}
)

func (x RecoveryArchiveSectionKind) Enum() *RecoveryArchiveSectionKind {
	p := new(RecoveryArchiveSectionKind)
	*p = x
	return p
}

func (x RecoveryArchiveSectionKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecoveryArchiveSectionKind) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_chat_recovery_proto_enumTypes[0].Descriptor()
}

func (RecoveryArchiveSectionKind) Type() protoreflect.EnumType {
	return &file_domain_chat_recovery_proto_enumTypes[0]
}

func (x RecoveryArchiveSectionKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecoveryArchiveSectionKind.Descriptor instead.
func (RecoveryArchiveSectionKind) EnumDescriptor() ([]byte, []int) {
	return file_domain_chat_recovery_proto_rawDescGZIP(), []int{0}
}

type RecoveryArchiveSection struct {
	state            protoimpl.MessageState     `protogen:"open.v1"`
	Kind             RecoveryArchiveSectionKind `protobuf:"varint,1,opt,name=kind,proto3,enum=peers_touch.model.chat.v1.RecoveryArchiveSectionKind" json:"kind,omitempty"`
	Ciphertext       []byte                     `protobuf:"bytes,2,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	CiphertextSha256 []byte                     `protobuf:"bytes,3,opt,name=ciphertext_sha256,json=ciphertextSha256,proto3" json:"ciphertext_sha256,omitempty"`
	RecordCount      uint64                     `protobuf:"varint,4,opt,name=record_count,json=recordCount,proto3" json:"record_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RecoveryArchiveSection) Reset() {
	*x = RecoveryArchiveSection{}
	mi := &file_domain_chat_recovery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoveryArchiveSection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoveryArchiveSection) ProtoMessage() {}

func (x *RecoveryArchiveSection) ProtoReflect() protoreflect.Message {
	mi := &file_domain_chat_recovery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoveryArchiveSection.ProtoReflect.Descriptor instead.
func (*RecoveryArchiveSection) Descriptor() ([]byte, []int) {
	return file_domain_chat_recovery_proto_rawDescGZIP(), []int{0}
}

func (x *RecoveryArchiveSection) GetKind() RecoveryArchiveSectionKind {
	if x != nil {
		return x.Kind
	}
	return RecoveryArchiveSectionKind_RECOVERY_ARCHIVE_SECTION_KIND_UNSPECIFIED
}

func (x *RecoveryArchiveSection) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *RecoveryArchiveSection) GetCiphertextSha256() []byte {
	if x != nil {
		return x.CiphertextSha256
	}
	return nil
}

func (x *RecoveryArchiveSection) GetRecordCount() uint64 {
	if x != nil {
		return x.RecordCount
	}
	return 0
}

// The encrypted archive intentionally excludes device identity keys, prekeys,
// Direct ratchets, skipped message keys, and live MLS state.
type RecoveryArchiveManifest struct {
	state             protoimpl.MessageState    `protogen:"open.v1"`
	FormatVersion     uint32                    `protobuf:"varint,1,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`
	Ptid              string                    `protobuf:"bytes,2,opt,name=ptid,proto3" json:"ptid,omitempty"`
	RevisionId        string                    `protobuf:"bytes,3,opt,name=revision_id,json=revisionId,proto3" json:"revision_id,omitempty"`
	Sections          []*RecoveryArchiveSection `protobuf:"bytes,4,rep,name=sections,proto3" json:"sections,omitempty"`
	ArchiveSha256     []byte                    `protobuf:"bytes,5,opt,name=archive_sha256,json=archiveSha256,proto3" json:"archive_sha256,omitempty"`
	CreatedAt         *timestamppb.Timestamp    `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedByDeviceId string                    `protobuf:"bytes,7,opt,name=created_by_device_id,json=createdByDeviceId,proto3" json:"created_by_device_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RecoveryArchiveManifest) Reset() {
	*x = RecoveryArchiveManifest{}
	mi := &file_domain_chat_recovery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoveryArchiveManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoveryArchiveManifest) ProtoMessage() {}

func (x *RecoveryArchiveManifest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_chat_recovery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoveryArchiveManifest.ProtoReflect.Descriptor instead.
func (*RecoveryArchiveManifest) Descriptor() ([]byte, []int) {
	return file_domain_chat_recovery_proto_rawDescGZIP(), []int{1}
}

func (x *RecoveryArchiveManifest) GetFormatVersion() uint32 {
	if x != nil {
		return x.FormatVersion
	}
	return 0
}

func (x *RecoveryArchiveManifest) GetPtid() string {
	if x != nil {
		return x.Ptid
	}
	return ""
}

func (x *RecoveryArchiveManifest) GetRevisionId() string {
	if x != nil {
		return x.RevisionId
	}
	return ""
}

func (x *RecoveryArchiveManifest) GetSections() []*RecoveryArchiveSection {
	if x != nil {
		return x.Sections
	}
	return nil
}

func (x *RecoveryArchiveManifest) GetArchiveSha256() []byte {
	if x != nil {
		return x.ArchiveSha256
	}
	return nil
}

func (x *RecoveryArchiveManifest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RecoveryArchiveManifest) GetCreatedByDeviceId() string {
	if x != nil {
		return x.CreatedByDeviceId
	}
	return ""
}

type PutRecoveryRevisionRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	RevisionId             string                 `protobuf:"bytes,1,opt,name=revision_id,json=revisionId,proto3" json:"revision_id,omitempty"`
	FormatVersion          uint32                 `protobuf:"varint,2,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`
	EncryptedArchive       []byte                 `protobuf:"bytes,3,opt,name=encrypted_archive,json=encryptedArchive,proto3" json:"encrypted_archive,omitempty"`
	EncryptedArchiveSha256 []byte                 `protobuf:"bytes,4,opt,name=encrypted_archive_sha256,json=encryptedArchiveSha256,proto3" json:"encrypted_archive_sha256,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PutRecoveryRevisionRequest) Reset() {
	*x = PutRecoveryRevisionRequest{}
	mi := &file_domain_chat_recovery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRecoveryRevisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRecoveryRevisionRequest) ProtoMessage() {}

func (x *PutRecoveryRevisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_chat_recovery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRecoveryRevisionRequest.ProtoReflect.Descriptor instead.
func (*PutRecoveryRevisionRequest) Descriptor() ([]byte, []int) {
	return file_domain_chat_recovery_proto_rawDescGZIP(), []int{2}
}

func (x *PutRecoveryRevisionRequest) GetRevisionId() string {
	if x != nil {
		return x.RevisionId
	}
	return ""
}

func (x *PutRecoveryRevisionRequest) GetFormatVersion() uint32 {
	if x != nil {
		return x.FormatVersion
	}
	return 0
}

func (x *PutRecoveryRevisionRequest) GetEncryptedArchive() []byte {
	if x != nil {
		return x.EncryptedArchive
	}
	return nil
}

func (x *PutRecoveryRevisionRequest) GetEncryptedArchiveSha256() []byte {
	if x != nil {
		return x.EncryptedArchiveSha256
	}
	return nil
}

type PutRecoveryRevisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RevisionId    string                 `protobuf:"bytes,1,opt,name=revision_id,json=revisionId,proto3" json:"revision_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRecoveryRevisionResponse) Reset() {
	*x = PutRecoveryRevisionResponse{}
	mi := &file_domain_chat_recovery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRecoveryRevisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRecoveryRevisionResponse) ProtoMessage() {}

func (x *PutRecoveryRevisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_chat_recovery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRecoveryRevisionResponse.ProtoReflect.Descriptor instead.
func (*PutRecoveryRevisionResponse) Descriptor() ([]byte, []int) {
	return file_domain_chat_recovery_proto_rawDescGZIP(), []int{3}
}

func (x *PutRecoveryRevisionResponse) GetRevisionId() string {
	if x != nil {
		return x.RevisionId
	}
	return ""
}

func (x *PutRecoveryRevisionResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetLatestRecoveryRevisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestRecoveryRevisionRequest) Reset() {
	*x = GetLatestRecoveryRevisionRequest{}
	mi := &file_domain_chat_recovery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestRecoveryRevisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestRecoveryRevisionRequest) ProtoMessage() {}

func (x *GetLatestRecoveryRevisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_chat_recovery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestRecoveryRevisionRequest.ProtoReflect.Descriptor instead.
func (*GetLatestRecoveryRevisionRequest) Descriptor() ([]byte, []int) {
	return file_domain_chat_recovery_proto_rawDescGZIP(), []int{4}
}

type GetLatestRecoveryRevisionResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	RevisionId             string                 `protobuf:"bytes,1,opt,name=revision_id,json=revisionId,proto3" json:"revision_id,omitempty"`
	FormatVersion          uint32                 `protobuf:"varint,2,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`
	EncryptedArchive       []byte                 `protobuf:"bytes,3,opt,name=encrypted_archive,json=encryptedArchive,proto3" json:"encrypted_archive,omitempty"`
	EncryptedArchiveSha256 []byte                 `protobuf:"bytes,4,opt,name=encrypted_archive_sha256,json=encryptedArchiveSha256,proto3" json:"encrypted_archive_sha256,omitempty"`
	CreatedAt              *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetLatestRecoveryRevisionResponse) Reset() {
	*x = GetLatestRecoveryRevisionResponse{}
	mi := &file_domain_chat_recovery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestRecoveryRevisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestRecoveryRevisionResponse) ProtoMessage() {}

func (x *GetLatestRecoveryRevisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_chat_recovery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestRecoveryRevisionResponse.ProtoReflect.Descriptor instead.
func (*GetLatestRecoveryRevisionResponse) Descriptor() ([]byte, []int) {
	return file_domain_chat_recovery_proto_rawDescGZIP(), []int{5}
}

func (x *GetLatestRecoveryRevisionResponse) GetRevisionId() string {
	if x != nil {
		return x.RevisionId
	}
	return ""
}

func (x *GetLatestRecoveryRevisionResponse) GetFormatVersion() uint32 {
	if x != nil {
		return x.FormatVersion
	}
	return 0
}

func (x *GetLatestRecoveryRevisionResponse) GetEncryptedArchive() []byte {
	if x != nil {
		return x.EncryptedArchive
	}
	return nil
}

func (x *GetLatestRecoveryRevisionResponse) GetEncryptedArchiveSha256() []byte {
	if x != nil {
		return x.EncryptedArchiveSha256
	}
	return nil
}

func (x *GetLatestRecoveryRevisionResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_domain_chat_recovery_proto protoreflect.FileDescriptor

const file_domain_chat_recovery_proto_rawDesc = "" +
	"\n" +
	"\x1adomain/chat/recovery.proto\x12\x19peers_touch.model.chat.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd3\x01\n" +
	"\x16RecoveryArchiveSection\x12I\n" +
	"\x04kind\x18\x01 \x01(\x0e25.peers_touch.model.chat.v1.RecoveryArchiveSectionKindR\x04kind\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x02 \x01(\fR\n" +
	"ciphertext\x12+\n" +
	"\x11ciphertext_sha256\x18\x03 \x01(\fR\x10ciphertextSha256\x12!\n" +
	"\frecord_count\x18\x04 \x01(\x04R\vrecordCount\"\xd7\x02\n" +
	"\x17RecoveryArchiveManifest\x12%\n" +
	"\x0eformat_version\x18\x01 \x01(\rR\rformatVersion\x12\x12\n" +
	"\x04ptid\x18\x02 \x01(\tR\x04ptid\x12\x1f\n" +
	"\vrevision_id\x18\x03 \x01(\tR\n" +
	"revisionId\x12M\n" +
	"\bsections\x18\x04 \x03(\v21.peers_touch.model.chat.v1.RecoveryArchiveSectionR\bsections\x12%\n" +
	"\x0earchive_sha256\x18\x05 \x01(\fR\rarchiveSha256\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12/\n" +
	"\x14created_by_device_id\x18\a \x01(\tR\x11createdByDeviceId\"\xcb\x01\n" +
	"\x1aPutRecoveryRevisionRequest\x12\x1f\n" +
	"\vrevision_id\x18\x01 \x01(\tR\n" +
	"revisionId\x12%\n" +
	"\x0eformat_version\x18\x02 \x01(\rR\rformatVersion\x12+\n" +
	"\x11encrypted_archive\x18\x03 \x01(\fR\x10encryptedArchive\x128\n" +
	"\x18encrypted_archive_sha256\x18\x04 \x01(\fR\x16encryptedArchiveSha256\"y\n" +
	"\x1bPutRecoveryRevisionResponse\x12\x1f\n" +
	"\vrevision_id\x18\x01 \x01(\tR\n" +
	"revisionId\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\"\n" +
	" GetLatestRecoveryRevisionRequest\"\x8d\x02\n" +
	"!GetLatestRecoveryRevisionResponse\x12\x1f\n" +
	"\vrevision_id\x18\x01 \x01(\tR\n" +
	"revisionId\x12%\n" +
	"\x0eformat_version\x18\x02 \x01(\rR\rformatVersion\x12+\n" +
	"\x11encrypted_archive\x18\x03 \x01(\fR\x10encryptedArchive\x128\n" +
	"\x18encrypted_archive_sha256\x18\x04 \x01(\fR\x16encryptedArchiveSha256\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt*\x90\x02\n" +
	"\x1aRecoveryArchiveSectionKind\x12-\n" +
	")RECOVERY_ARCHIVE_SECTION_KIND_UNSPECIFIED\x10\x00\x120\n" +
	",RECOVERY_ARCHIVE_SECTION_KIND_ACTOR_IDENTITY\x10\x01\x121\n" +
	"-RECOVERY_ARCHIVE_SECTION_KIND_MESSAGE_HISTORY\x10\x02\x125\n" +
	"1RECOVERY_ARCHIVE_SECTION_KIND_ATTACHMENT_METADATA\x10\x03\x12'\n" +
	"#RECOVERY_ARCHIVE_SECTION_KIND_TRUST\x10\x04BGZEgithub.com/peers-labs/peers-touch/station/frame/touch/model/chat;chatb\x06proto3"

var (
	file_domain_chat_recovery_proto_rawDescOnce sync.Once
	file_domain_chat_recovery_proto_rawDescData []byte
)

func file_domain_chat_recovery_proto_rawDescGZIP() []byte {
	file_domain_chat_recovery_proto_rawDescOnce.Do(func() {
		file_domain_chat_recovery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_chat_recovery_proto_rawDesc), len(file_domain_chat_recovery_proto_rawDesc)))
	})
	return file_domain_chat_recovery_proto_rawDescData
}

var file_domain_chat_recovery_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_domain_chat_recovery_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_domain_chat_recovery_proto_goTypes = []any{
	(RecoveryArchiveSectionKind)(0),           // 0: peers_touch.model.chat.v1.RecoveryArchiveSectionKind
	(*RecoveryArchiveSection)(nil),            // 1: peers_touch.model.chat.v1.RecoveryArchiveSection
	(*RecoveryArchiveManifest)(nil),           // 2: peers_touch.model.chat.v1.RecoveryArchiveManifest
	(*PutRecoveryRevisionRequest)(nil),        // 3: peers_touch.model.chat.v1.PutRecoveryRevisionRequest
	(*PutRecoveryRevisionResponse)(nil),       // 4: peers_touch.model.chat.v1.PutRecoveryRevisionResponse
	(*GetLatestRecoveryRevisionRequest)(nil),  // 5: peers_touch.model.chat.v1.GetLatestRecoveryRevisionRequest
	(*GetLatestRecoveryRevisionResponse)(nil), // 6: peers_touch.model.chat.v1.GetLatestRecoveryRevisionResponse
	(*timestamppb.Timestamp)(nil),             // 7: google.protobuf.Timestamp
}
var file_domain_chat_recovery_proto_depIdxs = []int32{
	0, // 0: peers_touch.model.chat.v1.RecoveryArchiveSection.kind:type_name -> peers_touch.model.chat.v1.RecoveryArchiveSectionKind
	1, // 1: peers_touch.model.chat.v1.RecoveryArchiveManifest.sections:type_name -> peers_touch.model.chat.v1.RecoveryArchiveSection
	7, // 2: peers_touch.model.chat.v1.RecoveryArchiveManifest.created_at:type_name -> google.protobuf.Timestamp
	7, // 3: peers_touch.model.chat.v1.PutRecoveryRevisionResponse.created_at:type_name -> google.protobuf.Timestamp
	7, // 4: peers_touch.model.chat.v1.GetLatestRecoveryRevisionResponse.created_at:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_domain_chat_recovery_proto_init() }
func file_domain_chat_recovery_proto_init() {
	if File_domain_chat_recovery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_chat_recovery_proto_rawDesc), len(file_domain_chat_recovery_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_chat_recovery_proto_goTypes,
		DependencyIndexes: file_domain_chat_recovery_proto_depIdxs,
		EnumInfos:         file_domain_chat_recovery_proto_enumTypes,
		MessageInfos:      file_domain_chat_recovery_proto_msgTypes,
	}.Build()
	File_domain_chat_recovery_proto = out.File
	file_domain_chat_recovery_proto_goTypes = nil
	file_domain_chat_recovery_proto_depIdxs = nil
}
