// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: domain/ai_box/send_message_request.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TopicId       string                 `protobuf:"bytes,2,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Attachments   []*MessageAttachment   `protobuf:"bytes,4,rep,name=attachments,proto3" json:"attachments,omitempty"`
	MetadataJson  string                 `protobuf:"bytes,5,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	Stream        bool                   `protobuf:"varint,6,opt,name=stream,proto3" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_domain_ai_box_send_message_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_ai_box_send_message_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_domain_ai_box_send_message_request_proto_rawDescGZIP(), []int{0}
}

func (x *SendMessageRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SendMessageRequest) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

func (x *SendMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendMessageRequest) GetAttachments() []*MessageAttachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *SendMessageRequest) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *SendMessageRequest) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

var File_domain_ai_box_send_message_request_proto protoreflect.FileDescriptor

const file_domain_ai_box_send_message_request_proto_rawDesc = "" +
	"\n" +
	"(domain/ai_box/send_message_request.proto\x12\x1bpeers_touch.model.ai_box.v1\x1a&domain/ai_box/message_attachment.proto\"\xf7\x01\n" +
	"\x12SendMessageRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\btopic_id\x18\x02 \x01(\tR\atopicId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12P\n" +
	"\vattachments\x18\x04 \x03(\v2..peers_touch.model.ai_box.v1.MessageAttachmentR\vattachments\x12#\n" +
	"\rmetadata_json\x18\x05 \x01(\tR\fmetadataJson\x12\x16\n" +
	"\x06stream\x18\x06 \x01(\bR\x06streamBLZJgithub.com/peers-labs/peers-touch/station/app/subserver/ai-box/model;modelb\x06proto3"

var (
	file_domain_ai_box_send_message_request_proto_rawDescOnce sync.Once
	file_domain_ai_box_send_message_request_proto_rawDescData []byte
)

func file_domain_ai_box_send_message_request_proto_rawDescGZIP() []byte {
	file_domain_ai_box_send_message_request_proto_rawDescOnce.Do(func() {
		file_domain_ai_box_send_message_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_ai_box_send_message_request_proto_rawDesc), len(file_domain_ai_box_send_message_request_proto_rawDesc)))
	})
	return file_domain_ai_box_send_message_request_proto_rawDescData
}

var file_domain_ai_box_send_message_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_domain_ai_box_send_message_request_proto_goTypes = []any{
	(*SendMessageRequest)(nil), // 0: peers_touch.model.ai_box.v1.SendMessageRequest
	(*MessageAttachment)(nil),  // 1: peers_touch.model.ai_box.v1.MessageAttachment
}
var file_domain_ai_box_send_message_request_proto_depIdxs = []int32{
	1, // 0: peers_touch.model.ai_box.v1.SendMessageRequest.attachments:type_name -> peers_touch.model.ai_box.v1.MessageAttachment
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_domain_ai_box_send_message_request_proto_init() }
func file_domain_ai_box_send_message_request_proto_init() {
	if File_domain_ai_box_send_message_request_proto != nil {
		return
	}
	file_domain_ai_box_message_attachment_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_ai_box_send_message_request_proto_rawDesc), len(file_domain_ai_box_send_message_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_ai_box_send_message_request_proto_goTypes,
		DependencyIndexes: file_domain_ai_box_send_message_request_proto_depIdxs,
		MessageInfos:      file_domain_ai_box_send_message_request_proto_msgTypes,
	}.Build()
	File_domain_ai_box_send_message_request_proto = out.File
	file_domain_ai_box_send_message_request_proto_goTypes = nil
	file_domain_ai_box_send_message_request_proto_depIdxs = nil
}
