SHELL := bash
export PATH := /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$(PATH)
.DEFAULT_GOAL := help

# ─── Include split modules ───────────────────────────────────────
include tooling/make/local-dev.mk
include tooling/make/station-go.mk
include tooling/make/monorepo.mk
include tooling/make/proto.mk
include tooling/make/qa.mk
include tooling/make/review.mk
include tooling/make/acceptance.mk
include tooling/make/prototypes.mk
include tooling/make/docker.mk
include tooling/make/deploy.mk
include tooling/make/setup.mk

# ─── Help ────────────────────────────────────────────────────────

.PHONY: help help-docker help-deploy

help:
	@echo ""
	@echo "Peers-Touch"
	@echo "==========="
	@echo ""
	@echo "Local Dev (worktree-isolated):"
	@echo "  make env-register ...          Register this workspace, profile, slot, and capabilities"
	@echo "  make env-update ...            Update this workspace's authoritative binding"
	@echo "  make env-unregister            Remove this idle workspace registration"
	@echo "  make env-check ...             Verify binding, topology, slot, and capabilities"
	@echo "  make env-status-all            Show all bindings and observed OS-held leases"
	@echo "  make dev-observe               Report this worktree to the observation ledger"
	@echo "  make workflow-snapshot         Print the canonical workflow projection"
	@echo "  make workflow-doctor           Verify installed integration and workflow truth"
	@echo "  make profile <name>            Update this registered workspace's profile binding"
	@echo "  make profile-authorize <name> [SLOT=0]  Human authorization for local profile creation"
	@echo "  make profile-init <name> [SLOT=0]  Consume authorization and create local profile"
	@echo "  make profiles                  List approved and unapproved profile observations"
	@echo "  make config                    Show active profile config"
	@echo "  make dev-start ...             Publish work intent and optional PLAN/TASK locator"
	@echo "  make dev-update WORK_ITEM=x    Refresh work intent, source, and PLAN/TASK locator"
	@echo "  make dev-status [WORK_ITEM=x]  Show this worktree's development declarations"
	@echo "  make dev-status-all            Show machine-wide development declarations"
	@echo "  make dev-check WORK_ITEM=x     Verify the current declaration before writes/runtime"
	@echo "  make dev-heartbeat WORK_ITEM=x Extend the current declaration expiry"
	@echo "  make dev-release WORK_ITEM=x   Release the current development declaration"
	@echo "  make active-work-sync WORK_ITEM=x  Derive this worktree's active-work record from owners"
	@echo "  make active-work-status        Show this worktree's active-work record"
	@echo "  make active-work-status-all    Read all workspace-owned records"
	@echo "  make active-work-close WORK_ITEM=x EXPECTED_REVISION=n  Close this record with CAS"
	@echo "  make plan-mount PLAN=<path>    Mount one frozen Plan Version in this workspace"
	@echo "  make plan-mount-status         Show this workspace's live Plan mount and run"
	@echo "  make plan-unmount REASON=<reason>  Release a completed/cancelled or owner-authorized mount"
	@echo ""
	@echo "  make station                   Ready Station (local start / remote deploy)"
	@echo "  make station-check             Health-check Station only"
	@echo "  make station-status            Show Station deployment/runtime status"
	@echo "  make station-logs              Show Station logs"
	@echo "  make relay                     Ready Relay (remote deploy)"
	@echo "  make relay-check               Health-check Relay only"
	@echo "  make relay-status              Show Relay deployment/runtime status"
	@echo "  make relay-logs                Show Relay logs"
	@echo "  make desktop                   Start Desktop App"
	@echo "  make desktop-install           Build and install current source as Peers Dev.app"
	@echo "  make mobile                    Start Mobile iOS Simulator"
	@echo ""
	@echo "Development workflow:"
	@echo "  make dev-start WORK_ITEM=<id> PURPOSE='<text>' SOURCE_CLAIMS='<claims>' [PLAN=<path> TASK=<id>]"
	@echo "  make dev-check WORK_ITEM=<id>  Verify the active resource declaration"
	@echo "  make dev-status [WORK_ITEM=<id>]  Show declaration status"
	@echo "  make plan-validate PLAN=<path> Validate a frozen Plan Version"
	@echo "  make plan-status PLAN=<path>   Show current Task and ready frontier"
	@echo "  make plan-current PLAN=<path>  Show the current Task"
	@echo "  make plan-next PLAN=<path>     Show dependency-ready Tasks"
	@echo "  make plan-activate PLAN=<path> TASK=<id>  Activate one prepared Plan"
	@echo "  make plan-advance PLAN=<path> WORK_ITEM=<id> TO=<state>  Close or park the current Task"
	@echo "  make plan-reopen PLAN=<path> WORK_ITEM=<id>  Reopen the earliest stale review"
	@echo "  make dev-session-start WORK_ITEM=<id> TASK=<id> JOURNEY=<id> [PLAN=<path>]"
	@echo "  make dev-session-status WORK_ITEM=<id>  Show Development Session state"
	@echo "  make dev-transition WORK_ITEM=<id> TO=<state> REASON='<text>'"
	@echo "  make dev-functional-result WORK_ITEM=<id> REASON='<text>' [RUNTIME_CELL=<cell>]"
	@echo "  make completion-review-prepare WORK_ITEM=<id> [SCOPE=<task|plan>]"
	@echo "  make completion-review-submit REVIEW=<id> VERDICT=<PASS|FAIL> ASSESSMENT=<json-file> CAPABILITY=<json-file>"
	@echo "  make completion-review-status WORK_ITEM=<id>"
	@echo ""
	@echo "  make status                    Show running services"
	@echo "  make stop                      Stop all services"
	@echo "  make restart                   Restart all services"
	@echo "  make station-restart           Restart Station only"
	@echo "  make relay-restart             Restart Relay only"
	@echo "  make desktop-restart           Restart Desktop only"
	@echo "  make mobile-restart            Restart Mobile only"
	@echo ""
	@echo "Checks:"
	@echo "  make check                     Go format check"
	@echo "  make vet                       Go vet"
	@echo "  make style                     Go style check"
	@echo "  make lint                      Go lint (golangci-lint)"
	@echo "  make test-unit                 Go unit tests"
	@echo "  make mono-check                pnpm workspace checks"
	@echo "  make mono-build                pnpm workspace build"
	@echo "  make model-gen                 Generate proto code"
	@echo "  make review REVIEW_RANGE=<range>  Run code review framework checks"
	@echo "  make review-submit REVIEW_BASE=<base>  Run submit-time review pipeline before PR/MR"
	@echo "  make quality-evidence REVIEW_RANGE=<range>  Aggregate review, knowledge, and acceptance evidence"
	@echo "  make acceptance-validate [DOMAIN=<name>]  Validate acceptance domain contracts"
	@echo "  make acceptance-plan           Show current closure Acceptance projection"
	@echo "  make acceptance-plan-self      Run the Acceptance planner self-check"
	@echo "  make acceptance PLAN=<path>    Run an explicit acceptance plan"
	@echo "  make acceptance-run            Run current closure Acceptance"
	@echo "  make acceptance-run-completion Run current plan completion Acceptance"
	@echo "  make acceptance-run-full       Run explicit full/release Acceptance"
	@echo "  make acceptance-run-ci         Run planned ci-structure and ci-cheap gates"
	@echo "  make acceptance-report         Render latest acceptance report"
	@echo "  make run-prototype             Start prototype portal (exclusive per worktree)"
	@echo "  make -w run-prototype          Start another prototype portal on the next free port"
	@echo ""
	@echo "More:"
	@echo "  make help-docker               Docker deployment commands"
	@echo "  make help-deploy               Remote deploy commands"
	@echo "  make init-dev                  Initialize dev environment"
	@echo "  make skills IDE=<host>         Install Skills plus workflow hooks and audit them"
	@echo "  make agent-integration-audit IDE=<host>  Verify installed project integration"
	@echo ""

help-docker:
	@echo ""
	@echo "Docker Deployment"
	@echo "================="
	@echo "  make docker-station            Build & deploy Station"
	@echo "  make docker-relay              Build & deploy Relay"
	@echo "  make docker-all                Build & deploy all"
	@echo "  make docker-infra              Start PostgreSQL"
	@echo "  make docker-down               Stop all containers"
	@echo "  make docker-logs               Tail container logs"
	@echo "  make docker-ps                 Show running containers"
	@echo "  make docker-remotes            List Docker contexts"
	@echo ""
	@echo "  Add REMOTE=<context> for remote deployment."
	@echo ""

help-deploy:
	@echo ""
	@echo "Remote Deployment (pull model)"
	@echo "=============================="
	@echo "  make deploy ENV=<name>         Deploy to remote host"
	@echo "  make deploy ENV=<name> BRANCH=feat/x  Deploy specific branch"
	@echo "  make deploy-status ENV=<name>  Check remote status"
	@echo "  make deploy-logs ENV=<name>    Fetch remote logs"
	@echo ""
	@echo "  Env files: .local/deploy/envs/<name>.env"
	@echo "  Required vars: PT_DEPLOY_HOST, PT_DEPLOY_USER,"
	@echo "                 PT_DEPLOY_PATH, PT_DEPLOY_ROLE"
	@echo ""
