packages:
  - apps/mobile
  - apps/desktop
  - apps/desktop/applets-dev/*
  - apps/station/app/subserver/dashboard/web
  - packages/model
  - packages/sdk/ts
  - packages/ui/desktop
  - packages/applet-sdk
  - packages/applet-contract
  - packages/applets/*
