[package]
name = "peers-touch-mobile"
version = "0.1.0"
edition = "2021"

[lib]
name = "peers_touch_mobile_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.1", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
tauri = { version = "2.0.1", features = [] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
