// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: domain/error/error.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED                        ErrorCode = 0
	ErrorCode_ERROR_CODE_UNDEFINED                          ErrorCode = 1
	ErrorCode_ERROR_CODE_WELL_KNOWN_INVALID_RESOURCE_FORMAT ErrorCode = 10001
	ErrorCode_ERROR_CODE_WELL_KNOWN_UNSUPPORTED_PREFIX_TYPE ErrorCode = 10002
	ErrorCode_ERROR_CODE_ACTOR_INVALID_NAME                 ErrorCode = 10003
	ErrorCode_ERROR_CODE_ACTOR_INVALID_EMAIL                ErrorCode = 10004
	ErrorCode_ERROR_CODE_ACTOR_INVALID_PASSWORD             ErrorCode = 10005
	ErrorCode_ERROR_CODE_ACTOR_EXISTS                       ErrorCode = 10006
	ErrorCode_ERROR_CODE_ACTOR_INVALID_PASSPORT             ErrorCode = 10007
	ErrorCode_ERROR_CODE_ACTOR_NOT_FOUND                    ErrorCode = 10008
	ErrorCode_ERROR_CODE_ACTOR_INVALID_CREDENTIALS          ErrorCode = 10009
	ErrorCode_ERROR_CODE_PEER_ADDR_EXISTS                   ErrorCode = 10010
	ErrorCode_ERROR_CODE_UNAUTHORIZED                       ErrorCode = 20001
	ErrorCode_ERROR_CODE_INVALID_REQUEST                    ErrorCode = 20002
	ErrorCode_ERROR_CODE_INVALID_QUERY_PARAMETERS           ErrorCode = 20003
	ErrorCode_ERROR_CODE_INVALID_REQUEST_BODY               ErrorCode = 20004
	ErrorCode_ERROR_CODE_INVALID_PROTOBUF                   ErrorCode = 20005
	ErrorCode_ERROR_CODE_FAILED_TO_READ_BODY                ErrorCode = 20006
	ErrorCode_ERROR_CODE_METHOD_NOT_ALLOWED                 ErrorCode = 20007
	ErrorCode_ERROR_CODE_INTERNAL_SERVER_ERROR              ErrorCode = 20008
	ErrorCode_ERROR_CODE_POST_ID_REQUIRED                   ErrorCode = 30001
	ErrorCode_ERROR_CODE_POST_NOT_FOUND                     ErrorCode = 30002
	ErrorCode_ERROR_CODE_USER_ID_REQUIRED                   ErrorCode = 30003
	ErrorCode_ERROR_CODE_CREATE_POST_FAILED                 ErrorCode = 30004
	ErrorCode_ERROR_CODE_UPDATE_POST_FAILED                 ErrorCode = 30005
	ErrorCode_ERROR_CODE_DELETE_POST_FAILED                 ErrorCode = 30006
	ErrorCode_ERROR_CODE_LIKE_POST_FAILED                   ErrorCode = 30007
	ErrorCode_ERROR_CODE_UNLIKE_POST_FAILED                 ErrorCode = 30008
	ErrorCode_ERROR_CODE_GET_POST_FAILED                    ErrorCode = 30009
	ErrorCode_ERROR_CODE_LIST_POSTS_FAILED                  ErrorCode = 30010
	ErrorCode_ERROR_CODE_REPOST_FAILED                      ErrorCode = 30011
	ErrorCode_ERROR_CODE_GET_LIKERS_FAILED                  ErrorCode = 30012
	ErrorCode_ERROR_CODE_GET_TIMELINE_FAILED                ErrorCode = 30013
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:     "ERROR_CODE_UNSPECIFIED",
		1:     "ERROR_CODE_UNDEFINED",
		10001: "ERROR_CODE_WELL_KNOWN_INVALID_RESOURCE_FORMAT",
		10002: "ERROR_CODE_WELL_KNOWN_UNSUPPORTED_PREFIX_TYPE",
		10003: "ERROR_CODE_ACTOR_INVALID_NAME",
		10004: "ERROR_CODE_ACTOR_INVALID_EMAIL",
		10005: "ERROR_CODE_ACTOR_INVALID_PASSWORD",
		10006: "ERROR_CODE_ACTOR_EXISTS",
		10007: "ERROR_CODE_ACTOR_INVALID_PASSPORT",
		10008: "ERROR_CODE_ACTOR_NOT_FOUND",
		10009: "ERROR_CODE_ACTOR_INVALID_CREDENTIALS",
		10010: "ERROR_CODE_PEER_ADDR_EXISTS",
		20001: "ERROR_CODE_UNAUTHORIZED",
		20002: "ERROR_CODE_INVALID_REQUEST",
		20003: "ERROR_CODE_INVALID_QUERY_PARAMETERS",
		20004: "ERROR_CODE_INVALID_REQUEST_BODY",
		20005: "ERROR_CODE_INVALID_PROTOBUF",
		20006: "ERROR_CODE_FAILED_TO_READ_BODY",
		20007: "ERROR_CODE_METHOD_NOT_ALLOWED",
		20008: "ERROR_CODE_INTERNAL_SERVER_ERROR",
		30001: "ERROR_CODE_POST_ID_REQUIRED",
		30002: "ERROR_CODE_POST_NOT_FOUND",
		30003: "ERROR_CODE_USER_ID_REQUIRED",
		30004: "ERROR_CODE_CREATE_POST_FAILED",
		30005: "ERROR_CODE_UPDATE_POST_FAILED",
		30006: "ERROR_CODE_DELETE_POST_FAILED",
		30007: "ERROR_CODE_LIKE_POST_FAILED",
		30008: "ERROR_CODE_UNLIKE_POST_FAILED",
		30009: "ERROR_CODE_GET_POST_FAILED",
		30010: "ERROR_CODE_LIST_POSTS_FAILED",
		30011: "ERROR_CODE_REPOST_FAILED",
		30012: "ERROR_CODE_GET_LIKERS_FAILED",
		30013: "ERROR_CODE_GET_TIMELINE_FAILED",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":                        0,
		"ERROR_CODE_UNDEFINED":                          1,
		"ERROR_CODE_WELL_KNOWN_INVALID_RESOURCE_FORMAT": 10001,
		"ERROR_CODE_WELL_KNOWN_UNSUPPORTED_PREFIX_TYPE": 10002,
		"ERROR_CODE_ACTOR_INVALID_NAME":                 10003,
		"ERROR_CODE_ACTOR_INVALID_EMAIL":                10004,
		"ERROR_CODE_ACTOR_INVALID_PASSWORD":             10005,
		"ERROR_CODE_ACTOR_EXISTS":                       10006,
		"ERROR_CODE_ACTOR_INVALID_PASSPORT":             10007,
		"ERROR_CODE_ACTOR_NOT_FOUND":                    10008,
		"ERROR_CODE_ACTOR_INVALID_CREDENTIALS":          10009,
		"ERROR_CODE_PEER_ADDR_EXISTS":                   10010,
		"ERROR_CODE_UNAUTHORIZED":                       20001,
		"ERROR_CODE_INVALID_REQUEST":                    20002,
		"ERROR_CODE_INVALID_QUERY_PARAMETERS":           20003,
		"ERROR_CODE_INVALID_REQUEST_BODY":               20004,
		"ERROR_CODE_INVALID_PROTOBUF":                   20005,
		"ERROR_CODE_FAILED_TO_READ_BODY":                20006,
		"ERROR_CODE_METHOD_NOT_ALLOWED":                 20007,
		"ERROR_CODE_INTERNAL_SERVER_ERROR":              20008,
		"ERROR_CODE_POST_ID_REQUIRED":                   30001,
		"ERROR_CODE_POST_NOT_FOUND":                     30002,
		"ERROR_CODE_USER_ID_REQUIRED":                   30003,
		"ERROR_CODE_CREATE_POST_FAILED":                 30004,
		"ERROR_CODE_UPDATE_POST_FAILED":                 30005,
		"ERROR_CODE_DELETE_POST_FAILED":                 30006,
		"ERROR_CODE_LIKE_POST_FAILED":                   30007,
		"ERROR_CODE_UNLIKE_POST_FAILED":                 30008,
		"ERROR_CODE_GET_POST_FAILED":                    30009,
		"ERROR_CODE_LIST_POSTS_FAILED":                  30010,
		"ERROR_CODE_REPOST_FAILED":                      30011,
		"ERROR_CODE_GET_LIKERS_FAILED":                  30012,
		"ERROR_CODE_GET_TIMELINE_FAILED":                30013,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_error_error_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_domain_error_error_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_domain_error_error_proto_rawDescGZIP(), []int{0}
}

type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=peers_touch.model.error.v1.ErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_domain_error_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_error_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_domain_error_error_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorResponse) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_domain_error_error_proto protoreflect.FileDescriptor

const file_domain_error_error_proto_rawDesc = "" +
	"\n" +
	"\x18domain/error/error.proto\x12\x1apeers_touch.model.error.v1\"\xf2\x01\n" +
	"\rErrorResponse\x129\n" +
	"\x04code\x18\x01 \x01(\x0e2%.peers_touch.model.error.v1.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12P\n" +
	"\adetails\x18\x03 \x03(\v26.peers_touch.model.error.v1.ErrorResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xc5\t\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ERROR_CODE_UNDEFINED\x10\x01\x122\n" +
	"-ERROR_CODE_WELL_KNOWN_INVALID_RESOURCE_FORMAT\x10\x91N\x122\n" +
	"-ERROR_CODE_WELL_KNOWN_UNSUPPORTED_PREFIX_TYPE\x10\x92N\x12\"\n" +
	"\x1dERROR_CODE_ACTOR_INVALID_NAME\x10\x93N\x12#\n" +
	"\x1eERROR_CODE_ACTOR_INVALID_EMAIL\x10\x94N\x12&\n" +
	"!ERROR_CODE_ACTOR_INVALID_PASSWORD\x10\x95N\x12\x1c\n" +
	"\x17ERROR_CODE_ACTOR_EXISTS\x10\x96N\x12&\n" +
	"!ERROR_CODE_ACTOR_INVALID_PASSPORT\x10\x97N\x12\x1f\n" +
	"\x1aERROR_CODE_ACTOR_NOT_FOUND\x10\x98N\x12)\n" +
	"$ERROR_CODE_ACTOR_INVALID_CREDENTIALS\x10\x99N\x12 \n" +
	"\x1bERROR_CODE_PEER_ADDR_EXISTS\x10\x9aN\x12\x1d\n" +
	"\x17ERROR_CODE_UNAUTHORIZED\x10\xa1\x9c\x01\x12 \n" +
	"\x1aERROR_CODE_INVALID_REQUEST\x10\xa2\x9c\x01\x12)\n" +
	"#ERROR_CODE_INVALID_QUERY_PARAMETERS\x10\xa3\x9c\x01\x12%\n" +
	"\x1fERROR_CODE_INVALID_REQUEST_BODY\x10\xa4\x9c\x01\x12!\n" +
	"\x1bERROR_CODE_INVALID_PROTOBUF\x10\xa5\x9c\x01\x12$\n" +
	"\x1eERROR_CODE_FAILED_TO_READ_BODY\x10\xa6\x9c\x01\x12#\n" +
	"\x1dERROR_CODE_METHOD_NOT_ALLOWED\x10\xa7\x9c\x01\x12&\n" +
	" ERROR_CODE_INTERNAL_SERVER_ERROR\x10\xa8\x9c\x01\x12!\n" +
	"\x1bERROR_CODE_POST_ID_REQUIRED\x10\xb1\xea\x01\x12\x1f\n" +
	"\x19ERROR_CODE_POST_NOT_FOUND\x10\xb2\xea\x01\x12!\n" +
	"\x1bERROR_CODE_USER_ID_REQUIRED\x10\xb3\xea\x01\x12#\n" +
	"\x1dERROR_CODE_CREATE_POST_FAILED\x10\xb4\xea\x01\x12#\n" +
	"\x1dERROR_CODE_UPDATE_POST_FAILED\x10\xb5\xea\x01\x12#\n" +
	"\x1dERROR_CODE_DELETE_POST_FAILED\x10\xb6\xea\x01\x12!\n" +
	"\x1bERROR_CODE_LIKE_POST_FAILED\x10\xb7\xea\x01\x12#\n" +
	"\x1dERROR_CODE_UNLIKE_POST_FAILED\x10\xb8\xea\x01\x12 \n" +
	"\x1aERROR_CODE_GET_POST_FAILED\x10\xb9\xea\x01\x12\"\n" +
	"\x1cERROR_CODE_LIST_POSTS_FAILED\x10\xba\xea\x01\x12\x1e\n" +
	"\x18ERROR_CODE_REPOST_FAILED\x10\xbb\xea\x01\x12\"\n" +
	"\x1cERROR_CODE_GET_LIKERS_FAILED\x10\xbc\xea\x01\x12$\n" +
	"\x1eERROR_CODE_GET_TIMELINE_FAILED\x10\xbd\xea\x01BCZAgithub.com/peers-labs/peers-touch/station/frame/touch/model;modelb\x06proto3"

var (
	file_domain_error_error_proto_rawDescOnce sync.Once
	file_domain_error_error_proto_rawDescData []byte
)

func file_domain_error_error_proto_rawDescGZIP() []byte {
	file_domain_error_error_proto_rawDescOnce.Do(func() {
		file_domain_error_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_error_error_proto_rawDesc), len(file_domain_error_error_proto_rawDesc)))
	})
	return file_domain_error_error_proto_rawDescData
}

var file_domain_error_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_domain_error_error_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_domain_error_error_proto_goTypes = []any{
	(ErrorCode)(0),        // 0: peers_touch.model.error.v1.ErrorCode
	(*ErrorResponse)(nil), // 1: peers_touch.model.error.v1.ErrorResponse
	nil,                   // 2: peers_touch.model.error.v1.ErrorResponse.DetailsEntry
}
var file_domain_error_error_proto_depIdxs = []int32{
	0, // 0: peers_touch.model.error.v1.ErrorResponse.code:type_name -> peers_touch.model.error.v1.ErrorCode
	2, // 1: peers_touch.model.error.v1.ErrorResponse.details:type_name -> peers_touch.model.error.v1.ErrorResponse.DetailsEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_domain_error_error_proto_init() }
func file_domain_error_error_proto_init() {
	if File_domain_error_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_error_error_proto_rawDesc), len(file_domain_error_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_error_error_proto_goTypes,
		DependencyIndexes: file_domain_error_error_proto_depIdxs,
		EnumInfos:         file_domain_error_error_proto_enumTypes,
		MessageInfos:      file_domain_error_error_proto_msgTypes,
	}.Build()
	File_domain_error_error_proto = out.File
	file_domain_error_error_proto_goTypes = nil
	file_domain_error_error_proto_depIdxs = nil
}
