platform :ios, '17.0'

inhibit_all_warnings!
use_frameworks!

target 'PeersTouch' do
  pod 'Lynx', '3.6.0', :subspecs => ['Framework']
  pod 'PrimJS', '3.6.1', :subspecs => ['quickjs', 'napi']
  pod 'LynxService', '3.6.0', :subspecs => ['Image', 'Log', 'Http']
  pod 'SDWebImage', '~> 5.15'
  pod 'SwiftProtobuf', '~> 1.28'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'
    end
  end
end
