// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: domain/federation/federation_health.proto
// Protobuf Java Version: 4.34.1

package peers_touch.model.federation.v1;

@com.google.protobuf.Generated
public final class FederationHealth {
  private FederationHealth() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface FederationHealthViewOrBuilder extends
      // @@protoc_insertion_point(interface_extends:peers_touch.model.federation.v1.FederationHealthView)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * True iff the local kad-DHT routing table has at least
     * `min_dht_peers` peers AND the bootstrap subserver has begun
     * executing. False during the first few seconds of a cold start.
     * </pre>
     *
     * <code>bool ready = 1;</code>
     * @return The ready.
     */
    boolean getReady();

    /**
     * <pre>
     * Current routing table size — peers reachable for GetValue /
     * PutValue. Below `min_dht_peers` the resolver gates remote
     * resolves with HTTP 503 + ErrFederationNotReady.
     * </pre>
     *
     * <code>int32 peers_in_routing_table = 2 [json_name = "peers_in_routing_table"];</code>
     * @return The peersInRoutingTable.
     */
    int getPeersInRoutingTable();

    /**
     * <pre>
     * libp2p host total connected peers. Broader than the routing
     * table — includes direct dials, relay-circuit connections, and
     * peers we are connected to but have not yet exchanged DHT
     * records with.
     * </pre>
     *
     * <code>int32 connected_peers = 3 [json_name = "connected_peers"];</code>
     * @return The connectedPeers.
     */
    int getConnectedPeers();

    /**
     * <pre>
     * Configured federation seeds AFTER the self-filter (a station
     * never lists itself as a seed). Static after boot.
     * </pre>
     *
     * <code>int32 seeds_configured = 4 [json_name = "seeds_configured"];</code>
     * @return The seedsConfigured.
     */
    int getSeedsConfigured();

    /**
     * <pre>
     * Seeds with libp2p Connectedness == Connected RIGHT NOW. May be
     * less than `seeds_configured` even when ready=true if the DHT
     * has learned about other peers via the seed and the seed
     * connection then dropped.
     * </pre>
     *
     * <code>int32 seeds_connected = 5 [json_name = "seeds_connected"];</code>
     * @return The seedsConnected.
     */
    int getSeedsConnected();

    /**
     * <pre>
     * Effective threshold (post policy clamp). Always &gt;= 1 in
     * production; a negative value here means an operator has
     * explicitly disabled the gate (ready always true once Start runs).
     * </pre>
     *
     * <code>int32 min_dht_peers = 6 [json_name = "min_dht_peers"];</code>
     * @return The minDhtPeers.
     */
    int getMinDhtPeers();

    /**
     * <pre>
     * Stable identity of this station. Echoes the local libp2p PeerID
     * and HTTP origin a federation locator record carries, so an
     * external monitor can correlate health snapshots with locator
     * records they may also be observing.
     * </pre>
     *
     * <code>string station_peer_id = 7 [json_name = "station_peer_id"];</code>
     * @return The stationPeerId.
     */
    java.lang.String getStationPeerId();
    /**
     * <pre>
     * Stable identity of this station. Echoes the local libp2p PeerID
     * and HTTP origin a federation locator record carries, so an
     * external monitor can correlate health snapshots with locator
     * records they may also be observing.
     * </pre>
     *
     * <code>string station_peer_id = 7 [json_name = "station_peer_id"];</code>
     * @return The bytes for stationPeerId.
     */
    com.google.protobuf.ByteString
        getStationPeerIdBytes();

    /**
     * <code>string station_domain = 8 [json_name = "station_domain"];</code>
     * @return The stationDomain.
     */
    java.lang.String getStationDomain();
    /**
     * <code>string station_domain = 8 [json_name = "station_domain"];</code>
     * @return The bytes for stationDomain.
     */
    com.google.protobuf.ByteString
        getStationDomainBytes();

    /**
     * <pre>
     * RFC-3339 wall-clock time bootstrap.Start() began. Empty when
     * the bootstrap subserver has not yet started — clients should
     * treat that as not-ready. Paired with `uptime_seconds` for
     * human-readable diagnostics.
     * </pre>
     *
     * <code>string boot_started_at = 9 [json_name = "boot_started_at"];</code>
     * @return The bootStartedAt.
     */
    java.lang.String getBootStartedAt();
    /**
     * <pre>
     * RFC-3339 wall-clock time bootstrap.Start() began. Empty when
     * the bootstrap subserver has not yet started — clients should
     * treat that as not-ready. Paired with `uptime_seconds` for
     * human-readable diagnostics.
     * </pre>
     *
     * <code>string boot_started_at = 9 [json_name = "boot_started_at"];</code>
     * @return The bytes for bootStartedAt.
     */
    com.google.protobuf.ByteString
        getBootStartedAtBytes();

    /**
     * <code>int64 uptime_seconds = 10 [json_name = "uptime_seconds"];</code>
     * @return The uptimeSeconds.
     */
    long getUptimeSeconds();
  }
  /**
   * Protobuf type {@code peers_touch.model.federation.v1.FederationHealthView}
   */
  public  static final class FederationHealthView extends
      com.google.protobuf.GeneratedMessageLite<
          FederationHealthView, FederationHealthView.Builder> implements
      // @@protoc_insertion_point(message_implements:peers_touch.model.federation.v1.FederationHealthView)
      FederationHealthViewOrBuilder {
    private FederationHealthView() {
      stationPeerId_ = "";
      stationDomain_ = "";
      bootStartedAt_ = "";
    }
    public static final int READY_FIELD_NUMBER = 1;
    private boolean ready_;
    /**
     * <pre>
     * True iff the local kad-DHT routing table has at least
     * `min_dht_peers` peers AND the bootstrap subserver has begun
     * executing. False during the first few seconds of a cold start.
     * </pre>
     *
     * <code>bool ready = 1;</code>
     * @return The ready.
     */
    @java.lang.Override
    public boolean getReady() {
      return ready_;
    }
    /**
     * <pre>
     * True iff the local kad-DHT routing table has at least
     * `min_dht_peers` peers AND the bootstrap subserver has begun
     * executing. False during the first few seconds of a cold start.
     * </pre>
     *
     * <code>bool ready = 1;</code>
     * @param value The ready to set.
     */
    private void setReady(boolean value) {
      
      ready_ = value;
    }
    /**
     * <pre>
     * True iff the local kad-DHT routing table has at least
     * `min_dht_peers` peers AND the bootstrap subserver has begun
     * executing. False during the first few seconds of a cold start.
     * </pre>
     *
     * <code>bool ready = 1;</code>
     */
    private void clearReady() {

      ready_ = false;
    }

    public static final int PEERS_IN_ROUTING_TABLE_FIELD_NUMBER = 2;
    private int peersInRoutingTable_;
    /**
     * <pre>
     * Current routing table size — peers reachable for GetValue /
     * PutValue. Below `min_dht_peers` the resolver gates remote
     * resolves with HTTP 503 + ErrFederationNotReady.
     * </pre>
     *
     * <code>int32 peers_in_routing_table = 2 [json_name = "peers_in_routing_table"];</code>
     * @return The peersInRoutingTable.
     */
    @java.lang.Override
    public int getPeersInRoutingTable() {
      return peersInRoutingTable_;
    }
    /**
     * <pre>
     * Current routing table size — peers reachable for GetValue /
     * PutValue. Below `min_dht_peers` the resolver gates remote
     * resolves with HTTP 503 + ErrFederationNotReady.
     * </pre>
     *
     * <code>int32 peers_in_routing_table = 2 [json_name = "peers_in_routing_table"];</code>
     * @param value The peersInRoutingTable to set.
     */
    private void setPeersInRoutingTable(int value) {
      
      peersInRoutingTable_ = value;
    }
    /**
     * <pre>
     * Current routing table size — peers reachable for GetValue /
     * PutValue. Below `min_dht_peers` the resolver gates remote
     * resolves with HTTP 503 + ErrFederationNotReady.
     * </pre>
     *
     * <code>int32 peers_in_routing_table = 2 [json_name = "peers_in_routing_table"];</code>
     */
    private void clearPeersInRoutingTable() {

      peersInRoutingTable_ = 0;
    }

    public static final int CONNECTED_PEERS_FIELD_NUMBER = 3;
    private int connectedPeers_;
    /**
     * <pre>
     * libp2p host total connected peers. Broader than the routing
     * table — includes direct dials, relay-circuit connections, and
     * peers we are connected to but have not yet exchanged DHT
     * records with.
     * </pre>
     *
     * <code>int32 connected_peers = 3 [json_name = "connected_peers"];</code>
     * @return The connectedPeers.
     */
    @java.lang.Override
    public int getConnectedPeers() {
      return connectedPeers_;
    }
    /**
     * <pre>
     * libp2p host total connected peers. Broader than the routing
     * table — includes direct dials, relay-circuit connections, and
     * peers we are connected to but have not yet exchanged DHT
     * records with.
     * </pre>
     *
     * <code>int32 connected_peers = 3 [json_name = "connected_peers"];</code>
     * @param value The connectedPeers to set.
     */
    private void setConnectedPeers(int value) {
      
      connectedPeers_ = value;
    }
    /**
     * <pre>
     * libp2p host total connected peers. Broader than the routing
     * table — includes direct dials, relay-circuit connections, and
     * peers we are connected to but have not yet exchanged DHT
     * records with.
     * </pre>
     *
     * <code>int32 connected_peers = 3 [json_name = "connected_peers"];</code>
     */
    private void clearConnectedPeers() {

      connectedPeers_ = 0;
    }

    public static final int SEEDS_CONFIGURED_FIELD_NUMBER = 4;
    private int seedsConfigured_;
    /**
     * <pre>
     * Configured federation seeds AFTER the self-filter (a station
     * never lists itself as a seed). Static after boot.
     * </pre>
     *
     * <code>int32 seeds_configured = 4 [json_name = "seeds_configured"];</code>
     * @return The seedsConfigured.
     */
    @java.lang.Override
    public int getSeedsConfigured() {
      return seedsConfigured_;
    }
    /**
     * <pre>
     * Configured federation seeds AFTER the self-filter (a station
     * never lists itself as a seed). Static after boot.
     * </pre>
     *
     * <code>int32 seeds_configured = 4 [json_name = "seeds_configured"];</code>
     * @param value The seedsConfigured to set.
     */
    private void setSeedsConfigured(int value) {
      
      seedsConfigured_ = value;
    }
    /**
     * <pre>
     * Configured federation seeds AFTER the self-filter (a station
     * never lists itself as a seed). Static after boot.
     * </pre>
     *
     * <code>int32 seeds_configured = 4 [json_name = "seeds_configured"];</code>
     */
    private void clearSeedsConfigured() {

      seedsConfigured_ = 0;
    }

    public static final int SEEDS_CONNECTED_FIELD_NUMBER = 5;
    private int seedsConnected_;
    /**
     * <pre>
     * Seeds with libp2p Connectedness == Connected RIGHT NOW. May be
     * less than `seeds_configured` even when ready=true if the DHT
     * has learned about other peers via the seed and the seed
     * connection then dropped.
     * </pre>
     *
     * <code>int32 seeds_connected = 5 [json_name = "seeds_connected"];</code>
     * @return The seedsConnected.
     */
    @java.lang.Override
    public int getSeedsConnected() {
      return seedsConnected_;
    }
    /**
     * <pre>
     * Seeds with libp2p Connectedness == Connected RIGHT NOW. May be
     * less than `seeds_configured` even when ready=true if the DHT
     * has learned about other peers via the seed and the seed
     * connection then dropped.
     * </pre>
     *
     * <code>int32 seeds_connected = 5 [json_name = "seeds_connected"];</code>
     * @param value The seedsConnected to set.
     */
    private void setSeedsConnected(int value) {
      
      seedsConnected_ = value;
    }
    /**
     * <pre>
     * Seeds with libp2p Connectedness == Connected RIGHT NOW. May be
     * less than `seeds_configured` even when ready=true if the DHT
     * has learned about other peers via the seed and the seed
     * connection then dropped.
     * </pre>
     *
     * <code>int32 seeds_connected = 5 [json_name = "seeds_connected"];</code>
     */
    private void clearSeedsConnected() {

      seedsConnected_ = 0;
    }

    public static final int MIN_DHT_PEERS_FIELD_NUMBER = 6;
    private int minDhtPeers_;
    /**
     * <pre>
     * Effective threshold (post policy clamp). Always &gt;= 1 in
     * production; a negative value here means an operator has
     * explicitly disabled the gate (ready always true once Start runs).
     * </pre>
     *
     * <code>int32 min_dht_peers = 6 [json_name = "min_dht_peers"];</code>
     * @return The minDhtPeers.
     */
    @java.lang.Override
    public int getMinDhtPeers() {
      return minDhtPeers_;
    }
    /**
     * <pre>
     * Effective threshold (post policy clamp). Always &gt;= 1 in
     * production; a negative value here means an operator has
     * explicitly disabled the gate (ready always true once Start runs).
     * </pre>
     *
     * <code>int32 min_dht_peers = 6 [json_name = "min_dht_peers"];</code>
     * @param value The minDhtPeers to set.
     */
    private void setMinDhtPeers(int value) {
      
      minDhtPeers_ = value;
    }
    /**
     * <pre>
     * Effective threshold (post policy clamp). Always &gt;= 1 in
     * production; a negative value here means an operator has
     * explicitly disabled the gate (ready always true once Start runs).
     * </pre>
     *
     * <code>int32 min_dht_peers = 6 [json_name = "min_dht_peers"];</code>
     */
    private void clearMinDhtPeers() {

      minDhtPeers_ = 0;
    }

    public static final int STATION_PEER_ID_FIELD_NUMBER = 7;
    private java.lang.String stationPeerId_;
    /**
     * <pre>
     * Stable identity of this station. Echoes the local libp2p PeerID
     * and HTTP origin a federation locator record carries, so an
     * external monitor can correlate health snapshots with locator
     * records they may also be observing.
     * </pre>
     *
     * <code>string station_peer_id = 7 [json_name = "station_peer_id"];</code>
     * @return The stationPeerId.
     */
    @java.lang.Override
    public java.lang.String getStationPeerId() {
      return stationPeerId_;
    }
    /**
     * <pre>
     * Stable identity of this station. Echoes the local libp2p PeerID
     * and HTTP origin a federation locator record carries, so an
     * external monitor can correlate health snapshots with locator
     * records they may also be observing.
     * </pre>
     *
     * <code>string station_peer_id = 7 [json_name = "station_peer_id"];</code>
     * @return The bytes for stationPeerId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStationPeerIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(stationPeerId_);
    }
    /**
     * <pre>
     * Stable identity of this station. Echoes the local libp2p PeerID
     * and HTTP origin a federation locator record carries, so an
     * external monitor can correlate health snapshots with locator
     * records they may also be observing.
     * </pre>
     *
     * <code>string station_peer_id = 7 [json_name = "station_peer_id"];</code>
     * @param value The stationPeerId to set.
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void setStationPeerId(
        java.lang.String value) {
      value.getClass();  // minimal bytecode null check

      stationPeerId_ = value;
    }
    /**
     * <pre>
     * Stable identity of this station. Echoes the local libp2p PeerID
     * and HTTP origin a federation locator record carries, so an
     * external monitor can correlate health snapshots with locator
     * records they may also be observing.
     * </pre>
     *
     * <code>string station_peer_id = 7 [json_name = "station_peer_id"];</code>
     */
    private void clearStationPeerId() {

      stationPeerId_ = getDefaultInstance().getStationPeerId();
    }
    /**
     * <pre>
     * Stable identity of this station. Echoes the local libp2p PeerID
     * and HTTP origin a federation locator record carries, so an
     * external monitor can correlate health snapshots with locator
     * records they may also be observing.
     * </pre>
     *
     * <code>string station_peer_id = 7 [json_name = "station_peer_id"];</code>
     * @param value The bytes for stationPeerId to set.
     */
    private void setStationPeerIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      stationPeerId_ = value.toStringUtf8();

    }

    public static final int STATION_DOMAIN_FIELD_NUMBER = 8;
    private java.lang.String stationDomain_;
    /**
     * <code>string station_domain = 8 [json_name = "station_domain"];</code>
     * @return The stationDomain.
     */
    @java.lang.Override
    public java.lang.String getStationDomain() {
      return stationDomain_;
    }
    /**
     * <code>string station_domain = 8 [json_name = "station_domain"];</code>
     * @return The bytes for stationDomain.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStationDomainBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(stationDomain_);
    }
    /**
     * <code>string station_domain = 8 [json_name = "station_domain"];</code>
     * @param value The stationDomain to set.
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void setStationDomain(
        java.lang.String value) {
      value.getClass();  // minimal bytecode null check

      stationDomain_ = value;
    }
    /**
     * <code>string station_domain = 8 [json_name = "station_domain"];</code>
     */
    private void clearStationDomain() {

      stationDomain_ = getDefaultInstance().getStationDomain();
    }
    /**
     * <code>string station_domain = 8 [json_name = "station_domain"];</code>
     * @param value The bytes for stationDomain to set.
     */
    private void setStationDomainBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      stationDomain_ = value.toStringUtf8();

    }

    public static final int BOOT_STARTED_AT_FIELD_NUMBER = 9;
    private java.lang.String bootStartedAt_;
    /**
     * <pre>
     * RFC-3339 wall-clock time bootstrap.Start() began. Empty when
     * the bootstrap subserver has not yet started — clients should
     * treat that as not-ready. Paired with `uptime_seconds` for
     * human-readable diagnostics.
     * </pre>
     *
     * <code>string boot_started_at = 9 [json_name = "boot_started_at"];</code>
     * @return The bootStartedAt.
     */
    @java.lang.Override
    public java.lang.String getBootStartedAt() {
      return bootStartedAt_;
    }
    /**
     * <pre>
     * RFC-3339 wall-clock time bootstrap.Start() began. Empty when
     * the bootstrap subserver has not yet started — clients should
     * treat that as not-ready. Paired with `uptime_seconds` for
     * human-readable diagnostics.
     * </pre>
     *
     * <code>string boot_started_at = 9 [json_name = "boot_started_at"];</code>
     * @return The bytes for bootStartedAt.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBootStartedAtBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(bootStartedAt_);
    }
    /**
     * <pre>
     * RFC-3339 wall-clock time bootstrap.Start() began. Empty when
     * the bootstrap subserver has not yet started — clients should
     * treat that as not-ready. Paired with `uptime_seconds` for
     * human-readable diagnostics.
     * </pre>
     *
     * <code>string boot_started_at = 9 [json_name = "boot_started_at"];</code>
     * @param value The bootStartedAt to set.
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void setBootStartedAt(
        java.lang.String value) {
      value.getClass();  // minimal bytecode null check

      bootStartedAt_ = value;
    }
    /**
     * <pre>
     * RFC-3339 wall-clock time bootstrap.Start() began. Empty when
     * the bootstrap subserver has not yet started — clients should
     * treat that as not-ready. Paired with `uptime_seconds` for
     * human-readable diagnostics.
     * </pre>
     *
     * <code>string boot_started_at = 9 [json_name = "boot_started_at"];</code>
     */
    private void clearBootStartedAt() {

      bootStartedAt_ = getDefaultInstance().getBootStartedAt();
    }
    /**
     * <pre>
     * RFC-3339 wall-clock time bootstrap.Start() began. Empty when
     * the bootstrap subserver has not yet started — clients should
     * treat that as not-ready. Paired with `uptime_seconds` for
     * human-readable diagnostics.
     * </pre>
     *
     * <code>string boot_started_at = 9 [json_name = "boot_started_at"];</code>
     * @param value The bytes for bootStartedAt to set.
     */
    private void setBootStartedAtBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      bootStartedAt_ = value.toStringUtf8();

    }

    public static final int UPTIME_SECONDS_FIELD_NUMBER = 10;
    private long uptimeSeconds_;
    /**
     * <code>int64 uptime_seconds = 10 [json_name = "uptime_seconds"];</code>
     * @return The uptimeSeconds.
     */
    @java.lang.Override
    public long getUptimeSeconds() {
      return uptimeSeconds_;
    }
    /**
     * <code>int64 uptime_seconds = 10 [json_name = "uptime_seconds"];</code>
     * @param value The uptimeSeconds to set.
     */
    private void setUptimeSeconds(long value) {
      
      uptimeSeconds_ = value;
    }
    /**
     * <code>int64 uptime_seconds = 10 [json_name = "uptime_seconds"];</code>
     */
    private void clearUptimeSeconds() {

      uptimeSeconds_ = 0L;
    }

    public static peers_touch.model.federation.v1.FederationHealth.FederationHealthView parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static peers_touch.model.federation.v1.FederationHealth.FederationHealthView parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static peers_touch.model.federation.v1.FederationHealth.FederationHealthView parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static peers_touch.model.federation.v1.FederationHealth.FederationHealthView parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static peers_touch.model.federation.v1.FederationHealth.FederationHealthView parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static peers_touch.model.federation.v1.FederationHealth.FederationHealthView parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static peers_touch.model.federation.v1.FederationHealth.FederationHealthView parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static peers_touch.model.federation.v1.FederationHealth.FederationHealthView parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static peers_touch.model.federation.v1.FederationHealth.FederationHealthView parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static peers_touch.model.federation.v1.FederationHealth.FederationHealthView parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static peers_touch.model.federation.v1.FederationHealth.FederationHealthView parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static peers_touch.model.federation.v1.FederationHealth.FederationHealthView parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(peers_touch.model.federation.v1.FederationHealth.FederationHealthView prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code peers_touch.model.federation.v1.FederationHealthView}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          peers_touch.model.federation.v1.FederationHealth.FederationHealthView, Builder> implements
        // @@protoc_insertion_point(builder_implements:peers_touch.model.federation.v1.FederationHealthView)
        peers_touch.model.federation.v1.FederationHealth.FederationHealthViewOrBuilder {
      // Construct using peers_touch.model.federation.v1.FederationHealth.FederationHealthView.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * True iff the local kad-DHT routing table has at least
       * `min_dht_peers` peers AND the bootstrap subserver has begun
       * executing. False during the first few seconds of a cold start.
       * </pre>
       *
       * <code>bool ready = 1;</code>
       * @return The ready.
       */
      @java.lang.Override
      public boolean getReady() {
        return instance.getReady();
      }
      /**
       * <pre>
       * True iff the local kad-DHT routing table has at least
       * `min_dht_peers` peers AND the bootstrap subserver has begun
       * executing. False during the first few seconds of a cold start.
       * </pre>
       *
       * <code>bool ready = 1;</code>
       * @param value The ready to set.
       * @return This builder for chaining.
       */
      public Builder setReady(boolean value) {
        copyOnWrite();
        instance.setReady(value);
        return this;
      }
      /**
       * <pre>
       * True iff the local kad-DHT routing table has at least
       * `min_dht_peers` peers AND the bootstrap subserver has begun
       * executing. False during the first few seconds of a cold start.
       * </pre>
       *
       * <code>bool ready = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearReady() {
        copyOnWrite();
        instance.clearReady();
        return this;
      }

      /**
       * <pre>
       * Current routing table size — peers reachable for GetValue /
       * PutValue. Below `min_dht_peers` the resolver gates remote
       * resolves with HTTP 503 + ErrFederationNotReady.
       * </pre>
       *
       * <code>int32 peers_in_routing_table = 2 [json_name = "peers_in_routing_table"];</code>
       * @return The peersInRoutingTable.
       */
      @java.lang.Override
      public int getPeersInRoutingTable() {
        return instance.getPeersInRoutingTable();
      }
      /**
       * <pre>
       * Current routing table size — peers reachable for GetValue /
       * PutValue. Below `min_dht_peers` the resolver gates remote
       * resolves with HTTP 503 + ErrFederationNotReady.
       * </pre>
       *
       * <code>int32 peers_in_routing_table = 2 [json_name = "peers_in_routing_table"];</code>
       * @param value The peersInRoutingTable to set.
       * @return This builder for chaining.
       */
      public Builder setPeersInRoutingTable(int value) {
        copyOnWrite();
        instance.setPeersInRoutingTable(value);
        return this;
      }
      /**
       * <pre>
       * Current routing table size — peers reachable for GetValue /
       * PutValue. Below `min_dht_peers` the resolver gates remote
       * resolves with HTTP 503 + ErrFederationNotReady.
       * </pre>
       *
       * <code>int32 peers_in_routing_table = 2 [json_name = "peers_in_routing_table"];</code>
       * @return This builder for chaining.
       */
      public Builder clearPeersInRoutingTable() {
        copyOnWrite();
        instance.clearPeersInRoutingTable();
        return this;
      }

      /**
       * <pre>
       * libp2p host total connected peers. Broader than the routing
       * table — includes direct dials, relay-circuit connections, and
       * peers we are connected to but have not yet exchanged DHT
       * records with.
       * </pre>
       *
       * <code>int32 connected_peers = 3 [json_name = "connected_peers"];</code>
       * @return The connectedPeers.
       */
      @java.lang.Override
      public int getConnectedPeers() {
        return instance.getConnectedPeers();
      }
      /**
       * <pre>
       * libp2p host total connected peers. Broader than the routing
       * table — includes direct dials, relay-circuit connections, and
       * peers we are connected to but have not yet exchanged DHT
       * records with.
       * </pre>
       *
       * <code>int32 connected_peers = 3 [json_name = "connected_peers"];</code>
       * @param value The connectedPeers to set.
       * @return This builder for chaining.
       */
      public Builder setConnectedPeers(int value) {
        copyOnWrite();
        instance.setConnectedPeers(value);
        return this;
      }
      /**
       * <pre>
       * libp2p host total connected peers. Broader than the routing
       * table — includes direct dials, relay-circuit connections, and
       * peers we are connected to but have not yet exchanged DHT
       * records with.
       * </pre>
       *
       * <code>int32 connected_peers = 3 [json_name = "connected_peers"];</code>
       * @return This builder for chaining.
       */
      public Builder clearConnectedPeers() {
        copyOnWrite();
        instance.clearConnectedPeers();
        return this;
      }

      /**
       * <pre>
       * Configured federation seeds AFTER the self-filter (a station
       * never lists itself as a seed). Static after boot.
       * </pre>
       *
       * <code>int32 seeds_configured = 4 [json_name = "seeds_configured"];</code>
       * @return The seedsConfigured.
       */
      @java.lang.Override
      public int getSeedsConfigured() {
        return instance.getSeedsConfigured();
      }
      /**
       * <pre>
       * Configured federation seeds AFTER the self-filter (a station
       * never lists itself as a seed). Static after boot.
       * </pre>
       *
       * <code>int32 seeds_configured = 4 [json_name = "seeds_configured"];</code>
       * @param value The seedsConfigured to set.
       * @return This builder for chaining.
       */
      public Builder setSeedsConfigured(int value) {
        copyOnWrite();
        instance.setSeedsConfigured(value);
        return this;
      }
      /**
       * <pre>
       * Configured federation seeds AFTER the self-filter (a station
       * never lists itself as a seed). Static after boot.
       * </pre>
       *
       * <code>int32 seeds_configured = 4 [json_name = "seeds_configured"];</code>
       * @return This builder for chaining.
       */
      public Builder clearSeedsConfigured() {
        copyOnWrite();
        instance.clearSeedsConfigured();
        return this;
      }

      /**
       * <pre>
       * Seeds with libp2p Connectedness == Connected RIGHT NOW. May be
       * less than `seeds_configured` even when ready=true if the DHT
       * has learned about other peers via the seed and the seed
       * connection then dropped.
       * </pre>
       *
       * <code>int32 seeds_connected = 5 [json_name = "seeds_connected"];</code>
       * @return The seedsConnected.
       */
      @java.lang.Override
      public int getSeedsConnected() {
        return instance.getSeedsConnected();
      }
      /**
       * <pre>
       * Seeds with libp2p Connectedness == Connected RIGHT NOW. May be
       * less than `seeds_configured` even when ready=true if the DHT
       * has learned about other peers via the seed and the seed
       * connection then dropped.
       * </pre>
       *
       * <code>int32 seeds_connected = 5 [json_name = "seeds_connected"];</code>
       * @param value The seedsConnected to set.
       * @return This builder for chaining.
       */
      public Builder setSeedsConnected(int value) {
        copyOnWrite();
        instance.setSeedsConnected(value);
        return this;
      }
      /**
       * <pre>
       * Seeds with libp2p Connectedness == Connected RIGHT NOW. May be
       * less than `seeds_configured` even when ready=true if the DHT
       * has learned about other peers via the seed and the seed
       * connection then dropped.
       * </pre>
       *
       * <code>int32 seeds_connected = 5 [json_name = "seeds_connected"];</code>
       * @return This builder for chaining.
       */
      public Builder clearSeedsConnected() {
        copyOnWrite();
        instance.clearSeedsConnected();
        return this;
      }

      /**
       * <pre>
       * Effective threshold (post policy clamp). Always &gt;= 1 in
       * production; a negative value here means an operator has
       * explicitly disabled the gate (ready always true once Start runs).
       * </pre>
       *
       * <code>int32 min_dht_peers = 6 [json_name = "min_dht_peers"];</code>
       * @return The minDhtPeers.
       */
      @java.lang.Override
      public int getMinDhtPeers() {
        return instance.getMinDhtPeers();
      }
      /**
       * <pre>
       * Effective threshold (post policy clamp). Always &gt;= 1 in
       * production; a negative value here means an operator has
       * explicitly disabled the gate (ready always true once Start runs).
       * </pre>
       *
       * <code>int32 min_dht_peers = 6 [json_name = "min_dht_peers"];</code>
       * @param value The minDhtPeers to set.
       * @return This builder for chaining.
       */
      public Builder setMinDhtPeers(int value) {
        copyOnWrite();
        instance.setMinDhtPeers(value);
        return this;
      }
      /**
       * <pre>
       * Effective threshold (post policy clamp). Always &gt;= 1 in
       * production; a negative value here means an operator has
       * explicitly disabled the gate (ready always true once Start runs).
       * </pre>
       *
       * <code>int32 min_dht_peers = 6 [json_name = "min_dht_peers"];</code>
       * @return This builder for chaining.
       */
      public Builder clearMinDhtPeers() {
        copyOnWrite();
        instance.clearMinDhtPeers();
        return this;
      }

      /**
       * <pre>
       * Stable identity of this station. Echoes the local libp2p PeerID
       * and HTTP origin a federation locator record carries, so an
       * external monitor can correlate health snapshots with locator
       * records they may also be observing.
       * </pre>
       *
       * <code>string station_peer_id = 7 [json_name = "station_peer_id"];</code>
       * @return The stationPeerId.
       */
      @java.lang.Override
      public java.lang.String getStationPeerId() {
        return instance.getStationPeerId();
      }
      /**
       * <pre>
       * Stable identity of this station. Echoes the local libp2p PeerID
       * and HTTP origin a federation locator record carries, so an
       * external monitor can correlate health snapshots with locator
       * records they may also be observing.
       * </pre>
       *
       * <code>string station_peer_id = 7 [json_name = "station_peer_id"];</code>
       * @return The bytes for stationPeerId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getStationPeerIdBytes() {
        return instance.getStationPeerIdBytes();
      }
      /**
       * <pre>
       * Stable identity of this station. Echoes the local libp2p PeerID
       * and HTTP origin a federation locator record carries, so an
       * external monitor can correlate health snapshots with locator
       * records they may also be observing.
       * </pre>
       *
       * <code>string station_peer_id = 7 [json_name = "station_peer_id"];</code>
       * @param value The stationPeerId to set.
       * @return This builder for chaining.
       */
      public Builder setStationPeerId(
          java.lang.String value) {
        copyOnWrite();
        instance.setStationPeerId(value);
        return this;
      }
      /**
       * <pre>
       * Stable identity of this station. Echoes the local libp2p PeerID
       * and HTTP origin a federation locator record carries, so an
       * external monitor can correlate health snapshots with locator
       * records they may also be observing.
       * </pre>
       *
       * <code>string station_peer_id = 7 [json_name = "station_peer_id"];</code>
       * @return This builder for chaining.
       */
      public Builder clearStationPeerId() {
        copyOnWrite();
        instance.clearStationPeerId();
        return this;
      }
      /**
       * <pre>
       * Stable identity of this station. Echoes the local libp2p PeerID
       * and HTTP origin a federation locator record carries, so an
       * external monitor can correlate health snapshots with locator
       * records they may also be observing.
       * </pre>
       *
       * <code>string station_peer_id = 7 [json_name = "station_peer_id"];</code>
       * @param value The bytes for stationPeerId to set.
       * @return This builder for chaining.
       */
      public Builder setStationPeerIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setStationPeerIdBytes(value);
        return this;
      }

      /**
       * <code>string station_domain = 8 [json_name = "station_domain"];</code>
       * @return The stationDomain.
       */
      @java.lang.Override
      public java.lang.String getStationDomain() {
        return instance.getStationDomain();
      }
      /**
       * <code>string station_domain = 8 [json_name = "station_domain"];</code>
       * @return The bytes for stationDomain.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getStationDomainBytes() {
        return instance.getStationDomainBytes();
      }
      /**
       * <code>string station_domain = 8 [json_name = "station_domain"];</code>
       * @param value The stationDomain to set.
       * @return This builder for chaining.
       */
      public Builder setStationDomain(
          java.lang.String value) {
        copyOnWrite();
        instance.setStationDomain(value);
        return this;
      }
      /**
       * <code>string station_domain = 8 [json_name = "station_domain"];</code>
       * @return This builder for chaining.
       */
      public Builder clearStationDomain() {
        copyOnWrite();
        instance.clearStationDomain();
        return this;
      }
      /**
       * <code>string station_domain = 8 [json_name = "station_domain"];</code>
       * @param value The bytes for stationDomain to set.
       * @return This builder for chaining.
       */
      public Builder setStationDomainBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setStationDomainBytes(value);
        return this;
      }

      /**
       * <pre>
       * RFC-3339 wall-clock time bootstrap.Start() began. Empty when
       * the bootstrap subserver has not yet started — clients should
       * treat that as not-ready. Paired with `uptime_seconds` for
       * human-readable diagnostics.
       * </pre>
       *
       * <code>string boot_started_at = 9 [json_name = "boot_started_at"];</code>
       * @return The bootStartedAt.
       */
      @java.lang.Override
      public java.lang.String getBootStartedAt() {
        return instance.getBootStartedAt();
      }
      /**
       * <pre>
       * RFC-3339 wall-clock time bootstrap.Start() began. Empty when
       * the bootstrap subserver has not yet started — clients should
       * treat that as not-ready. Paired with `uptime_seconds` for
       * human-readable diagnostics.
       * </pre>
       *
       * <code>string boot_started_at = 9 [json_name = "boot_started_at"];</code>
       * @return The bytes for bootStartedAt.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getBootStartedAtBytes() {
        return instance.getBootStartedAtBytes();
      }
      /**
       * <pre>
       * RFC-3339 wall-clock time bootstrap.Start() began. Empty when
       * the bootstrap subserver has not yet started — clients should
       * treat that as not-ready. Paired with `uptime_seconds` for
       * human-readable diagnostics.
       * </pre>
       *
       * <code>string boot_started_at = 9 [json_name = "boot_started_at"];</code>
       * @param value The bootStartedAt to set.
       * @return This builder for chaining.
       */
      public Builder setBootStartedAt(
          java.lang.String value) {
        copyOnWrite();
        instance.setBootStartedAt(value);
        return this;
      }
      /**
       * <pre>
       * RFC-3339 wall-clock time bootstrap.Start() began. Empty when
       * the bootstrap subserver has not yet started — clients should
       * treat that as not-ready. Paired with `uptime_seconds` for
       * human-readable diagnostics.
       * </pre>
       *
       * <code>string boot_started_at = 9 [json_name = "boot_started_at"];</code>
       * @return This builder for chaining.
       */
      public Builder clearBootStartedAt() {
        copyOnWrite();
        instance.clearBootStartedAt();
        return this;
      }
      /**
       * <pre>
       * RFC-3339 wall-clock time bootstrap.Start() began. Empty when
       * the bootstrap subserver has not yet started — clients should
       * treat that as not-ready. Paired with `uptime_seconds` for
       * human-readable diagnostics.
       * </pre>
       *
       * <code>string boot_started_at = 9 [json_name = "boot_started_at"];</code>
       * @param value The bytes for bootStartedAt to set.
       * @return This builder for chaining.
       */
      public Builder setBootStartedAtBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setBootStartedAtBytes(value);
        return this;
      }

      /**
       * <code>int64 uptime_seconds = 10 [json_name = "uptime_seconds"];</code>
       * @return The uptimeSeconds.
       */
      @java.lang.Override
      public long getUptimeSeconds() {
        return instance.getUptimeSeconds();
      }
      /**
       * <code>int64 uptime_seconds = 10 [json_name = "uptime_seconds"];</code>
       * @param value The uptimeSeconds to set.
       * @return This builder for chaining.
       */
      public Builder setUptimeSeconds(long value) {
        copyOnWrite();
        instance.setUptimeSeconds(value);
        return this;
      }
      /**
       * <code>int64 uptime_seconds = 10 [json_name = "uptime_seconds"];</code>
       * @return This builder for chaining.
       */
      public Builder clearUptimeSeconds() {
        copyOnWrite();
        instance.clearUptimeSeconds();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:peers_touch.model.federation.v1.FederationHealthView)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new peers_touch.model.federation.v1.FederationHealth.FederationHealthView();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "ready_",
              "peersInRoutingTable_",
              "connectedPeers_",
              "seedsConfigured_",
              "seedsConnected_",
              "minDhtPeers_",
              "stationPeerId_",
              "stationDomain_",
              "bootStartedAt_",
              "uptimeSeconds_",
            };
            java.lang.String info =
                "\u0000\n\u0000\u0000\u0001\n\n\u0000\u0000\u0000\u0001\u0007\u0002\u0004\u0003\u0004" +
                "\u0004\u0004\u0005\u0004\u0006\u0004\u0007\u0208\b\u0208\t\u0208\n\u0002";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<peers_touch.model.federation.v1.FederationHealth.FederationHealthView> parser = PARSER;
          if (parser == null) {
            synchronized (peers_touch.model.federation.v1.FederationHealth.FederationHealthView.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<peers_touch.model.federation.v1.FederationHealth.FederationHealthView>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:peers_touch.model.federation.v1.FederationHealthView)
    private static final peers_touch.model.federation.v1.FederationHealth.FederationHealthView DEFAULT_INSTANCE;
    static {
      FederationHealthView defaultInstance = new FederationHealthView();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        FederationHealthView.class, defaultInstance);
    }

    public static peers_touch.model.federation.v1.FederationHealth.FederationHealthView getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<FederationHealthView> PARSER;

    public static com.google.protobuf.Parser<FederationHealthView> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
