pub mod build_identity;
pub mod draft;
pub mod health;
pub mod ledger;
#[cfg(feature = "acceptance-harness")]
pub mod native_events;
pub mod oauth;
pub mod platform_bridge;
pub mod secure_storage;
pub mod station;

use tauri::ipc::Invoke;

#[cfg(not(feature = "acceptance-harness"))]
pub fn handlers<R: tauri::Runtime>() -> impl Fn(Invoke<R>) -> bool + Send + Sync + 'static {
    tauri::generate_handler![
        // Health
        health::mobile_health,
        // Messaging
        crate::messaging::commands::messaging_activate,
        crate::messaging::commands::messaging_attachment_stage_begin,
        crate::messaging::commands::messaging_attachment_stage_complete,
        crate::messaging::commands::messaging_attachment_stage_discard,
        crate::messaging::commands::messaging_attachment_stage_write,
        crate::messaging::commands::messaging_call_signal_open,
        crate::messaging::commands::messaging_call_signal_seal,
        crate::messaging::commands::messaging_cancel_attachment,
        crate::messaging::commands::messaging_command_status,
        crate::messaging::commands::messaging_conversation_summary,
        crate::messaging::commands::messaging_create_direct,
        crate::messaging::commands::messaging_create_group,
        crate::messaging::commands::messaging_deactivate,
        crate::messaging::commands::messaging_dissolve_conversation,
        crate::messaging::commands::messaging_forward_message,
        crate::messaging::commands::messaging_list_conversations,
        crate::messaging::commands::messaging_list_messages,
        crate::messaging::commands::messaging_list_thread_messages,
        crate::messaging::commands::messaging_membership_transition,
        crate::messaging::commands::messaging_open_attachment,
        crate::messaging::commands::messaging_reconcile,
        crate::messaging::commands::messaging_resume,
        crate::messaging::commands::messaging_search_messages,
        crate::messaging::commands::messaging_send_message,
        crate::messaging::commands::messaging_status,
        crate::messaging::commands::messaging_submit_leave_intent,
        crate::messaging::commands::messaging_suspend,
        crate::messaging::commands::messaging_submit_edit,
        crate::messaging::commands::messaging_submit_metadata_interaction,
        crate::messaging::commands::messaging_submit_read_cursor,
        crate::messaging::commands::messaging_submit_typing,
        crate::messaging::commands::messaging_transfer_ownership,
        crate::messaging::commands::messaging_update_conversation,
        crate::messaging::commands::messaging_update_member_authority,
        crate::messaging::commands::messaging_wake,
        crate::messaging::commands::social_friend_request_accept,
        crate::messaging::commands::social_friend_request_reconcile,
        crate::messaging::commands::social_friend_request_reject,
        crate::messaging::commands::social_friend_request_send,
        crate::messaging::commands::social_relationship_block,
        crate::messaging::commands::social_relationship_reconcile,
        crate::messaging::commands::social_relationship_unblock,
        // Private Social
        crate::social::social_private_activate,
        crate::social::social_private_comment_submit,
        crate::social::social_private_comments,
        crate::social::social_private_open_media,
        crate::social::social_private_prepare_text,
        crate::social::social_private_publish,
        crate::social::social_private_read,
        crate::social::social_private_read_text,
        crate::social::social_private_recover,
        crate::social::social_private_recover_text,
        crate::social::social_private_store_recovery_phrase,
        crate::social::social_private_reconcile,
        crate::social::social_private_snapshot,
        crate::social::social_private_status,
        crate::social::social_private_submit_text,
        crate::social::social_private_teardown,
        // OAuth
        oauth::access_cancel,
        oauth::access_decision,
        oauth::access_start,
        oauth::access_submit,
        oauth::oauth_cancel,
        oauth::oauth_logout_purge,
        oauth::oauth_projection,
        oauth::oauth_restore,
        oauth::oauth_retry_browser,
        oauth::oauth_session_projection,
        oauth::oauth_session_refresh,
        oauth::oauth_start,
        oauth::oauth_status,
        // Authenticated Station transport
        crate::runtime::station_transport::station_realtime_start,
        crate::runtime::station_transport::station_realtime_stop,
        crate::runtime::station_transport::station_transport_cancel,
        crate::runtime::station_transport::station_transport_execute,
        // Secure storage
        secure_storage::secure_storage_get,
        secure_storage::secure_storage_remove,
        secure_storage::secure_storage_set,
        // Station
        station::station_identity_verify,
        station::station_probe,
        // Reliability
        ledger::reliability_activate,
        ledger::reliability_status,
        ledger::reliability_rebind_generation,
        ledger::reliability_suspend,
        ledger::reliability_prepare_scope_exit,
        ledger::reliability_open_admission,
        ledger::reliability_close_scope,
        ledger::reliability_apply_legacy_disposition,
        ledger::reliability_reset_all,
        ledger::reliability_list_commands,
        ledger::reliability_list_projection_checkpoints,
        ledger::reliability_cancel_command,
        ledger::reliability_acknowledge_projection,
        ledger::reliability_acknowledge_terminal_failure,
        ledger::reliability_discard_unresolved,
        // Drafts
        draft::draft_save,
        draft::draft_load,
        draft::draft_remove,
        draft::draft_list,
        // W7: Platform bridge — lifecycle, permissions, network
        platform_bridge::lifecycle_generation,
        platform_bridge::lifecycle_advance_generation,
        platform_bridge::lifecycle_process_event,
        platform_bridge::lifecycle_ingest_native_signal,
        platform_bridge::lifecycle_reconcile,
        platform_bridge::permission_check,
        platform_bridge::permission_request,
        platform_bridge::permission_check_all,
        platform_bridge::network_state,
        platform_bridge::network_start_observation,
        platform_bridge::network_ingest_native_signal,
        platform_bridge::network_is_connected,
        platform_bridge::push_activate,
        platform_bridge::push_drain,
        platform_bridge::push_deactivate,
        platform_bridge::scheduled_reconcile_drain,
        platform_bridge::media_pick,
        platform_bridge::moment_media_upload,
        platform_bridge::moment_media_discard,
    ]
}

#[cfg(feature = "acceptance-harness")]
pub fn handlers<R: tauri::Runtime>() -> impl Fn(Invoke<R>) -> bool + Send + Sync + 'static {
    tauri::generate_handler![
        // Build identity (acceptance only)
        build_identity::mobile_build_identity,
        // Health
        health::mobile_health,
        // Native events
        native_events::mobile_native_event_emit,
        // Messaging
        crate::messaging::commands::messaging_activate,
        crate::messaging::commands::messaging_attachment_stage_begin,
        crate::messaging::commands::messaging_attachment_stage_complete,
        crate::messaging::commands::messaging_attachment_stage_discard,
        crate::messaging::commands::messaging_attachment_stage_write,
        crate::messaging::commands::messaging_call_signal_open,
        crate::messaging::commands::messaging_call_signal_seal,
        crate::messaging::commands::messaging_cancel_attachment,
        crate::messaging::commands::messaging_command_status,
        crate::messaging::commands::messaging_conversation_summary,
        crate::messaging::commands::messaging_create_direct,
        crate::messaging::commands::messaging_create_group,
        crate::messaging::commands::messaging_deactivate,
        crate::messaging::commands::messaging_dissolve_conversation,
        crate::messaging::commands::messaging_forward_message,
        crate::messaging::commands::messaging_list_conversations,
        crate::messaging::commands::messaging_list_messages,
        crate::messaging::commands::messaging_list_thread_messages,
        crate::messaging::commands::messaging_membership_transition,
        crate::messaging::commands::messaging_open_attachment,
        crate::messaging::commands::messaging_reconcile,
        crate::messaging::commands::messaging_resume,
        crate::messaging::commands::messaging_search_messages,
        crate::messaging::commands::messaging_send_message,
        crate::messaging::commands::messaging_status,
        crate::messaging::commands::messaging_submit_leave_intent,
        crate::messaging::commands::messaging_suspend,
        crate::messaging::commands::messaging_submit_edit,
        crate::messaging::commands::messaging_submit_metadata_interaction,
        crate::messaging::commands::messaging_submit_read_cursor,
        crate::messaging::commands::messaging_submit_typing,
        crate::messaging::commands::messaging_transfer_ownership,
        crate::messaging::commands::messaging_update_conversation,
        crate::messaging::commands::messaging_update_member_authority,
        crate::messaging::commands::messaging_wake,
        crate::messaging::commands::social_friend_request_accept,
        crate::messaging::commands::social_friend_request_reconcile,
        crate::messaging::commands::social_friend_request_reject,
        crate::messaging::commands::social_friend_request_send,
        crate::messaging::commands::social_relationship_block,
        crate::messaging::commands::social_relationship_reconcile,
        crate::messaging::commands::social_relationship_unblock,
        // Private Social
        crate::social::social_private_activate,
        crate::social::social_private_comment_submit,
        crate::social::social_private_comments,
        crate::social::social_private_open_media,
        crate::social::social_private_prepare_text,
        crate::social::social_private_publish,
        crate::social::social_private_read,
        crate::social::social_private_read_text,
        crate::social::social_private_recover,
        crate::social::social_private_recover_text,
        crate::social::social_private_store_recovery_phrase,
        crate::social::social_private_reconcile,
        crate::social::social_private_snapshot,
        crate::social::social_private_status,
        crate::social::social_private_submit_text,
        crate::social::social_private_teardown,
        // OAuth (acceptance)
        oauth::access_cancel,
        oauth::access_decision,
        oauth::access_start,
        oauth::access_submit,
        oauth::oauth_acceptance_callback_replay_handle,
        oauth::oauth_acceptance_configure_secure_storage_fault,
        oauth::oauth_acceptance_negative_callback,
        oauth::oauth_cancel,
        oauth::oauth_logout_purge,
        oauth::oauth_projection,
        oauth::oauth_restore,
        oauth::oauth_retry_browser,
        oauth::oauth_session_projection,
        oauth::oauth_session_refresh,
        oauth::oauth_start,
        oauth::oauth_status,
        // Authenticated Station transport
        crate::runtime::station_transport::station_realtime_start,
        crate::runtime::station_transport::station_realtime_stop,
        crate::runtime::station_transport::station_transport_cancel,
        crate::runtime::station_transport::station_transport_execute,
        // Secure storage
        secure_storage::secure_storage_get,
        secure_storage::secure_storage_remove,
        secure_storage::secure_storage_set,
        // Station
        station::station_identity_verify,
        station::station_probe,
        // Reliability
        ledger::reliability_activate,
        ledger::reliability_status,
        ledger::reliability_rebind_generation,
        ledger::reliability_suspend,
        ledger::reliability_prepare_scope_exit,
        ledger::reliability_open_admission,
        ledger::reliability_close_scope,
        ledger::reliability_apply_legacy_disposition,
        ledger::reliability_reset_all,
        ledger::reliability_list_commands,
        ledger::reliability_list_projection_checkpoints,
        ledger::reliability_cancel_command,
        ledger::reliability_acknowledge_projection,
        ledger::reliability_acknowledge_terminal_failure,
        ledger::reliability_discard_unresolved,
        ledger::reliability_acceptance_configure_fault,
        // Drafts
        draft::draft_save,
        draft::draft_load,
        draft::draft_remove,
        draft::draft_list,
        // W7: Platform bridge — lifecycle, permissions, network
        platform_bridge::lifecycle_generation,
        platform_bridge::lifecycle_advance_generation,
        platform_bridge::lifecycle_process_event,
        platform_bridge::lifecycle_ingest_native_signal,
        platform_bridge::lifecycle_reconcile,
        platform_bridge::permission_check,
        platform_bridge::permission_request,
        platform_bridge::permission_check_all,
        platform_bridge::network_state,
        platform_bridge::network_start_observation,
        platform_bridge::network_ingest_native_signal,
        platform_bridge::network_is_connected,
        platform_bridge::push_activate,
        platform_bridge::push_drain,
        platform_bridge::push_deactivate,
        platform_bridge::scheduled_reconcile_drain,
        platform_bridge::media_pick,
        platform_bridge::moment_media_upload,
        platform_bridge::moment_media_discard,
    ]
}
