// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: domain/ai_box/chat.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 角色枚举映射
type ChatRole int32

const (
	ChatRole_CHAT_ROLE_UNSPECIFIED ChatRole = 0
	ChatRole_CHAT_ROLE_SYSTEM      ChatRole = 1
	ChatRole_CHAT_ROLE_USER        ChatRole = 2
	ChatRole_CHAT_ROLE_ASSISTANT   ChatRole = 3
	ChatRole_CHAT_ROLE_TOOL        ChatRole = 4
)

// Enum value maps for ChatRole.
var (
	ChatRole_name = map[int32]string{
		0: "CHAT_ROLE_UNSPECIFIED",
		1: "CHAT_ROLE_SYSTEM",
		2: "CHAT_ROLE_USER",
		3: "CHAT_ROLE_ASSISTANT",
		4: "CHAT_ROLE_TOOL",
	}
	ChatRole_value = map[string]int32{
		"CHAT_ROLE_UNSPECIFIED": 0,
		"CHAT_ROLE_SYSTEM":      1,
		"CHAT_ROLE_USER":        2,
		"CHAT_ROLE_ASSISTANT":   3,
		"CHAT_ROLE_TOOL":        4,
	}
)

func (x ChatRole) Enum() *ChatRole {
	p := new(ChatRole)
	*p = x
	return p
}

func (x ChatRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatRole) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_ai_box_chat_proto_enumTypes[0].Descriptor()
}

func (ChatRole) Type() protoreflect.EnumType {
	return &file_domain_ai_box_chat_proto_enumTypes[0]
}

func (x ChatRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatRole.Descriptor instead.
func (ChatRole) EnumDescriptor() ([]byte, []int) {
	return file_domain_ai_box_chat_proto_rawDescGZIP(), []int{0}
}

// 聊天会话
type ChatSession struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Avatar          string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	BackgroundColor string                 `protobuf:"bytes,5,opt,name=background_color,json=backgroundColor,proto3" json:"background_color,omitempty"`
	ProviderId      string                 `protobuf:"bytes,6,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	UserId          string                 `protobuf:"bytes,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ModelName       string                 `protobuf:"bytes,8,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Pinned          bool                   `protobuf:"varint,9,opt,name=pinned,proto3" json:"pinned,omitempty"`
	Group           string                 `protobuf:"bytes,10,opt,name=group,proto3" json:"group,omitempty"`
	CreatedAt       int64                  `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       int64                  `protobuf:"varint,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Meta            map[string]string      `protobuf:"bytes,13,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ConfigJson      string                 `protobuf:"bytes,14,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChatSession) Reset() {
	*x = ChatSession{}
	mi := &file_domain_ai_box_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatSession) ProtoMessage() {}

func (x *ChatSession) ProtoReflect() protoreflect.Message {
	mi := &file_domain_ai_box_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatSession.ProtoReflect.Descriptor instead.
func (*ChatSession) Descriptor() ([]byte, []int) {
	return file_domain_ai_box_chat_proto_rawDescGZIP(), []int{0}
}

func (x *ChatSession) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatSession) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ChatSession) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ChatSession) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *ChatSession) GetBackgroundColor() string {
	if x != nil {
		return x.BackgroundColor
	}
	return ""
}

func (x *ChatSession) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *ChatSession) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChatSession) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *ChatSession) GetPinned() bool {
	if x != nil {
		return x.Pinned
	}
	return false
}

func (x *ChatSession) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ChatSession) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ChatSession) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *ChatSession) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ChatSession) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

// 消息附件
type MessageAttachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Url           string                 `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	MetadataJson  string                 `protobuf:"bytes,7,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageAttachment) Reset() {
	*x = MessageAttachment{}
	mi := &file_domain_ai_box_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageAttachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageAttachment) ProtoMessage() {}

func (x *MessageAttachment) ProtoReflect() protoreflect.Message {
	mi := &file_domain_ai_box_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageAttachment.ProtoReflect.Descriptor instead.
func (*MessageAttachment) Descriptor() ([]byte, []int) {
	return file_domain_ai_box_chat_proto_rawDescGZIP(), []int{1}
}

func (x *MessageAttachment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MessageAttachment) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageAttachment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MessageAttachment) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *MessageAttachment) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MessageAttachment) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MessageAttachment) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *MessageAttachment) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// 聊天消息
type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TopicId       string                 `protobuf:"bytes,3,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	ModelName     string                 `protobuf:"bytes,4,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Role          ChatRole               `protobuf:"varint,5,opt,name=role,proto3,enum=peers_touch.model.ai_box.v1.ChatRole" json:"role,omitempty"` // e.g., "user", "assistant", "system"
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	ErrorJson     string                 `protobuf:"bytes,7,opt,name=error_json,json=errorJson,proto3" json:"error_json,omitempty"`
	Attachments   []*MessageAttachment   `protobuf:"bytes,8,rep,name=attachments,proto3" json:"attachments,omitempty"`
	ImagesJson    string                 `protobuf:"bytes,9,opt,name=images_json,json=imagesJson,proto3" json:"images_json,omitempty"`
	MetadataJson  string                 `protobuf:"bytes,10,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	PluginJson    string                 `protobuf:"bytes,11,opt,name=plugin_json,json=pluginJson,proto3" json:"plugin_json,omitempty"`
	ToolCallsJson string                 `protobuf:"bytes,12,opt,name=tool_calls_json,json=toolCallsJson,proto3" json:"tool_calls_json,omitempty"`
	ReasoningJson string                 `protobuf:"bytes,13,opt,name=reasoning_json,json=reasoningJson,proto3" json:"reasoning_json,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_domain_ai_box_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_domain_ai_box_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_domain_ai_box_chat_proto_rawDescGZIP(), []int{2}
}

func (x *ChatMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatMessage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatMessage) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

func (x *ChatMessage) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *ChatMessage) GetRole() ChatRole {
	if x != nil {
		return x.Role
	}
	return ChatRole_CHAT_ROLE_UNSPECIFIED
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetErrorJson() string {
	if x != nil {
		return x.ErrorJson
	}
	return ""
}

func (x *ChatMessage) GetAttachments() []*MessageAttachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *ChatMessage) GetImagesJson() string {
	if x != nil {
		return x.ImagesJson
	}
	return ""
}

func (x *ChatMessage) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *ChatMessage) GetPluginJson() string {
	if x != nil {
		return x.PluginJson
	}
	return ""
}

func (x *ChatMessage) GetToolCallsJson() string {
	if x != nil {
		return x.ToolCallsJson
	}
	return ""
}

func (x *ChatMessage) GetReasoningJson() string {
	if x != nil {
		return x.ReasoningJson
	}
	return ""
}

func (x *ChatMessage) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ChatMessage) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// 聊天主题
type ChatTopic struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SessionId      string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Title          string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	MessageCount   int32                  `protobuf:"varint,5,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	FirstMessageId string                 `protobuf:"bytes,6,opt,name=first_message_id,json=firstMessageId,proto3" json:"first_message_id,omitempty"`
	LastMessageId  string                 `protobuf:"bytes,7,opt,name=last_message_id,json=lastMessageId,proto3" json:"last_message_id,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      int64                  `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChatTopic) Reset() {
	*x = ChatTopic{}
	mi := &file_domain_ai_box_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatTopic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatTopic) ProtoMessage() {}

func (x *ChatTopic) ProtoReflect() protoreflect.Message {
	mi := &file_domain_ai_box_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatTopic.ProtoReflect.Descriptor instead.
func (*ChatTopic) Descriptor() ([]byte, []int) {
	return file_domain_ai_box_chat_proto_rawDescGZIP(), []int{3}
}

func (x *ChatTopic) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatTopic) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatTopic) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ChatTopic) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ChatTopic) GetMessageCount() int32 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *ChatTopic) GetFirstMessageId() string {
	if x != nil {
		return x.FirstMessageId
	}
	return ""
}

func (x *ChatTopic) GetLastMessageId() string {
	if x != nil {
		return x.LastMessageId
	}
	return ""
}

func (x *ChatTopic) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ChatTopic) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// 工具调用类
type ToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Function      *structpb.Struct       `protobuf:"bytes,3,opt,name=function,proto3" json:"function,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_domain_ai_box_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_domain_ai_box_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_domain_ai_box_chat_proto_rawDescGZIP(), []int{4}
}

func (x *ToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCall) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ToolCall) GetFunction() *structpb.Struct {
	if x != nil {
		return x.Function
	}
	return nil
}

// 聊天完成请求
type ChatCompletionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Model            string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Messages         []*ChatMessage         `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	Temperature      *float64               `protobuf:"fixed64,3,opt,name=temperature,proto3,oneof" json:"temperature,omitempty"`
	MaxTokens        *int32                 `protobuf:"varint,4,opt,name=max_tokens,json=maxTokens,proto3,oneof" json:"max_tokens,omitempty"`
	TopP             *float64               `protobuf:"fixed64,5,opt,name=top_p,json=topP,proto3,oneof" json:"top_p,omitempty"`
	N                *int32                 `protobuf:"varint,6,opt,name=n,proto3,oneof" json:"n,omitempty"`
	Stream           *bool                  `protobuf:"varint,7,opt,name=stream,proto3,oneof" json:"stream,omitempty"`
	Stop             []string               `protobuf:"bytes,8,rep,name=stop,proto3" json:"stop,omitempty"`
	PresencePenalty  *float64               `protobuf:"fixed64,9,opt,name=presence_penalty,json=presencePenalty,proto3,oneof" json:"presence_penalty,omitempty"`
	FrequencyPenalty *float64               `protobuf:"fixed64,10,opt,name=frequency_penalty,json=frequencyPenalty,proto3,oneof" json:"frequency_penalty,omitempty"`
	LogitBias        *structpb.Struct       `protobuf:"bytes,11,opt,name=logit_bias,json=logitBias,proto3" json:"logit_bias,omitempty"`
	User             *string                `protobuf:"bytes,12,opt,name=user,proto3,oneof" json:"user,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChatCompletionRequest) Reset() {
	*x = ChatCompletionRequest{}
	mi := &file_domain_ai_box_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCompletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionRequest) ProtoMessage() {}

func (x *ChatCompletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_ai_box_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionRequest.ProtoReflect.Descriptor instead.
func (*ChatCompletionRequest) Descriptor() ([]byte, []int) {
	return file_domain_ai_box_chat_proto_rawDescGZIP(), []int{5}
}

func (x *ChatCompletionRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatCompletionRequest) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ChatCompletionRequest) GetTemperature() float64 {
	if x != nil && x.Temperature != nil {
		return *x.Temperature
	}
	return 0
}

func (x *ChatCompletionRequest) GetMaxTokens() int32 {
	if x != nil && x.MaxTokens != nil {
		return *x.MaxTokens
	}
	return 0
}

func (x *ChatCompletionRequest) GetTopP() float64 {
	if x != nil && x.TopP != nil {
		return *x.TopP
	}
	return 0
}

func (x *ChatCompletionRequest) GetN() int32 {
	if x != nil && x.N != nil {
		return *x.N
	}
	return 0
}

func (x *ChatCompletionRequest) GetStream() bool {
	if x != nil && x.Stream != nil {
		return *x.Stream
	}
	return false
}

func (x *ChatCompletionRequest) GetStop() []string {
	if x != nil {
		return x.Stop
	}
	return nil
}

func (x *ChatCompletionRequest) GetPresencePenalty() float64 {
	if x != nil && x.PresencePenalty != nil {
		return *x.PresencePenalty
	}
	return 0
}

func (x *ChatCompletionRequest) GetFrequencyPenalty() float64 {
	if x != nil && x.FrequencyPenalty != nil {
		return *x.FrequencyPenalty
	}
	return 0
}

func (x *ChatCompletionRequest) GetLogitBias() *structpb.Struct {
	if x != nil {
		return x.LogitBias
	}
	return nil
}

func (x *ChatCompletionRequest) GetUser() string {
	if x != nil && x.User != nil {
		return *x.User
	}
	return ""
}

// 聊天选择
type ChatChoice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Message       *ChatMessage           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	FinishReason  *string                `protobuf:"bytes,3,opt,name=finish_reason,json=finishReason,proto3,oneof" json:"finish_reason,omitempty"`
	Logprobs      *float64               `protobuf:"fixed64,4,opt,name=logprobs,proto3,oneof" json:"logprobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatChoice) Reset() {
	*x = ChatChoice{}
	mi := &file_domain_ai_box_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatChoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatChoice) ProtoMessage() {}

func (x *ChatChoice) ProtoReflect() protoreflect.Message {
	mi := &file_domain_ai_box_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatChoice.ProtoReflect.Descriptor instead.
func (*ChatChoice) Descriptor() ([]byte, []int) {
	return file_domain_ai_box_chat_proto_rawDescGZIP(), []int{6}
}

func (x *ChatChoice) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ChatChoice) GetMessage() *ChatMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ChatChoice) GetFinishReason() string {
	if x != nil && x.FinishReason != nil {
		return *x.FinishReason
	}
	return ""
}

func (x *ChatChoice) GetLogprobs() float64 {
	if x != nil && x.Logprobs != nil {
		return *x.Logprobs
	}
	return 0
}

// 使用统计
type Usage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PromptTokens     int32                  `protobuf:"varint,1,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int32                  `protobuf:"varint,2,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	TotalTokens      int32                  `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_domain_ai_box_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_domain_ai_box_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_domain_ai_box_chat_proto_rawDescGZIP(), []int{7}
}

func (x *Usage) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *Usage) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *Usage) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

// 聊天完成响应
type ChatCompletionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Object        string                 `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	Created       int64                  `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Choices       []*ChatChoice          `protobuf:"bytes,5,rep,name=choices,proto3" json:"choices,omitempty"`
	Usage         *Usage                 `protobuf:"bytes,6,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatCompletionResponse) Reset() {
	*x = ChatCompletionResponse{}
	mi := &file_domain_ai_box_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCompletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionResponse) ProtoMessage() {}

func (x *ChatCompletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_ai_box_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionResponse.ProtoReflect.Descriptor instead.
func (*ChatCompletionResponse) Descriptor() ([]byte, []int) {
	return file_domain_ai_box_chat_proto_rawDescGZIP(), []int{8}
}

func (x *ChatCompletionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatCompletionResponse) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *ChatCompletionResponse) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *ChatCompletionResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatCompletionResponse) GetChoices() []*ChatChoice {
	if x != nil {
		return x.Choices
	}
	return nil
}

func (x *ChatCompletionResponse) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

var File_domain_ai_box_chat_proto protoreflect.FileDescriptor

const file_domain_ai_box_chat_proto_rawDesc = "" +
	"\n" +
	"\x18domain/ai_box/chat.proto\x12\x1bpeers_touch.model.ai_box.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xff\x03\n" +
	"\vChatSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12)\n" +
	"\x10background_color\x18\x05 \x01(\tR\x0fbackgroundColor\x12\x1f\n" +
	"\vprovider_id\x18\x06 \x01(\tR\n" +
	"providerId\x12\x17\n" +
	"\auser_id\x18\a \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"model_name\x18\b \x01(\tR\tmodelName\x12\x16\n" +
	"\x06pinned\x18\t \x01(\bR\x06pinned\x12\x14\n" +
	"\x05group\x18\n" +
	" \x01(\tR\x05group\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\x03R\tupdatedAt\x12F\n" +
	"\x04meta\x18\r \x03(\v22.peers_touch.model.ai_box.v1.ChatSession.MetaEntryR\x04meta\x12\x1f\n" +
	"\vconfig_json\x18\x0e \x01(\tR\n" +
	"configJson\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd4\x01\n" +
	"\x11MessageAttachment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\x12#\n" +
	"\rmetadata_json\x18\a \x01(\tR\fmetadataJson\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\"\xb0\x04\n" +
	"\vChatMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x19\n" +
	"\btopic_id\x18\x03 \x01(\tR\atopicId\x12\x1d\n" +
	"\n" +
	"model_name\x18\x04 \x01(\tR\tmodelName\x129\n" +
	"\x04role\x18\x05 \x01(\x0e2%.peers_touch.model.ai_box.v1.ChatRoleR\x04role\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"error_json\x18\a \x01(\tR\terrorJson\x12P\n" +
	"\vattachments\x18\b \x03(\v2..peers_touch.model.ai_box.v1.MessageAttachmentR\vattachments\x12\x1f\n" +
	"\vimages_json\x18\t \x01(\tR\n" +
	"imagesJson\x12#\n" +
	"\rmetadata_json\x18\n" +
	" \x01(\tR\fmetadataJson\x12\x1f\n" +
	"\vplugin_json\x18\v \x01(\tR\n" +
	"pluginJson\x12&\n" +
	"\x0ftool_calls_json\x18\f \x01(\tR\rtoolCallsJson\x12%\n" +
	"\x0ereasoning_json\x18\r \x01(\tR\rreasoningJson\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\x03R\tupdatedAt\"\xa7\x02\n" +
	"\tChatTopic\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12#\n" +
	"\rmessage_count\x18\x05 \x01(\x05R\fmessageCount\x12(\n" +
	"\x10first_message_id\x18\x06 \x01(\tR\x0efirstMessageId\x12&\n" +
	"\x0flast_message_id\x18\a \x01(\tR\rlastMessageId\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\x03R\tupdatedAt\"c\n" +
	"\bToolCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x123\n" +
	"\bfunction\x18\x03 \x01(\v2\x17.google.protobuf.StructR\bfunction\"\xbd\x04\n" +
	"\x15ChatCompletionRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12D\n" +
	"\bmessages\x18\x02 \x03(\v2(.peers_touch.model.ai_box.v1.ChatMessageR\bmessages\x12%\n" +
	"\vtemperature\x18\x03 \x01(\x01H\x00R\vtemperature\x88\x01\x01\x12\"\n" +
	"\n" +
	"max_tokens\x18\x04 \x01(\x05H\x01R\tmaxTokens\x88\x01\x01\x12\x18\n" +
	"\x05top_p\x18\x05 \x01(\x01H\x02R\x04topP\x88\x01\x01\x12\x11\n" +
	"\x01n\x18\x06 \x01(\x05H\x03R\x01n\x88\x01\x01\x12\x1b\n" +
	"\x06stream\x18\a \x01(\bH\x04R\x06stream\x88\x01\x01\x12\x12\n" +
	"\x04stop\x18\b \x03(\tR\x04stop\x12.\n" +
	"\x10presence_penalty\x18\t \x01(\x01H\x05R\x0fpresencePenalty\x88\x01\x01\x120\n" +
	"\x11frequency_penalty\x18\n" +
	" \x01(\x01H\x06R\x10frequencyPenalty\x88\x01\x01\x126\n" +
	"\n" +
	"logit_bias\x18\v \x01(\v2\x17.google.protobuf.StructR\tlogitBias\x12\x17\n" +
	"\x04user\x18\f \x01(\tH\aR\x04user\x88\x01\x01B\x0e\n" +
	"\f_temperatureB\r\n" +
	"\v_max_tokensB\b\n" +
	"\x06_top_pB\x04\n" +
	"\x02_nB\t\n" +
	"\a_streamB\x13\n" +
	"\x11_presence_penaltyB\x14\n" +
	"\x12_frequency_penaltyB\a\n" +
	"\x05_user\"\xd0\x01\n" +
	"\n" +
	"ChatChoice\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12B\n" +
	"\amessage\x18\x02 \x01(\v2(.peers_touch.model.ai_box.v1.ChatMessageR\amessage\x12(\n" +
	"\rfinish_reason\x18\x03 \x01(\tH\x00R\ffinishReason\x88\x01\x01\x12\x1f\n" +
	"\blogprobs\x18\x04 \x01(\x01H\x01R\blogprobs\x88\x01\x01B\x10\n" +
	"\x0e_finish_reasonB\v\n" +
	"\t_logprobs\"|\n" +
	"\x05Usage\x12#\n" +
	"\rprompt_tokens\x18\x01 \x01(\x05R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x02 \x01(\x05R\x10completionTokens\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x05R\vtotalTokens\"\xed\x01\n" +
	"\x16ChatCompletionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06object\x18\x02 \x01(\tR\x06object\x12\x18\n" +
	"\acreated\x18\x03 \x01(\x03R\acreated\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12A\n" +
	"\achoices\x18\x05 \x03(\v2'.peers_touch.model.ai_box.v1.ChatChoiceR\achoices\x128\n" +
	"\x05usage\x18\x06 \x01(\v2\".peers_touch.model.ai_box.v1.UsageR\x05usage*|\n" +
	"\bChatRole\x12\x19\n" +
	"\x15CHAT_ROLE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10CHAT_ROLE_SYSTEM\x10\x01\x12\x12\n" +
	"\x0eCHAT_ROLE_USER\x10\x02\x12\x17\n" +
	"\x13CHAT_ROLE_ASSISTANT\x10\x03\x12\x12\n" +
	"\x0eCHAT_ROLE_TOOL\x10\x04BLZJgithub.com/peers-labs/peers-touch/station/app/subserver/ai_box/model;modelb\x06proto3"

var (
	file_domain_ai_box_chat_proto_rawDescOnce sync.Once
	file_domain_ai_box_chat_proto_rawDescData []byte
)

func file_domain_ai_box_chat_proto_rawDescGZIP() []byte {
	file_domain_ai_box_chat_proto_rawDescOnce.Do(func() {
		file_domain_ai_box_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_ai_box_chat_proto_rawDesc), len(file_domain_ai_box_chat_proto_rawDesc)))
	})
	return file_domain_ai_box_chat_proto_rawDescData
}

var file_domain_ai_box_chat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_domain_ai_box_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_domain_ai_box_chat_proto_goTypes = []any{
	(ChatRole)(0),                  // 0: peers_touch.model.ai_box.v1.ChatRole
	(*ChatSession)(nil),            // 1: peers_touch.model.ai_box.v1.ChatSession
	(*MessageAttachment)(nil),      // 2: peers_touch.model.ai_box.v1.MessageAttachment
	(*ChatMessage)(nil),            // 3: peers_touch.model.ai_box.v1.ChatMessage
	(*ChatTopic)(nil),              // 4: peers_touch.model.ai_box.v1.ChatTopic
	(*ToolCall)(nil),               // 5: peers_touch.model.ai_box.v1.ToolCall
	(*ChatCompletionRequest)(nil),  // 6: peers_touch.model.ai_box.v1.ChatCompletionRequest
	(*ChatChoice)(nil),             // 7: peers_touch.model.ai_box.v1.ChatChoice
	(*Usage)(nil),                  // 8: peers_touch.model.ai_box.v1.Usage
	(*ChatCompletionResponse)(nil), // 9: peers_touch.model.ai_box.v1.ChatCompletionResponse
	nil,                            // 10: peers_touch.model.ai_box.v1.ChatSession.MetaEntry
	(*structpb.Struct)(nil),        // 11: google.protobuf.Struct
}
var file_domain_ai_box_chat_proto_depIdxs = []int32{
	10, // 0: peers_touch.model.ai_box.v1.ChatSession.meta:type_name -> peers_touch.model.ai_box.v1.ChatSession.MetaEntry
	0,  // 1: peers_touch.model.ai_box.v1.ChatMessage.role:type_name -> peers_touch.model.ai_box.v1.ChatRole
	2,  // 2: peers_touch.model.ai_box.v1.ChatMessage.attachments:type_name -> peers_touch.model.ai_box.v1.MessageAttachment
	11, // 3: peers_touch.model.ai_box.v1.ToolCall.function:type_name -> google.protobuf.Struct
	3,  // 4: peers_touch.model.ai_box.v1.ChatCompletionRequest.messages:type_name -> peers_touch.model.ai_box.v1.ChatMessage
	11, // 5: peers_touch.model.ai_box.v1.ChatCompletionRequest.logit_bias:type_name -> google.protobuf.Struct
	3,  // 6: peers_touch.model.ai_box.v1.ChatChoice.message:type_name -> peers_touch.model.ai_box.v1.ChatMessage
	7,  // 7: peers_touch.model.ai_box.v1.ChatCompletionResponse.choices:type_name -> peers_touch.model.ai_box.v1.ChatChoice
	8,  // 8: peers_touch.model.ai_box.v1.ChatCompletionResponse.usage:type_name -> peers_touch.model.ai_box.v1.Usage
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_domain_ai_box_chat_proto_init() }
func file_domain_ai_box_chat_proto_init() {
	if File_domain_ai_box_chat_proto != nil {
		return
	}
	file_domain_ai_box_chat_proto_msgTypes[5].OneofWrappers = []any{}
	file_domain_ai_box_chat_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_ai_box_chat_proto_rawDesc), len(file_domain_ai_box_chat_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_ai_box_chat_proto_goTypes,
		DependencyIndexes: file_domain_ai_box_chat_proto_depIdxs,
		EnumInfos:         file_domain_ai_box_chat_proto_enumTypes,
		MessageInfos:      file_domain_ai_box_chat_proto_msgTypes,
	}.Build()
	File_domain_ai_box_chat_proto = out.File
	file_domain_ai_box_chat_proto_goTypes = nil
	file_domain_ai_box_chat_proto_depIdxs = nil
}
