#!/usr/bin/env bash
# profile.sh — Manage human-authorized local profile definitions
# Usage:
#   profile.sh authorize <name> [SLOT=N]
#   profile.sh init <name> [SLOT=N]
#   profile.sh list
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
# shellcheck disable=SC1091
source "$SCRIPT_DIR/redact-env.sh"
AUTHORIZATION_SCRIPT="$SCRIPT_DIR/environment-creation-authorization.py"
LOCAL_DEV_DIR="$PROJECT_ROOT/.local/dev"
PROFILES_DIR="$LOCAL_DEV_DIR/profiles"

mkdir -p "$PROFILES_DIR"

cmd="${1:-}"
name="${2:-}"

ENV_REPO_HINT_FILE="$LOCAL_DEV_DIR/.env-repo-path"

validate_profile_name() {
  local profile_name="$1"
  if [[ ! "$profile_name" =~ ^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$ ]]; then
    echo "[ERROR] Invalid profile name: $profile_name"
    exit 1
  fi
}

validate_slot() {
  local profile_slot="$1"
  if [[ ! "$profile_slot" =~ ^[0-9]+$ ]] || (( profile_slot > 99 )); then
    echo "[ERROR] SLOT must be an integer between 0 and 99."
    exit 1
  fi
}

list_profile_directories() {
  local env_root="$1"
  local directory
  for directory in "$env_root"/peers-touch/*/; do
    [[ -d "$directory" ]] || continue
    [[ "$(basename "$directory")" == "0-tpl" ]] && continue
    basename "$directory"
  done
}

resolve_env_repo() {
  if [[ -n "${PT_ENV_REPO:-}" && -d "$PT_ENV_REPO" ]]; then
    echo "$PT_ENV_REPO"
    return 0
  fi
  if [[ -f "$ENV_REPO_HINT_FILE" ]]; then
    local saved
    saved="$(cat "$ENV_REPO_HINT_FILE")"
    if [[ -d "$saved" ]]; then
      echo "$saved"
      return 0
    fi
  fi
  local sibling_env
  sibling_env="$(dirname "$PROJECT_ROOT")/env"
  if [[ -d "$sibling_env/peers-touch" ]]; then
    echo "$sibling_env"
    return 0
  fi
  return 1
}

require_reviewed_env_profile() {
  local profile_name="$1"
  local env_repo="$2"
  local relative_dir="peers-touch/$profile_name"
  local relative_profile="$relative_dir/profile.env.example"

  if ! git -C "$env_repo" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    echo "[ERROR] Environment repository is not a Git worktree: $env_repo"
    return 1
  fi
  if ! git -C "$env_repo" ls-files --error-unmatch "$relative_profile" >/dev/null 2>&1; then
    echo "[ERROR] Profile '$profile_name' is not Git-tracked in the env repository."
    echo "        Untracked topology cannot authorize profile selection."
    return 1
  fi
  if [[ -n "$(git -C "$env_repo" status --porcelain --untracked-files=all -- "$relative_dir")" ]]; then
    echo "[ERROR] Profile '$profile_name' has dirty or untracked env definitions."
    echo "        Review and commit the exact topology before activation."
    return 1
  fi
}

verify_authorized_local_profile() {
  local profile_name="$1"
  local profile_file="$2"
  python3 "$AUTHORIZATION_SCRIPT" verify \
    --workspace-root "$PROJECT_ROOT" \
    --profile "$profile_name" \
    --profile-file "$profile_file"
}

case "$cmd" in
  authorize)
    if [[ -z "$name" ]]; then
      echo "[ERROR] Usage: profile.sh authorize <name> [SLOT=N]"
      exit 1
    fi
    validate_profile_name "$name"
    slot="${SLOT:-0}"
    validate_slot "$slot"
    python3 "$AUTHORIZATION_SCRIPT" grant \
      --workspace-root "$PROJECT_ROOT" \
      --profile "$name" \
      --mode compose \
      --slot "$slot"
    ;;

  init)
    if [[ -z "$name" ]]; then
      echo "[ERROR] Usage: profile.sh init <name> [SLOT=N]"
      exit 1
    fi
    validate_profile_name "$name"
    slot="${SLOT:-0}"
    validate_slot "$slot"
    dest="$PROFILES_DIR/$name.env"
    if [[ -f "$dest" ]]; then
      echo "[ERROR] Profile '$name' already exists: $dest"
      echo "        profile-init never overwrites an existing environment."
      exit 1
    fi

    station_port=$((18080 + slot * 100))
    desktop_gw=$((3030 + slot * 100))
    desktop_web=$((3210 + slot * 100))
    desktop_web_gw=$((3031 + slot * 100))
    desktop_web_vite=$((3211 + slot * 100))
    mobile_web=$((5173 + slot * 100))

    temporary_profile="$(mktemp "$PROFILES_DIR/.${name}.XXXXXX")"
    cleanup_temporary_profile() {
      rm -f "$temporary_profile"
    }
    trap cleanup_temporary_profile EXIT

    cat > "$temporary_profile" <<EOF
# Profile: $name (slot $slot)
# Generated by: make profile-init PROFILE=$name SLOT=$slot

PT_DEV_PROFILE=$name
PT_DEV_SLOT=$slot
PT_AGENT_CONTROL_MODE=human-gated

# Station
PT_STATION_MODE=compose
PT_STATION_NAME=$name
PT_STATION_URL=http://127.0.0.1:$station_port
PT_STATION_PORT=$station_port
PT_STATION_DB_NAME=peers_touch_${name//-/_}
PT_STATION_COMPOSE_PROJECT=pt_${name//-/_}
PT_STATION_COMPOSE_ENV_FILE=
PT_STATION_DEPLOY_ENV=
PT_STATION_DEPLOY_BRANCH=
PT_STATION_HEALTH_URL=

# Relay
PT_RELAY_MODE=remote
PT_RELAY_URL=
PT_RELAY_DEPLOY_ENV=
PT_RELAY_DEPLOY_BRANCH=
PT_RELAY_HEALTH_URL=
PT_RELAY_MULTIADDR=
PT_BOOTSTRAP_NODES=

# Desktop
PT_DESKTOP_APP_GATEWAY_PORT=$desktop_gw
PT_DESKTOP_APP_WEB_PORT=$desktop_web
PT_DESKTOP_WEB_GATEWAY_PORT=$desktop_web_gw
PT_DESKTOP_WEB_WEB_PORT=$desktop_web_vite

# Mobile
PT_MOBILE_WEB_PORT=$mobile_web
PT_MOBILE_DEFAULT_STATION_URL=http://127.0.0.1:$station_port
EOF

    if ! receipt="$(python3 "$AUTHORIZATION_SCRIPT" consume \
      --workspace-root "$PROJECT_ROOT" \
      --profile "$name" \
      --profile-file "$temporary_profile")"; then
      echo "[ERROR] profile-init requires a matching human-created authorization."
      echo "        Run interactively: make profile-authorize PROFILE=$name SLOT=$slot"
      exit 1
    fi
    chmod 600 "$temporary_profile"
    mv "$temporary_profile" "$dest"
    trap - EXIT
    echo "[OK] Created profile: $dest"
    echo "     Authorization receipt: $receipt"
    echo "     Register with: make env-register PROFILE=$name SLOT=$slot CAPABILITIES=station.connect PURPOSE='<purpose>'"
    ;;

  list)
    echo "Available profiles:"
    env_repo=""
    if resolved="$(resolve_env_repo)"; then
      env_repo="$resolved"
    fi
    profile_names="$(
      {
        for f in "$PROFILES_DIR"/*.env; do
          [[ -f "$f" ]] && basename "$f" .env
        done
        if [[ -n "$env_repo" ]]; then
          for f in "$env_repo"/peers-touch/*/profile.env.example; do
            [[ -f "$f" ]] && basename "$(dirname "$f")"
          done
        fi
      } | sort -u
    )"
    if [[ -n "$profile_names" ]]; then
      while IFS= read -r pname; do
        [[ -n "$pname" ]] || continue
        f="$PROFILES_DIR/$pname.env"
        source_kind="unapproved"
        if [[ -n "$env_repo" && -f "$env_repo/peers-touch/$pname/profile.env.example" ]] \
          && require_reviewed_env_profile "$pname" "$env_repo" >/dev/null 2>&1; then
          source_kind="canonical"
        elif [[ -f "$f" ]] \
          && verify_authorized_local_profile "$pname" "$f" >/dev/null 2>&1; then
          source_kind="authorized-local"
        fi
        echo "    $pname ($source_kind)"
      done <<< "$profile_names"
    else
      echo "  (none)"
      echo ""
      echo "  Human authorization: make profile-authorize PROFILE=local-a SLOT=0"
      echo "  Then create: make profile-init PROFILE=local-a SLOT=0"
    fi
    echo ""
    echo "Local deploy env cache is non-authoritative."
    echo "Remote deploys resolve reviewed definitions directly from the env repository."
    ;;

  *)
    echo "Usage: profile.sh {authorize|init|list} [name]"
    exit 1
    ;;
esac
