// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: domain/federation/locator.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ActorLocatorRecord is the on-the-wire shape of a signed locator pointer
// stored in the libp2p DHT under "/pst-actor/<federated_handle>".
//
// Receivers do NOT trust the record fields directly. They:
//  1. Verify `signature` against `signing_key_pem` using the canonical
//     serialisation (deterministic field ordering — see
//     apps/station/frame/core/plugin/native/federation/locator/record.go).
//  2. TOFU pin (federated_handle, signing_key_pem) on first sight.
//     A subsequent record claiming the same handle with a different key
//     MUST be rejected unless the new record carries a valid signature
//     from the *previously pinned* key (key-rotation / handover envelope —
//     not in scope for the initial drop).
//  3. Use `seq` to dedupe: lower-or-equal `seq` is dropped.
//
// The record body intentionally carries NO profile data. It is a *pointer*:
// "to talk to @alice@station-1.example, dial the home station whose libp2p
// PeerID is X and whose HTTP origin is Y, then GET /api/v1/federation/
// resolve?handle=...". Profile retrieval lives in the resolver layer.
type ActorLocatorRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Canonical federated handle, e.g. "@alice@station-1.example". Always
	// lower-cased on the publish path so DHT keys are byte-stable.
	FederatedHandle string `protobuf:"bytes,1,opt,name=federated_handle,proto3" json:"federated_handle,omitempty"`
	// Authoritative home station — the only station that may legitimately
	// sign this handle. Cross-checked against signing_key_pem during TOFU.
	HomeStationPeerId string `protobuf:"bytes,2,opt,name=home_station_peer_id,proto3" json:"home_station_peer_id,omitempty"`
	// Stable HTTP origin of the home station, no scheme. Receivers MUST NOT
	// dial this directly across the federation; instead it is fed through
	// `/relay/forward/{home_station_peer_id}/...` so NAT-bound stations
	// remain reachable.
	HomeStationDomain string `protobuf:"bytes,3,opt,name=home_station_domain,proto3" json:"home_station_domain,omitempty"`
	// Optional list of relay-mount labels through which this actor's home
	// station is reachable today. Pure hint — the resolver still authoritatively
	// looks up the live mount table from the relay before forwarding.
	InboxRelayMounts []string `protobuf:"bytes,4,rep,name=inbox_relay_mounts,proto3" json:"inbox_relay_mounts,omitempty"`
	// Tombstone flag. When true, the record is a withdrawal: receivers MUST
	// overwrite any cached entry for this handle and refuse to surface the
	// actor across the federation. Tombstones are signed exactly like live
	// records and persist in the DHT until expiry.
	Tombstone bool `protobuf:"varint,5,opt,name=tombstone,proto3" json:"tombstone,omitempty"`
	// Monotonic per-handle counter. Higher seq beats lower seq; equal-seq
	// races are broken by `updated_at_unix_ms` and finally by lexicographic
	// signature compare. Seq is reset only via the (out-of-scope) handover
	// envelope — never decreased by routine updates.
	Seq uint64 `protobuf:"varint,6,opt,name=seq,proto3" json:"seq,omitempty"`
	// Wall-clock the publisher minted the record. Receivers may reject
	// records older than a configurable freshness window; a record older
	// than ~24h is treated as stale and re-fetched.
	UpdatedAtUnixMs int64 `protobuf:"varint,7,opt,name=updated_at_unix_ms,proto3" json:"updated_at_unix_ms,omitempty"`
	// Detached Ed25519 signature over the canonical serialisation of every
	// OTHER field in this message (i.e. all fields except `signature`).
	Signature []byte `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	// PEM-encoded Ed25519 public key matching `home_station_peer_id`'s
	// station-signing key (NOT the libp2p host key — the federation key
	// managed by frame/core/auth/federation). Embedded so first-time
	// receivers can verify on TOFU without a side-channel JWKS fetch.
	SigningKeyPem string `protobuf:"bytes,9,opt,name=signing_key_pem,proto3" json:"signing_key_pem,omitempty"`
	// SHA-256 / base32-nopad fingerprint of `signing_key_pem`. Receivers
	// recompute this and compare; mismatch is a tampered record.
	SigningKeyKid string `protobuf:"bytes,10,opt,name=signing_key_kid,proto3" json:"signing_key_kid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorLocatorRecord) Reset() {
	*x = ActorLocatorRecord{}
	mi := &file_domain_federation_locator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorLocatorRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorLocatorRecord) ProtoMessage() {}

func (x *ActorLocatorRecord) ProtoReflect() protoreflect.Message {
	mi := &file_domain_federation_locator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorLocatorRecord.ProtoReflect.Descriptor instead.
func (*ActorLocatorRecord) Descriptor() ([]byte, []int) {
	return file_domain_federation_locator_proto_rawDescGZIP(), []int{0}
}

func (x *ActorLocatorRecord) GetFederatedHandle() string {
	if x != nil {
		return x.FederatedHandle
	}
	return ""
}

func (x *ActorLocatorRecord) GetHomeStationPeerId() string {
	if x != nil {
		return x.HomeStationPeerId
	}
	return ""
}

func (x *ActorLocatorRecord) GetHomeStationDomain() string {
	if x != nil {
		return x.HomeStationDomain
	}
	return ""
}

func (x *ActorLocatorRecord) GetInboxRelayMounts() []string {
	if x != nil {
		return x.InboxRelayMounts
	}
	return nil
}

func (x *ActorLocatorRecord) GetTombstone() bool {
	if x != nil {
		return x.Tombstone
	}
	return false
}

func (x *ActorLocatorRecord) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ActorLocatorRecord) GetUpdatedAtUnixMs() int64 {
	if x != nil {
		return x.UpdatedAtUnixMs
	}
	return 0
}

func (x *ActorLocatorRecord) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ActorLocatorRecord) GetSigningKeyPem() string {
	if x != nil {
		return x.SigningKeyPem
	}
	return ""
}

func (x *ActorLocatorRecord) GetSigningKeyKid() string {
	if x != nil {
		return x.SigningKeyKid
	}
	return ""
}

var File_domain_federation_locator_proto protoreflect.FileDescriptor

const file_domain_federation_locator_proto_rawDesc = "" +
	"\n" +
	"\x1fdomain/federation/locator.proto\x12\x1fpeers_touch.model.federation.v1\"\xa8\x03\n" +
	"\x12ActorLocatorRecord\x12*\n" +
	"\x10federated_handle\x18\x01 \x01(\tR\x10federated_handle\x122\n" +
	"\x14home_station_peer_id\x18\x02 \x01(\tR\x14home_station_peer_id\x120\n" +
	"\x13home_station_domain\x18\x03 \x01(\tR\x13home_station_domain\x12.\n" +
	"\x12inbox_relay_mounts\x18\x04 \x03(\tR\x12inbox_relay_mounts\x12\x1c\n" +
	"\ttombstone\x18\x05 \x01(\bR\ttombstone\x12\x10\n" +
	"\x03seq\x18\x06 \x01(\x04R\x03seq\x12.\n" +
	"\x12updated_at_unix_ms\x18\a \x01(\x03R\x12updated_at_unix_ms\x12\x1c\n" +
	"\tsignature\x18\b \x01(\fR\tsignature\x12(\n" +
	"\x0fsigning_key_pem\x18\t \x01(\tR\x0fsigning_key_pem\x12(\n" +
	"\x0fsigning_key_kid\x18\n" +
	" \x01(\tR\x0fsigning_key_kidB]Z[github.com/peers-labs/peers-touch/station/frame/core/plugin/native/federation/locator/pb;pbb\x06proto3"

var (
	file_domain_federation_locator_proto_rawDescOnce sync.Once
	file_domain_federation_locator_proto_rawDescData []byte
)

func file_domain_federation_locator_proto_rawDescGZIP() []byte {
	file_domain_federation_locator_proto_rawDescOnce.Do(func() {
		file_domain_federation_locator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_federation_locator_proto_rawDesc), len(file_domain_federation_locator_proto_rawDesc)))
	})
	return file_domain_federation_locator_proto_rawDescData
}

var file_domain_federation_locator_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_domain_federation_locator_proto_goTypes = []any{
	(*ActorLocatorRecord)(nil), // 0: peers_touch.model.federation.v1.ActorLocatorRecord
}
var file_domain_federation_locator_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_domain_federation_locator_proto_init() }
func file_domain_federation_locator_proto_init() {
	if File_domain_federation_locator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_federation_locator_proto_rawDesc), len(file_domain_federation_locator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_federation_locator_proto_goTypes,
		DependencyIndexes: file_domain_federation_locator_proto_depIdxs,
		MessageInfos:      file_domain_federation_locator_proto_msgTypes,
	}.Build()
	File_domain_federation_locator_proto = out.File
	file_domain_federation_locator_proto_goTypes = nil
	file_domain_federation_locator_proto_depIdxs = nil
}
