// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: domain/actor/actor.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActorKind int32

const (
	ActorKind_ACTOR_KIND_UNSPECIFIED  ActorKind = 0
	ActorKind_ACTOR_KIND_PERSON       ActorKind = 1
	ActorKind_ACTOR_KIND_GROUP        ActorKind = 2
	ActorKind_ACTOR_KIND_ORGANIZATION ActorKind = 3
	ActorKind_ACTOR_KIND_SERVICE      ActorKind = 4
	ActorKind_ACTOR_KIND_APPLICATION  ActorKind = 5
	ActorKind_ACTOR_KIND_NODE         ActorKind = 6
)

// Enum value maps for ActorKind.
var (
	ActorKind_name = map[int32]string{
		0: "ACTOR_KIND_UNSPECIFIED",
		1: "ACTOR_KIND_PERSON",
		2: "ACTOR_KIND_GROUP",
		3: "ACTOR_KIND_ORGANIZATION",
		4: "ACTOR_KIND_SERVICE",
		5: "ACTOR_KIND_APPLICATION",
		6: "ACTOR_KIND_NODE",
	}
	ActorKind_value = map[string]int32{
		"ACTOR_KIND_UNSPECIFIED":  0,
		"ACTOR_KIND_PERSON":       1,
		"ACTOR_KIND_GROUP":        2,
		"ACTOR_KIND_ORGANIZATION": 3,
		"ACTOR_KIND_SERVICE":      4,
		"ACTOR_KIND_APPLICATION":  5,
		"ACTOR_KIND_NODE":         6,
	}
)

func (x ActorKind) Enum() *ActorKind {
	p := new(ActorKind)
	*p = x
	return p
}

func (x ActorKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActorKind) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_actor_actor_proto_enumTypes[0].Descriptor()
}

func (ActorKind) Type() protoreflect.EnumType {
	return &file_domain_actor_actor_proto_enumTypes[0]
}

func (x ActorKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActorKind.Descriptor instead.
func (ActorKind) EnumDescriptor() ([]byte, []int) {
	return file_domain_actor_actor_proto_rawDescGZIP(), []int{0}
}

// ActorOrigin tells the consumer whether this actor row was authored on the
// local station (local) or fetched from a peer station and cached locally
// (remote_cached). Touch UIs use it to gate edit affordances; the locator
// publisher uses it to refuse publishing remote-cached rows back into the DHT.
type ActorOrigin int32

const (
	ActorOrigin_ACTOR_ORIGIN_UNSPECIFIED   ActorOrigin = 0
	ActorOrigin_ACTOR_ORIGIN_LOCAL         ActorOrigin = 1
	ActorOrigin_ACTOR_ORIGIN_REMOTE_CACHED ActorOrigin = 2
)

// Enum value maps for ActorOrigin.
var (
	ActorOrigin_name = map[int32]string{
		0: "ACTOR_ORIGIN_UNSPECIFIED",
		1: "ACTOR_ORIGIN_LOCAL",
		2: "ACTOR_ORIGIN_REMOTE_CACHED",
	}
	ActorOrigin_value = map[string]int32{
		"ACTOR_ORIGIN_UNSPECIFIED":   0,
		"ACTOR_ORIGIN_LOCAL":         1,
		"ACTOR_ORIGIN_REMOTE_CACHED": 2,
	}
)

func (x ActorOrigin) Enum() *ActorOrigin {
	p := new(ActorOrigin)
	*p = x
	return p
}

func (x ActorOrigin) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActorOrigin) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_actor_actor_proto_enumTypes[1].Descriptor()
}

func (ActorOrigin) Type() protoreflect.EnumType {
	return &file_domain_actor_actor_proto_enumTypes[1]
}

func (x ActorOrigin) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActorOrigin.Descriptor instead.
func (ActorOrigin) EnumDescriptor() ([]byte, []int) {
	return file_domain_actor_actor_proto_rawDescGZIP(), []int{1}
}

// ActorVisibility is the federation-discoverability state of an actor.
//
// ACTOR_VISIBILITY_HIDDEN     — never published to DHT, never resolvable
//
//	by handle from other stations.
//
// ACTOR_VISIBILITY_BY_HANDLE  — published to the DHT under its federated
//
//	handle. Other stations can resolve it iff
//	they know the exact handle (no enumeration).
//
// ACTOR_VISIBILITY_INDEXED    — same as BY_HANDLE plus opt-in to a future
//
//	directory-style index. Treated identically
//	to BY_HANDLE by the DHT publisher today;
//	the directory layer is Phase C.
//
// The ordering matters: hidden < by_handle < indexed. Numeric increases
// monotonically widen visibility; the publisher uses this to decide whether
// to publish or tombstone.
type ActorVisibility int32

const (
	ActorVisibility_ACTOR_VISIBILITY_UNSPECIFIED ActorVisibility = 0
	ActorVisibility_ACTOR_VISIBILITY_HIDDEN      ActorVisibility = 1
	ActorVisibility_ACTOR_VISIBILITY_BY_HANDLE   ActorVisibility = 2
	ActorVisibility_ACTOR_VISIBILITY_INDEXED     ActorVisibility = 3
)

// Enum value maps for ActorVisibility.
var (
	ActorVisibility_name = map[int32]string{
		0: "ACTOR_VISIBILITY_UNSPECIFIED",
		1: "ACTOR_VISIBILITY_HIDDEN",
		2: "ACTOR_VISIBILITY_BY_HANDLE",
		3: "ACTOR_VISIBILITY_INDEXED",
	}
	ActorVisibility_value = map[string]int32{
		"ACTOR_VISIBILITY_UNSPECIFIED": 0,
		"ACTOR_VISIBILITY_HIDDEN":      1,
		"ACTOR_VISIBILITY_BY_HANDLE":   2,
		"ACTOR_VISIBILITY_INDEXED":     3,
	}
)

func (x ActorVisibility) Enum() *ActorVisibility {
	p := new(ActorVisibility)
	*p = x
	return p
}

func (x ActorVisibility) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActorVisibility) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_actor_actor_proto_enumTypes[2].Descriptor()
}

func (ActorVisibility) Type() protoreflect.EnumType {
	return &file_domain_actor_actor_proto_enumTypes[2]
}

func (x ActorVisibility) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActorVisibility.Descriptor instead.
func (ActorVisibility) EnumDescriptor() ([]byte, []int) {
	return file_domain_actor_actor_proto_rawDescGZIP(), []int{2}
}

type ActorDeviceStatus int32

const (
	ActorDeviceStatus_ACTOR_DEVICE_STATUS_UNSPECIFIED    ActorDeviceStatus = 0
	ActorDeviceStatus_ACTOR_DEVICE_STATUS_ENROLLING      ActorDeviceStatus = 1
	ActorDeviceStatus_ACTOR_DEVICE_STATUS_ACTIVE         ActorDeviceStatus = 2
	ActorDeviceStatus_ACTOR_DEVICE_STATUS_REVOKE_PENDING ActorDeviceStatus = 3
	ActorDeviceStatus_ACTOR_DEVICE_STATUS_REVOKED        ActorDeviceStatus = 4
)

// Enum value maps for ActorDeviceStatus.
var (
	ActorDeviceStatus_name = map[int32]string{
		0: "ACTOR_DEVICE_STATUS_UNSPECIFIED",
		1: "ACTOR_DEVICE_STATUS_ENROLLING",
		2: "ACTOR_DEVICE_STATUS_ACTIVE",
		3: "ACTOR_DEVICE_STATUS_REVOKE_PENDING",
		4: "ACTOR_DEVICE_STATUS_REVOKED",
	}
	ActorDeviceStatus_value = map[string]int32{
		"ACTOR_DEVICE_STATUS_UNSPECIFIED":    0,
		"ACTOR_DEVICE_STATUS_ENROLLING":      1,
		"ACTOR_DEVICE_STATUS_ACTIVE":         2,
		"ACTOR_DEVICE_STATUS_REVOKE_PENDING": 3,
		"ACTOR_DEVICE_STATUS_REVOKED":        4,
	}
)

func (x ActorDeviceStatus) Enum() *ActorDeviceStatus {
	p := new(ActorDeviceStatus)
	*p = x
	return p
}

func (x ActorDeviceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActorDeviceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_actor_actor_proto_enumTypes[3].Descriptor()
}

func (ActorDeviceStatus) Type() protoreflect.EnumType {
	return &file_domain_actor_actor_proto_enumTypes[3]
}

func (x ActorDeviceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActorDeviceStatus.Descriptor instead.
func (ActorDeviceStatus) EnumDescriptor() ([]byte, []int) {
	return file_domain_actor_actor_proto_rawDescGZIP(), []int{3}
}

type ActorSigningKeyVerificationSource int32

const (
	ActorSigningKeyVerificationSource_ACTOR_SIGNING_KEY_VERIFICATION_SOURCE_UNSPECIFIED               ActorSigningKeyVerificationSource = 0
	ActorSigningKeyVerificationSource_ACTOR_SIGNING_KEY_VERIFICATION_SOURCE_LOCAL_DEVICE_REGISTRATION ActorSigningKeyVerificationSource = 1
	ActorSigningKeyVerificationSource_ACTOR_SIGNING_KEY_VERIFICATION_SOURCE_VERIFIED_PROFILE          ActorSigningKeyVerificationSource = 2
	ActorSigningKeyVerificationSource_ACTOR_SIGNING_KEY_VERIFICATION_SOURCE_VERIFIED_LOCATOR          ActorSigningKeyVerificationSource = 3
)

// Enum value maps for ActorSigningKeyVerificationSource.
var (
	ActorSigningKeyVerificationSource_name = map[int32]string{
		0: "ACTOR_SIGNING_KEY_VERIFICATION_SOURCE_UNSPECIFIED",
		1: "ACTOR_SIGNING_KEY_VERIFICATION_SOURCE_LOCAL_DEVICE_REGISTRATION",
		2: "ACTOR_SIGNING_KEY_VERIFICATION_SOURCE_VERIFIED_PROFILE",
		3: "ACTOR_SIGNING_KEY_VERIFICATION_SOURCE_VERIFIED_LOCATOR",
	}
	ActorSigningKeyVerificationSource_value = map[string]int32{
		"ACTOR_SIGNING_KEY_VERIFICATION_SOURCE_UNSPECIFIED":               0,
		"ACTOR_SIGNING_KEY_VERIFICATION_SOURCE_LOCAL_DEVICE_REGISTRATION": 1,
		"ACTOR_SIGNING_KEY_VERIFICATION_SOURCE_VERIFIED_PROFILE":          2,
		"ACTOR_SIGNING_KEY_VERIFICATION_SOURCE_VERIFIED_LOCATOR":          3,
	}
)

func (x ActorSigningKeyVerificationSource) Enum() *ActorSigningKeyVerificationSource {
	p := new(ActorSigningKeyVerificationSource)
	*p = x
	return p
}

func (x ActorSigningKeyVerificationSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActorSigningKeyVerificationSource) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_actor_actor_proto_enumTypes[4].Descriptor()
}

func (ActorSigningKeyVerificationSource) Type() protoreflect.EnumType {
	return &file_domain_actor_actor_proto_enumTypes[4]
}

func (x ActorSigningKeyVerificationSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActorSigningKeyVerificationSource.Descriptor instead.
func (ActorSigningKeyVerificationSource) EnumDescriptor() ([]byte, []int) {
	return file_domain_actor_actor_proto_rawDescGZIP(), []int{4}
}

type ActorRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ptid          string                 `protobuf:"bytes,2,opt,name=ptid,proto3" json:"ptid,omitempty"`
	Acct          string                 `protobuf:"bytes,3,opt,name=acct,proto3" json:"acct,omitempty"`
	Kind          ActorKind              `protobuf:"varint,4,opt,name=kind,proto3,enum=peers_touch.model.actor.v1.ActorKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorRef) Reset() {
	*x = ActorRef{}
	mi := &file_domain_actor_actor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorRef) ProtoMessage() {}

func (x *ActorRef) ProtoReflect() protoreflect.Message {
	mi := &file_domain_actor_actor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorRef.ProtoReflect.Descriptor instead.
func (*ActorRef) Descriptor() ([]byte, []int) {
	return file_domain_actor_actor_proto_rawDescGZIP(), []int{0}
}

func (x *ActorRef) GetPtid() string {
	if x != nil {
		return x.Ptid
	}
	return ""
}

func (x *ActorRef) GetAcct() string {
	if x != nil {
		return x.Acct
	}
	return ""
}

func (x *ActorRef) GetKind() ActorKind {
	if x != nil {
		return x.Kind
	}
	return ActorKind_ACTOR_KIND_UNSPECIFIED
}

type ActorDeviceRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *ActorRef              `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorDeviceRef) Reset() {
	*x = ActorDeviceRef{}
	mi := &file_domain_actor_actor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorDeviceRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorDeviceRef) ProtoMessage() {}

func (x *ActorDeviceRef) ProtoReflect() protoreflect.Message {
	mi := &file_domain_actor_actor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorDeviceRef.ProtoReflect.Descriptor instead.
func (*ActorDeviceRef) Descriptor() ([]byte, []int) {
	return file_domain_actor_actor_proto_rawDescGZIP(), []int{1}
}

func (x *ActorDeviceRef) GetActor() *ActorRef {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *ActorDeviceRef) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

// Deterministic actor-signed authorization for one fresh device.
type ActorDeviceCertificate struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	FormatVersion               uint32                 `protobuf:"varint,1,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`
	Device                      *ActorDeviceRef        `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	ActorIdentityPublicKey      []byte                 `protobuf:"bytes,3,opt,name=actor_identity_public_key,json=actorIdentityPublicKey,proto3" json:"actor_identity_public_key,omitempty"`
	ActorIdentityKeyFingerprint []byte                 `protobuf:"bytes,4,opt,name=actor_identity_key_fingerprint,json=actorIdentityKeyFingerprint,proto3" json:"actor_identity_key_fingerprint,omitempty"`
	DeviceSigningPublicKey      []byte                 `protobuf:"bytes,5,opt,name=device_signing_public_key,json=deviceSigningPublicKey,proto3" json:"device_signing_public_key,omitempty"`
	SigningKeyId                string                 `protobuf:"bytes,6,opt,name=signing_key_id,json=signingKeyId,proto3" json:"signing_key_id,omitempty"`
	ObservedProfileVersion      uint64                 `protobuf:"varint,7,opt,name=observed_profile_version,json=observedProfileVersion,proto3" json:"observed_profile_version,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *ActorDeviceCertificate) Reset() {
	*x = ActorDeviceCertificate{}
	mi := &file_domain_actor_actor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorDeviceCertificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorDeviceCertificate) ProtoMessage() {}

func (x *ActorDeviceCertificate) ProtoReflect() protoreflect.Message {
	mi := &file_domain_actor_actor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorDeviceCertificate.ProtoReflect.Descriptor instead.
func (*ActorDeviceCertificate) Descriptor() ([]byte, []int) {
	return file_domain_actor_actor_proto_rawDescGZIP(), []int{2}
}

func (x *ActorDeviceCertificate) GetFormatVersion() uint32 {
	if x != nil {
		return x.FormatVersion
	}
	return 0
}

func (x *ActorDeviceCertificate) GetDevice() *ActorDeviceRef {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *ActorDeviceCertificate) GetActorIdentityPublicKey() []byte {
	if x != nil {
		return x.ActorIdentityPublicKey
	}
	return nil
}

func (x *ActorDeviceCertificate) GetActorIdentityKeyFingerprint() []byte {
	if x != nil {
		return x.ActorIdentityKeyFingerprint
	}
	return nil
}

func (x *ActorDeviceCertificate) GetDeviceSigningPublicKey() []byte {
	if x != nil {
		return x.DeviceSigningPublicKey
	}
	return nil
}

func (x *ActorDeviceCertificate) GetSigningKeyId() string {
	if x != nil {
		return x.SigningKeyId
	}
	return ""
}

func (x *ActorDeviceCertificate) GetObservedProfileVersion() uint64 {
	if x != nil {
		return x.ObservedProfileVersion
	}
	return 0
}

type ActorDevice struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	Ref                         *ActorDeviceRef        `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Status                      ActorDeviceStatus      `protobuf:"varint,2,opt,name=status,proto3,enum=peers_touch.model.actor.v1.ActorDeviceStatus" json:"status,omitempty"`
	Label                       string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	ActorIdentityKeyFingerprint []byte                 `protobuf:"bytes,4,opt,name=actor_identity_key_fingerprint,json=actorIdentityKeyFingerprint,proto3" json:"actor_identity_key_fingerprint,omitempty"`
	SigningKeyId                string                 `protobuf:"bytes,5,opt,name=signing_key_id,json=signingKeyId,proto3" json:"signing_key_id,omitempty"`
	DeviceSigningPublicKey      []byte                 `protobuf:"bytes,6,opt,name=device_signing_public_key,json=deviceSigningPublicKey,proto3" json:"device_signing_public_key,omitempty"`
	ProfileVersion              uint64                 `protobuf:"varint,7,opt,name=profile_version,json=profileVersion,proto3" json:"profile_version,omitempty"`
	ActivationSequence          int64                  `protobuf:"varint,8,opt,name=activation_sequence,json=activationSequence,proto3" json:"activation_sequence,omitempty"`
	EnrolledAt                  *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=enrolled_at,json=enrolledAt,proto3" json:"enrolled_at,omitempty"`
	RevokedAt                   *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *ActorDevice) Reset() {
	*x = ActorDevice{}
	mi := &file_domain_actor_actor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorDevice) ProtoMessage() {}

func (x *ActorDevice) ProtoReflect() protoreflect.Message {
	mi := &file_domain_actor_actor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorDevice.ProtoReflect.Descriptor instead.
func (*ActorDevice) Descriptor() ([]byte, []int) {
	return file_domain_actor_actor_proto_rawDescGZIP(), []int{3}
}

func (x *ActorDevice) GetRef() *ActorDeviceRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *ActorDevice) GetStatus() ActorDeviceStatus {
	if x != nil {
		return x.Status
	}
	return ActorDeviceStatus_ACTOR_DEVICE_STATUS_UNSPECIFIED
}

func (x *ActorDevice) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ActorDevice) GetActorIdentityKeyFingerprint() []byte {
	if x != nil {
		return x.ActorIdentityKeyFingerprint
	}
	return nil
}

func (x *ActorDevice) GetSigningKeyId() string {
	if x != nil {
		return x.SigningKeyId
	}
	return ""
}

func (x *ActorDevice) GetDeviceSigningPublicKey() []byte {
	if x != nil {
		return x.DeviceSigningPublicKey
	}
	return nil
}

func (x *ActorDevice) GetProfileVersion() uint64 {
	if x != nil {
		return x.ProfileVersion
	}
	return 0
}

func (x *ActorDevice) GetActivationSequence() int64 {
	if x != nil {
		return x.ActivationSequence
	}
	return 0
}

func (x *ActorDevice) GetEnrolledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EnrolledAt
	}
	return nil
}

func (x *ActorDevice) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

type EnrollActorDeviceRequest struct {
	state               protoimpl.MessageState  `protogen:"open.v1"`
	Certificate         *ActorDeviceCertificate `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`
	Label               string                  `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	ActorCrossSignature []byte                  `protobuf:"bytes,3,opt,name=actor_cross_signature,json=actorCrossSignature,proto3" json:"actor_cross_signature,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EnrollActorDeviceRequest) Reset() {
	*x = EnrollActorDeviceRequest{}
	mi := &file_domain_actor_actor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollActorDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollActorDeviceRequest) ProtoMessage() {}

func (x *EnrollActorDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_actor_actor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollActorDeviceRequest.ProtoReflect.Descriptor instead.
func (*EnrollActorDeviceRequest) Descriptor() ([]byte, []int) {
	return file_domain_actor_actor_proto_rawDescGZIP(), []int{4}
}

func (x *EnrollActorDeviceRequest) GetCertificate() *ActorDeviceCertificate {
	if x != nil {
		return x.Certificate
	}
	return nil
}

func (x *EnrollActorDeviceRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *EnrollActorDeviceRequest) GetActorCrossSignature() []byte {
	if x != nil {
		return x.ActorCrossSignature
	}
	return nil
}

type EnrollActorDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *ActorDevice           `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollActorDeviceResponse) Reset() {
	*x = EnrollActorDeviceResponse{}
	mi := &file_domain_actor_actor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollActorDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollActorDeviceResponse) ProtoMessage() {}

func (x *EnrollActorDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_actor_actor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollActorDeviceResponse.ProtoReflect.Descriptor instead.
func (*EnrollActorDeviceResponse) Descriptor() ([]byte, []int) {
	return file_domain_actor_actor_proto_rawDescGZIP(), []int{5}
}

func (x *EnrollActorDeviceResponse) GetDevice() *ActorDevice {
	if x != nil {
		return x.Device
	}
	return nil
}

type ListActorDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActorDevicesRequest) Reset() {
	*x = ListActorDevicesRequest{}
	mi := &file_domain_actor_actor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActorDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActorDevicesRequest) ProtoMessage() {}

func (x *ListActorDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_actor_actor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActorDevicesRequest.ProtoReflect.Descriptor instead.
func (*ListActorDevicesRequest) Descriptor() ([]byte, []int) {
	return file_domain_actor_actor_proto_rawDescGZIP(), []int{6}
}

type ListActorDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*ActorDevice         `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActorDevicesResponse) Reset() {
	*x = ListActorDevicesResponse{}
	mi := &file_domain_actor_actor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActorDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActorDevicesResponse) ProtoMessage() {}

func (x *ListActorDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_actor_actor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActorDevicesResponse.ProtoReflect.Descriptor instead.
func (*ListActorDevicesResponse) Descriptor() ([]byte, []int) {
	return file_domain_actor_actor_proto_rawDescGZIP(), []int{7}
}

func (x *ListActorDevicesResponse) GetDevices() []*ActorDevice {
	if x != nil {
		return x.Devices
	}
	return nil
}

type RevokeActorDeviceRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	DeviceId               string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ObservedProfileVersion uint64                 `protobuf:"varint,2,opt,name=observed_profile_version,json=observedProfileVersion,proto3" json:"observed_profile_version,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RevokeActorDeviceRequest) Reset() {
	*x = RevokeActorDeviceRequest{}
	mi := &file_domain_actor_actor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeActorDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeActorDeviceRequest) ProtoMessage() {}

func (x *RevokeActorDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_actor_actor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeActorDeviceRequest.ProtoReflect.Descriptor instead.
func (*RevokeActorDeviceRequest) Descriptor() ([]byte, []int) {
	return file_domain_actor_actor_proto_rawDescGZIP(), []int{8}
}

func (x *RevokeActorDeviceRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *RevokeActorDeviceRequest) GetObservedProfileVersion() uint64 {
	if x != nil {
		return x.ObservedProfileVersion
	}
	return 0
}

type RevokeActorDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *ActorDevice           `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeActorDeviceResponse) Reset() {
	*x = RevokeActorDeviceResponse{}
	mi := &file_domain_actor_actor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeActorDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeActorDeviceResponse) ProtoMessage() {}

func (x *RevokeActorDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_actor_actor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeActorDeviceResponse.ProtoReflect.Descriptor instead.
func (*RevokeActorDeviceResponse) Descriptor() ([]byte, []int) {
	return file_domain_actor_actor_proto_rawDescGZIP(), []int{9}
}

func (x *RevokeActorDeviceResponse) GetDevice() *ActorDevice {
	if x != nil {
		return x.Device
	}
	return nil
}

type ActorEndpointManifestEntry struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Endpoint             *ActorDeviceRef        `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	SigningKeyId         string                 `protobuf:"bytes,2,opt,name=signing_key_id,json=signingKeyId,proto3" json:"signing_key_id,omitempty"`
	PublicMaterialSha256 [][]byte               `protobuf:"bytes,3,rep,name=public_material_sha256,json=publicMaterialSha256,proto3" json:"public_material_sha256,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ActorEndpointManifestEntry) Reset() {
	*x = ActorEndpointManifestEntry{}
	mi := &file_domain_actor_actor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorEndpointManifestEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorEndpointManifestEntry) ProtoMessage() {}

func (x *ActorEndpointManifestEntry) ProtoReflect() protoreflect.Message {
	mi := &file_domain_actor_actor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorEndpointManifestEntry.ProtoReflect.Descriptor instead.
func (*ActorEndpointManifestEntry) Descriptor() ([]byte, []int) {
	return file_domain_actor_actor_proto_rawDescGZIP(), []int{10}
}

func (x *ActorEndpointManifestEntry) GetEndpoint() *ActorDeviceRef {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

func (x *ActorEndpointManifestEntry) GetSigningKeyId() string {
	if x != nil {
		return x.SigningKeyId
	}
	return ""
}

func (x *ActorEndpointManifestEntry) GetPublicMaterialSha256() [][]byte {
	if x != nil {
		return x.PublicMaterialSha256
	}
	return nil
}

type ActorEndpointManifestSigningInput struct {
	state                  protoimpl.MessageState        `protogen:"open.v1"`
	FormatVersion          uint32                        `protobuf:"varint,1,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`
	ManifestId             string                        `protobuf:"bytes,2,opt,name=manifest_id,json=manifestId,proto3" json:"manifest_id,omitempty"`
	Actor                  *ActorRef                     `protobuf:"bytes,3,opt,name=actor,proto3" json:"actor,omitempty"`
	HomeStationPeerId      string                        `protobuf:"bytes,4,opt,name=home_station_peer_id,json=homeStationPeerId,proto3" json:"home_station_peer_id,omitempty"`
	DirectoryVersion       uint64                        `protobuf:"varint,5,opt,name=directory_version,json=directoryVersion,proto3" json:"directory_version,omitempty"`
	ActiveEndpoints        []*ActorEndpointManifestEntry `protobuf:"bytes,6,rep,name=active_endpoints,json=activeEndpoints,proto3" json:"active_endpoints,omitempty"`
	IssuedAt               *timestamppb.Timestamp        `protobuf:"bytes,7,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	ExpiresAt              *timestamppb.Timestamp        `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	SigningKeyId           string                        `protobuf:"bytes,9,opt,name=signing_key_id,json=signingKeyId,proto3" json:"signing_key_id,omitempty"`
	ActorIdentityPublicKey []byte                        `protobuf:"bytes,10,opt,name=actor_identity_public_key,json=actorIdentityPublicKey,proto3" json:"actor_identity_public_key,omitempty"`
	ActorProfileVersion    uint64                        `protobuf:"varint,11,opt,name=actor_profile_version,json=actorProfileVersion,proto3" json:"actor_profile_version,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ActorEndpointManifestSigningInput) Reset() {
	*x = ActorEndpointManifestSigningInput{}
	mi := &file_domain_actor_actor_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorEndpointManifestSigningInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorEndpointManifestSigningInput) ProtoMessage() {}

func (x *ActorEndpointManifestSigningInput) ProtoReflect() protoreflect.Message {
	mi := &file_domain_actor_actor_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorEndpointManifestSigningInput.ProtoReflect.Descriptor instead.
func (*ActorEndpointManifestSigningInput) Descriptor() ([]byte, []int) {
	return file_domain_actor_actor_proto_rawDescGZIP(), []int{11}
}

func (x *ActorEndpointManifestSigningInput) GetFormatVersion() uint32 {
	if x != nil {
		return x.FormatVersion
	}
	return 0
}

func (x *ActorEndpointManifestSigningInput) GetManifestId() string {
	if x != nil {
		return x.ManifestId
	}
	return ""
}

func (x *ActorEndpointManifestSigningInput) GetActor() *ActorRef {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *ActorEndpointManifestSigningInput) GetHomeStationPeerId() string {
	if x != nil {
		return x.HomeStationPeerId
	}
	return ""
}

func (x *ActorEndpointManifestSigningInput) GetDirectoryVersion() uint64 {
	if x != nil {
		return x.DirectoryVersion
	}
	return 0
}

func (x *ActorEndpointManifestSigningInput) GetActiveEndpoints() []*ActorEndpointManifestEntry {
	if x != nil {
		return x.ActiveEndpoints
	}
	return nil
}

func (x *ActorEndpointManifestSigningInput) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *ActorEndpointManifestSigningInput) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *ActorEndpointManifestSigningInput) GetSigningKeyId() string {
	if x != nil {
		return x.SigningKeyId
	}
	return ""
}

func (x *ActorEndpointManifestSigningInput) GetActorIdentityPublicKey() []byte {
	if x != nil {
		return x.ActorIdentityPublicKey
	}
	return nil
}

func (x *ActorEndpointManifestSigningInput) GetActorProfileVersion() uint64 {
	if x != nil {
		return x.ActorProfileVersion
	}
	return 0
}

type ActorEndpointManifest struct {
	state                  protoimpl.MessageState        `protogen:"open.v1"`
	FormatVersion          uint32                        `protobuf:"varint,1,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`
	ManifestId             string                        `protobuf:"bytes,2,opt,name=manifest_id,json=manifestId,proto3" json:"manifest_id,omitempty"`
	Actor                  *ActorRef                     `protobuf:"bytes,3,opt,name=actor,proto3" json:"actor,omitempty"`
	HomeStationPeerId      string                        `protobuf:"bytes,4,opt,name=home_station_peer_id,json=homeStationPeerId,proto3" json:"home_station_peer_id,omitempty"`
	DirectoryVersion       uint64                        `protobuf:"varint,5,opt,name=directory_version,json=directoryVersion,proto3" json:"directory_version,omitempty"`
	ActiveEndpoints        []*ActorEndpointManifestEntry `protobuf:"bytes,6,rep,name=active_endpoints,json=activeEndpoints,proto3" json:"active_endpoints,omitempty"`
	IssuedAt               *timestamppb.Timestamp        `protobuf:"bytes,7,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	ExpiresAt              *timestamppb.Timestamp        `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	SigningKeyId           string                        `protobuf:"bytes,9,opt,name=signing_key_id,json=signingKeyId,proto3" json:"signing_key_id,omitempty"`
	StationSignature       []byte                        `protobuf:"bytes,10,opt,name=station_signature,json=stationSignature,proto3" json:"station_signature,omitempty"`
	ActorIdentityPublicKey []byte                        `protobuf:"bytes,11,opt,name=actor_identity_public_key,json=actorIdentityPublicKey,proto3" json:"actor_identity_public_key,omitempty"`
	ActorProfileVersion    uint64                        `protobuf:"varint,12,opt,name=actor_profile_version,json=actorProfileVersion,proto3" json:"actor_profile_version,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ActorEndpointManifest) Reset() {
	*x = ActorEndpointManifest{}
	mi := &file_domain_actor_actor_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorEndpointManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorEndpointManifest) ProtoMessage() {}

func (x *ActorEndpointManifest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_actor_actor_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorEndpointManifest.ProtoReflect.Descriptor instead.
func (*ActorEndpointManifest) Descriptor() ([]byte, []int) {
	return file_domain_actor_actor_proto_rawDescGZIP(), []int{12}
}

func (x *ActorEndpointManifest) GetFormatVersion() uint32 {
	if x != nil {
		return x.FormatVersion
	}
	return 0
}

func (x *ActorEndpointManifest) GetManifestId() string {
	if x != nil {
		return x.ManifestId
	}
	return ""
}

func (x *ActorEndpointManifest) GetActor() *ActorRef {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *ActorEndpointManifest) GetHomeStationPeerId() string {
	if x != nil {
		return x.HomeStationPeerId
	}
	return ""
}

func (x *ActorEndpointManifest) GetDirectoryVersion() uint64 {
	if x != nil {
		return x.DirectoryVersion
	}
	return 0
}

func (x *ActorEndpointManifest) GetActiveEndpoints() []*ActorEndpointManifestEntry {
	if x != nil {
		return x.ActiveEndpoints
	}
	return nil
}

func (x *ActorEndpointManifest) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *ActorEndpointManifest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *ActorEndpointManifest) GetSigningKeyId() string {
	if x != nil {
		return x.SigningKeyId
	}
	return ""
}

func (x *ActorEndpointManifest) GetStationSignature() []byte {
	if x != nil {
		return x.StationSignature
	}
	return nil
}

func (x *ActorEndpointManifest) GetActorIdentityPublicKey() []byte {
	if x != nil {
		return x.ActorIdentityPublicKey
	}
	return nil
}

func (x *ActorEndpointManifest) GetActorProfileVersion() uint64 {
	if x != nil {
		return x.ActorProfileVersion
	}
	return 0
}

type GetActorEndpointManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *ActorRef              `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActorEndpointManifestRequest) Reset() {
	*x = GetActorEndpointManifestRequest{}
	mi := &file_domain_actor_actor_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActorEndpointManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActorEndpointManifestRequest) ProtoMessage() {}

func (x *GetActorEndpointManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_actor_actor_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActorEndpointManifestRequest.ProtoReflect.Descriptor instead.
func (*GetActorEndpointManifestRequest) Descriptor() ([]byte, []int) {
	return file_domain_actor_actor_proto_rawDescGZIP(), []int{13}
}

func (x *GetActorEndpointManifestRequest) GetActor() *ActorRef {
	if x != nil {
		return x.Actor
	}
	return nil
}

type GetActorEndpointManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      *ActorEndpointManifest `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActorEndpointManifestResponse) Reset() {
	*x = GetActorEndpointManifestResponse{}
	mi := &file_domain_actor_actor_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActorEndpointManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActorEndpointManifestResponse) ProtoMessage() {}

func (x *GetActorEndpointManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_actor_actor_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActorEndpointManifestResponse.ProtoReflect.Descriptor instead.
func (*GetActorEndpointManifestResponse) Descriptor() ([]byte, []int) {
	return file_domain_actor_actor_proto_rawDescGZIP(), []int{14}
}

func (x *GetActorEndpointManifestResponse) GetManifest() *ActorEndpointManifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

type Actor struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Username    string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	DisplayName string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Email       string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Inbox       string                 `protobuf:"bytes,5,opt,name=inbox,proto3" json:"inbox,omitempty"`
	Outbox      string                 `protobuf:"bytes,6,opt,name=outbox,proto3" json:"outbox,omitempty"`
	Endpoints   map[string]string      `protobuf:"bytes,7,rep,name=endpoints,proto3" json:"endpoints,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IsFollowing bool                   `protobuf:"varint,8,opt,name=is_following,proto3" json:"is_following,omitempty"`
	Avatar      string                 `protobuf:"bytes,10,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Kind        ActorKind              `protobuf:"varint,11,opt,name=kind,proto3,enum=peers_touch.model.actor.v1.ActorKind" json:"kind,omitempty"`
	// Federation extension fields. Populated for every actor row regardless of
	// origin. For ACTOR_ORIGIN_LOCAL the home_station_* fields describe the
	// current station; for ACTOR_ORIGIN_REMOTE_CACHED they describe the
	// authoritative station that issued the locator record.
	FederatedHandle   string          `protobuf:"bytes,12,opt,name=federated_handle,proto3" json:"federated_handle,omitempty"`         // e.g. "@alice@station-1.example"
	HomeStationPeerId string          `protobuf:"bytes,13,opt,name=home_station_peer_id,proto3" json:"home_station_peer_id,omitempty"` // libp2p PeerID of the home station
	HomeStationDomain string          `protobuf:"bytes,14,opt,name=home_station_domain,proto3" json:"home_station_domain,omitempty"`   // DNS-style domain of the home station
	Visibility        ActorVisibility `protobuf:"varint,15,opt,name=visibility,proto3,enum=peers_touch.model.actor.v1.ActorVisibility" json:"visibility,omitempty"`
	Origin            ActorOrigin     `protobuf:"varint,16,opt,name=origin,proto3,enum=peers_touch.model.actor.v1.ActorOrigin" json:"origin,omitempty"`
	// Ed25519 public key for actor-initiated governance signing.
	// Generated at account creation; used to verify actor_signature on ledger events.
	SigningPublicKey []byte    `protobuf:"bytes,17,opt,name=signing_public_key,proto3" json:"signing_public_key,omitempty"`
	Ref              *ActorRef `protobuf:"bytes,18,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Actor) Reset() {
	*x = Actor{}
	mi := &file_domain_actor_actor_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Actor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Actor) ProtoMessage() {}

func (x *Actor) ProtoReflect() protoreflect.Message {
	mi := &file_domain_actor_actor_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Actor.ProtoReflect.Descriptor instead.
func (*Actor) Descriptor() ([]byte, []int) {
	return file_domain_actor_actor_proto_rawDescGZIP(), []int{15}
}

func (x *Actor) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Actor) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Actor) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Actor) GetInbox() string {
	if x != nil {
		return x.Inbox
	}
	return ""
}

func (x *Actor) GetOutbox() string {
	if x != nil {
		return x.Outbox
	}
	return ""
}

func (x *Actor) GetEndpoints() map[string]string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *Actor) GetIsFollowing() bool {
	if x != nil {
		return x.IsFollowing
	}
	return false
}

func (x *Actor) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Actor) GetKind() ActorKind {
	if x != nil {
		return x.Kind
	}
	return ActorKind_ACTOR_KIND_UNSPECIFIED
}

func (x *Actor) GetFederatedHandle() string {
	if x != nil {
		return x.FederatedHandle
	}
	return ""
}

func (x *Actor) GetHomeStationPeerId() string {
	if x != nil {
		return x.HomeStationPeerId
	}
	return ""
}

func (x *Actor) GetHomeStationDomain() string {
	if x != nil {
		return x.HomeStationDomain
	}
	return ""
}

func (x *Actor) GetVisibility() ActorVisibility {
	if x != nil {
		return x.Visibility
	}
	return ActorVisibility_ACTOR_VISIBILITY_UNSPECIFIED
}

func (x *Actor) GetOrigin() ActorOrigin {
	if x != nil {
		return x.Origin
	}
	return ActorOrigin_ACTOR_ORIGIN_UNSPECIFIED
}

func (x *Actor) GetSigningPublicKey() []byte {
	if x != nil {
		return x.SigningPublicKey
	}
	return nil
}

func (x *Actor) GetRef() *ActorRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

// Identity-owned device signing-key projection used to verify actor-signed
// federated commands. Consumers must not accept a key supplied by the command
// being verified.
type VerifiedActorDeviceSigningKey struct {
	state              protoimpl.MessageState            `protogen:"open.v1"`
	ActorPtid          string                            `protobuf:"bytes,1,opt,name=actor_ptid,json=actorPtid,proto3" json:"actor_ptid,omitempty"`
	ActorDeviceId      string                            `protobuf:"bytes,2,opt,name=actor_device_id,json=actorDeviceId,proto3" json:"actor_device_id,omitempty"`
	HomeStationPeerId  string                            `protobuf:"bytes,3,opt,name=home_station_peer_id,json=homeStationPeerId,proto3" json:"home_station_peer_id,omitempty"`
	SigningKeyId       string                            `protobuf:"bytes,4,opt,name=signing_key_id,json=signingKeyId,proto3" json:"signing_key_id,omitempty"`
	Ed25519PublicKey   []byte                            `protobuf:"bytes,5,opt,name=ed25519_public_key,json=ed25519PublicKey,proto3" json:"ed25519_public_key,omitempty"`
	ProfileVersion     int64                             `protobuf:"varint,6,opt,name=profile_version,json=profileVersion,proto3" json:"profile_version,omitempty"`
	VerificationSource ActorSigningKeyVerificationSource `protobuf:"varint,7,opt,name=verification_source,json=verificationSource,proto3,enum=peers_touch.model.actor.v1.ActorSigningKeyVerificationSource" json:"verification_source,omitempty"`
	ValidFromUnixMs    int64                             `protobuf:"varint,8,opt,name=valid_from_unix_ms,json=validFromUnixMs,proto3" json:"valid_from_unix_ms,omitempty"`
	RevokedAtUnixMs    int64                             `protobuf:"varint,9,opt,name=revoked_at_unix_ms,json=revokedAtUnixMs,proto3" json:"revoked_at_unix_ms,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *VerifiedActorDeviceSigningKey) Reset() {
	*x = VerifiedActorDeviceSigningKey{}
	mi := &file_domain_actor_actor_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifiedActorDeviceSigningKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifiedActorDeviceSigningKey) ProtoMessage() {}

func (x *VerifiedActorDeviceSigningKey) ProtoReflect() protoreflect.Message {
	mi := &file_domain_actor_actor_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifiedActorDeviceSigningKey.ProtoReflect.Descriptor instead.
func (*VerifiedActorDeviceSigningKey) Descriptor() ([]byte, []int) {
	return file_domain_actor_actor_proto_rawDescGZIP(), []int{16}
}

func (x *VerifiedActorDeviceSigningKey) GetActorPtid() string {
	if x != nil {
		return x.ActorPtid
	}
	return ""
}

func (x *VerifiedActorDeviceSigningKey) GetActorDeviceId() string {
	if x != nil {
		return x.ActorDeviceId
	}
	return ""
}

func (x *VerifiedActorDeviceSigningKey) GetHomeStationPeerId() string {
	if x != nil {
		return x.HomeStationPeerId
	}
	return ""
}

func (x *VerifiedActorDeviceSigningKey) GetSigningKeyId() string {
	if x != nil {
		return x.SigningKeyId
	}
	return ""
}

func (x *VerifiedActorDeviceSigningKey) GetEd25519PublicKey() []byte {
	if x != nil {
		return x.Ed25519PublicKey
	}
	return nil
}

func (x *VerifiedActorDeviceSigningKey) GetProfileVersion() int64 {
	if x != nil {
		return x.ProfileVersion
	}
	return 0
}

func (x *VerifiedActorDeviceSigningKey) GetVerificationSource() ActorSigningKeyVerificationSource {
	if x != nil {
		return x.VerificationSource
	}
	return ActorSigningKeyVerificationSource_ACTOR_SIGNING_KEY_VERIFICATION_SOURCE_UNSPECIFIED
}

func (x *VerifiedActorDeviceSigningKey) GetValidFromUnixMs() int64 {
	if x != nil {
		return x.ValidFromUnixMs
	}
	return 0
}

func (x *VerifiedActorDeviceSigningKey) GetRevokedAtUnixMs() int64 {
	if x != nil {
		return x.RevokedAtUnixMs
	}
	return 0
}

type UserLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLink) Reset() {
	*x = UserLink{}
	mi := &file_domain_actor_actor_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLink) ProtoMessage() {}

func (x *UserLink) ProtoReflect() protoreflect.Message {
	mi := &file_domain_actor_actor_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLink.ProtoReflect.Descriptor instead.
func (*UserLink) Descriptor() ([]byte, []int) {
	return file_domain_actor_actor_proto_rawDescGZIP(), []int{17}
}

func (x *UserLink) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *UserLink) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type PeersTouchInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkId     string                 `protobuf:"bytes,1,opt,name=network_id,proto3" json:"network_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeersTouchInfo) Reset() {
	*x = PeersTouchInfo{}
	mi := &file_domain_actor_actor_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeersTouchInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeersTouchInfo) ProtoMessage() {}

func (x *PeersTouchInfo) ProtoReflect() protoreflect.Message {
	mi := &file_domain_actor_actor_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeersTouchInfo.ProtoReflect.Descriptor instead.
func (*PeersTouchInfo) Descriptor() ([]byte, []int) {
	return file_domain_actor_actor_proto_rawDescGZIP(), []int{18}
}

func (x *PeersTouchInfo) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

type ActorProfile struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Id                        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName               string                 `protobuf:"bytes,2,opt,name=display_name,proto3" json:"display_name,omitempty"`
	Username                  string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Note                      string                 `protobuf:"bytes,4,opt,name=note,proto3" json:"note,omitempty"`
	Avatar                    string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Header                    string                 `protobuf:"bytes,6,opt,name=header,proto3" json:"header,omitempty"`
	Region                    string                 `protobuf:"bytes,7,opt,name=region,proto3" json:"region,omitempty"`
	Timezone                  string                 `protobuf:"bytes,8,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Tags                      []string               `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	Links                     []*UserLink            `protobuf:"bytes,10,rep,name=links,proto3" json:"links,omitempty"`
	Url                       string                 `protobuf:"bytes,11,opt,name=url,proto3" json:"url,omitempty"`
	ServerDomain              string                 `protobuf:"bytes,12,opt,name=server_domain,proto3" json:"server_domain,omitempty"`
	KeyFingerprint            string                 `protobuf:"bytes,13,opt,name=key_fingerprint,proto3" json:"key_fingerprint,omitempty"`
	Verifications             []string               `protobuf:"bytes,14,rep,name=verifications,proto3" json:"verifications,omitempty"`
	PeersTouch                *PeersTouchInfo        `protobuf:"bytes,15,opt,name=peers_touch,proto3" json:"peers_touch,omitempty"`
	Acct                      string                 `protobuf:"bytes,16,opt,name=acct,proto3" json:"acct,omitempty"`
	Locked                    bool                   `protobuf:"varint,17,opt,name=locked,proto3" json:"locked,omitempty"`
	CreatedAt                 string                 `protobuf:"bytes,18,opt,name=created_at,proto3" json:"created_at,omitempty"`
	FollowersCount            int64                  `protobuf:"varint,19,opt,name=followers_count,proto3" json:"followers_count,omitempty"`
	FollowingCount            int64                  `protobuf:"varint,20,opt,name=following_count,proto3" json:"following_count,omitempty"`
	StatusesCount             int64                  `protobuf:"varint,21,opt,name=statuses_count,proto3" json:"statuses_count,omitempty"`
	ShowCounts                bool                   `protobuf:"varint,22,opt,name=show_counts,proto3" json:"show_counts,omitempty"`
	Moments                   []string               `protobuf:"bytes,23,rep,name=moments,proto3" json:"moments,omitempty"`
	DefaultVisibility         string                 `protobuf:"bytes,24,opt,name=default_visibility,proto3" json:"default_visibility,omitempty"`
	ManuallyApprovesFollowers bool                   `protobuf:"varint,25,opt,name=manually_approves_followers,proto3" json:"manually_approves_followers,omitempty"`
	MessagePermission         string                 `protobuf:"bytes,26,opt,name=message_permission,proto3" json:"message_permission,omitempty"`
	AutoExpireDays            int32                  `protobuf:"varint,27,opt,name=auto_expire_days,proto3" json:"auto_expire_days,omitempty"`
	Ref                       *ActorRef              `protobuf:"bytes,28,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ActorProfile) Reset() {
	*x = ActorProfile{}
	mi := &file_domain_actor_actor_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorProfile) ProtoMessage() {}

func (x *ActorProfile) ProtoReflect() protoreflect.Message {
	mi := &file_domain_actor_actor_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorProfile.ProtoReflect.Descriptor instead.
func (*ActorProfile) Descriptor() ([]byte, []int) {
	return file_domain_actor_actor_proto_rawDescGZIP(), []int{19}
}

func (x *ActorProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ActorProfile) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ActorProfile) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ActorProfile) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *ActorProfile) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *ActorProfile) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *ActorProfile) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ActorProfile) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *ActorProfile) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ActorProfile) GetLinks() []*UserLink {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *ActorProfile) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ActorProfile) GetServerDomain() string {
	if x != nil {
		return x.ServerDomain
	}
	return ""
}

func (x *ActorProfile) GetKeyFingerprint() string {
	if x != nil {
		return x.KeyFingerprint
	}
	return ""
}

func (x *ActorProfile) GetVerifications() []string {
	if x != nil {
		return x.Verifications
	}
	return nil
}

func (x *ActorProfile) GetPeersTouch() *PeersTouchInfo {
	if x != nil {
		return x.PeersTouch
	}
	return nil
}

func (x *ActorProfile) GetAcct() string {
	if x != nil {
		return x.Acct
	}
	return ""
}

func (x *ActorProfile) GetLocked() bool {
	if x != nil {
		return x.Locked
	}
	return false
}

func (x *ActorProfile) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ActorProfile) GetFollowersCount() int64 {
	if x != nil {
		return x.FollowersCount
	}
	return 0
}

func (x *ActorProfile) GetFollowingCount() int64 {
	if x != nil {
		return x.FollowingCount
	}
	return 0
}

func (x *ActorProfile) GetStatusesCount() int64 {
	if x != nil {
		return x.StatusesCount
	}
	return 0
}

func (x *ActorProfile) GetShowCounts() bool {
	if x != nil {
		return x.ShowCounts
	}
	return false
}

func (x *ActorProfile) GetMoments() []string {
	if x != nil {
		return x.Moments
	}
	return nil
}

func (x *ActorProfile) GetDefaultVisibility() string {
	if x != nil {
		return x.DefaultVisibility
	}
	return ""
}

func (x *ActorProfile) GetManuallyApprovesFollowers() bool {
	if x != nil {
		return x.ManuallyApprovesFollowers
	}
	return false
}

func (x *ActorProfile) GetMessagePermission() string {
	if x != nil {
		return x.MessagePermission
	}
	return ""
}

func (x *ActorProfile) GetAutoExpireDays() int32 {
	if x != nil {
		return x.AutoExpireDays
	}
	return 0
}

func (x *ActorProfile) GetRef() *ActorRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

type UpdateProfileRequest struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	DisplayName               *string                `protobuf:"bytes,1,opt,name=display_name,proto3,oneof" json:"display_name,omitempty"`
	Note                      *string                `protobuf:"bytes,2,opt,name=note,proto3,oneof" json:"note,omitempty"`
	Avatar                    *string                `protobuf:"bytes,3,opt,name=avatar,proto3,oneof" json:"avatar,omitempty"`
	Header                    *string                `protobuf:"bytes,4,opt,name=header,proto3,oneof" json:"header,omitempty"`
	Region                    *string                `protobuf:"bytes,5,opt,name=region,proto3,oneof" json:"region,omitempty"`
	Timezone                  *string                `protobuf:"bytes,6,opt,name=timezone,proto3,oneof" json:"timezone,omitempty"`
	Tags                      []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	Links                     []*UserLink            `protobuf:"bytes,8,rep,name=links,proto3" json:"links,omitempty"`
	DefaultVisibility         *string                `protobuf:"bytes,9,opt,name=default_visibility,proto3,oneof" json:"default_visibility,omitempty"`
	ManuallyApprovesFollowers *bool                  `protobuf:"varint,10,opt,name=manually_approves_followers,proto3,oneof" json:"manually_approves_followers,omitempty"`
	MessagePermission         *string                `protobuf:"bytes,11,opt,name=message_permission,proto3,oneof" json:"message_permission,omitempty"`
	AutoExpireDays            *int32                 `protobuf:"varint,12,opt,name=auto_expire_days,proto3,oneof" json:"auto_expire_days,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_domain_actor_actor_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_actor_actor_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_domain_actor_actor_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateProfileRequest) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *UpdateProfileRequest) GetNote() string {
	if x != nil && x.Note != nil {
		return *x.Note
	}
	return ""
}

func (x *UpdateProfileRequest) GetAvatar() string {
	if x != nil && x.Avatar != nil {
		return *x.Avatar
	}
	return ""
}

func (x *UpdateProfileRequest) GetHeader() string {
	if x != nil && x.Header != nil {
		return *x.Header
	}
	return ""
}

func (x *UpdateProfileRequest) GetRegion() string {
	if x != nil && x.Region != nil {
		return *x.Region
	}
	return ""
}

func (x *UpdateProfileRequest) GetTimezone() string {
	if x != nil && x.Timezone != nil {
		return *x.Timezone
	}
	return ""
}

func (x *UpdateProfileRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateProfileRequest) GetLinks() []*UserLink {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *UpdateProfileRequest) GetDefaultVisibility() string {
	if x != nil && x.DefaultVisibility != nil {
		return *x.DefaultVisibility
	}
	return ""
}

func (x *UpdateProfileRequest) GetManuallyApprovesFollowers() bool {
	if x != nil && x.ManuallyApprovesFollowers != nil {
		return *x.ManuallyApprovesFollowers
	}
	return false
}

func (x *UpdateProfileRequest) GetMessagePermission() string {
	if x != nil && x.MessagePermission != nil {
		return *x.MessagePermission
	}
	return ""
}

func (x *UpdateProfileRequest) GetAutoExpireDays() int32 {
	if x != nil && x.AutoExpireDays != nil {
		return *x.AutoExpireDays
	}
	return 0
}

type ActorList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Actor               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorList) Reset() {
	*x = ActorList{}
	mi := &file_domain_actor_actor_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorList) ProtoMessage() {}

func (x *ActorList) ProtoReflect() protoreflect.Message {
	mi := &file_domain_actor_actor_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorList.ProtoReflect.Descriptor instead.
func (*ActorList) Descriptor() ([]byte, []int) {
	return file_domain_actor_actor_proto_rawDescGZIP(), []int{21}
}

func (x *ActorList) GetItems() []*Actor {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ActorList) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// SearchUsersRequest carries query parameters for the user search endpoint.
type SearchUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Q             string                 `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersRequest) Reset() {
	*x = SearchUsersRequest{}
	mi := &file_domain_actor_actor_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersRequest) ProtoMessage() {}

func (x *SearchUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_actor_actor_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersRequest.ProtoReflect.Descriptor instead.
func (*SearchUsersRequest) Descriptor() ([]byte, []int) {
	return file_domain_actor_actor_proto_rawDescGZIP(), []int{22}
}

func (x *SearchUsersRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

// GetMeRequest is intentionally empty; the current user is identified via JWT auth context.
type GetMeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeRequest) Reset() {
	*x = GetMeRequest{}
	mi := &file_domain_actor_actor_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeRequest) ProtoMessage() {}

func (x *GetMeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_actor_actor_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeRequest.ProtoReflect.Descriptor instead.
func (*GetMeRequest) Descriptor() ([]byte, []int) {
	return file_domain_actor_actor_proto_rawDescGZIP(), []int{23}
}

var File_domain_actor_actor_proto protoreflect.FileDescriptor

const file_domain_actor_actor_proto_rawDesc = "" +
	"\n" +
	"\x18domain/actor/actor.proto\x12\x1apeers_touch.model.actor.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"}\n" +
	"\bActorRef\x12\x12\n" +
	"\x04ptid\x18\x02 \x01(\tR\x04ptid\x12\x12\n" +
	"\x04acct\x18\x03 \x01(\tR\x04acct\x129\n" +
	"\x04kind\x18\x04 \x01(\x0e2%.peers_touch.model.actor.v1.ActorKindR\x04kindJ\x04\b\x01\x10\x02R\bactor_id\"i\n" +
	"\x0eActorDeviceRef\x12:\n" +
	"\x05actor\x18\x01 \x01(\v2$.peers_touch.model.actor.v1.ActorRefR\x05actor\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\"\x9e\x03\n" +
	"\x16ActorDeviceCertificate\x12%\n" +
	"\x0eformat_version\x18\x01 \x01(\rR\rformatVersion\x12B\n" +
	"\x06device\x18\x02 \x01(\v2*.peers_touch.model.actor.v1.ActorDeviceRefR\x06device\x129\n" +
	"\x19actor_identity_public_key\x18\x03 \x01(\fR\x16actorIdentityPublicKey\x12C\n" +
	"\x1eactor_identity_key_fingerprint\x18\x04 \x01(\fR\x1bactorIdentityKeyFingerprint\x129\n" +
	"\x19device_signing_public_key\x18\x05 \x01(\fR\x16deviceSigningPublicKey\x12$\n" +
	"\x0esigning_key_id\x18\x06 \x01(\tR\fsigningKeyId\x128\n" +
	"\x18observed_profile_version\x18\a \x01(\x04R\x16observedProfileVersion\"\xa0\x04\n" +
	"\vActorDevice\x12<\n" +
	"\x03ref\x18\x01 \x01(\v2*.peers_touch.model.actor.v1.ActorDeviceRefR\x03ref\x12E\n" +
	"\x06status\x18\x02 \x01(\x0e2-.peers_touch.model.actor.v1.ActorDeviceStatusR\x06status\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12C\n" +
	"\x1eactor_identity_key_fingerprint\x18\x04 \x01(\fR\x1bactorIdentityKeyFingerprint\x12$\n" +
	"\x0esigning_key_id\x18\x05 \x01(\tR\fsigningKeyId\x129\n" +
	"\x19device_signing_public_key\x18\x06 \x01(\fR\x16deviceSigningPublicKey\x12'\n" +
	"\x0fprofile_version\x18\a \x01(\x04R\x0eprofileVersion\x12/\n" +
	"\x13activation_sequence\x18\b \x01(\x03R\x12activationSequence\x12;\n" +
	"\venrolled_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"enrolledAt\x129\n" +
	"\n" +
	"revoked_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\trevokedAt\"\xba\x01\n" +
	"\x18EnrollActorDeviceRequest\x12T\n" +
	"\vcertificate\x18\x01 \x01(\v22.peers_touch.model.actor.v1.ActorDeviceCertificateR\vcertificate\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x122\n" +
	"\x15actor_cross_signature\x18\x03 \x01(\fR\x13actorCrossSignature\"\\\n" +
	"\x19EnrollActorDeviceResponse\x12?\n" +
	"\x06device\x18\x01 \x01(\v2'.peers_touch.model.actor.v1.ActorDeviceR\x06device\"\x19\n" +
	"\x17ListActorDevicesRequest\"]\n" +
	"\x18ListActorDevicesResponse\x12A\n" +
	"\adevices\x18\x01 \x03(\v2'.peers_touch.model.actor.v1.ActorDeviceR\adevices\"q\n" +
	"\x18RevokeActorDeviceRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x128\n" +
	"\x18observed_profile_version\x18\x02 \x01(\x04R\x16observedProfileVersion\"\\\n" +
	"\x19RevokeActorDeviceResponse\x12?\n" +
	"\x06device\x18\x01 \x01(\v2'.peers_touch.model.actor.v1.ActorDeviceR\x06device\"\xc0\x01\n" +
	"\x1aActorEndpointManifestEntry\x12F\n" +
	"\bendpoint\x18\x01 \x01(\v2*.peers_touch.model.actor.v1.ActorDeviceRefR\bendpoint\x12$\n" +
	"\x0esigning_key_id\x18\x02 \x01(\tR\fsigningKeyId\x124\n" +
	"\x16public_material_sha256\x18\x03 \x03(\fR\x14publicMaterialSha256\"\xf1\x04\n" +
	"!ActorEndpointManifestSigningInput\x12%\n" +
	"\x0eformat_version\x18\x01 \x01(\rR\rformatVersion\x12\x1f\n" +
	"\vmanifest_id\x18\x02 \x01(\tR\n" +
	"manifestId\x12:\n" +
	"\x05actor\x18\x03 \x01(\v2$.peers_touch.model.actor.v1.ActorRefR\x05actor\x12/\n" +
	"\x14home_station_peer_id\x18\x04 \x01(\tR\x11homeStationPeerId\x12+\n" +
	"\x11directory_version\x18\x05 \x01(\x04R\x10directoryVersion\x12a\n" +
	"\x10active_endpoints\x18\x06 \x03(\v26.peers_touch.model.actor.v1.ActorEndpointManifestEntryR\x0factiveEndpoints\x127\n" +
	"\tissued_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x129\n" +
	"\n" +
	"expires_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12$\n" +
	"\x0esigning_key_id\x18\t \x01(\tR\fsigningKeyId\x129\n" +
	"\x19actor_identity_public_key\x18\n" +
	" \x01(\fR\x16actorIdentityPublicKey\x122\n" +
	"\x15actor_profile_version\x18\v \x01(\x04R\x13actorProfileVersion\"\x92\x05\n" +
	"\x15ActorEndpointManifest\x12%\n" +
	"\x0eformat_version\x18\x01 \x01(\rR\rformatVersion\x12\x1f\n" +
	"\vmanifest_id\x18\x02 \x01(\tR\n" +
	"manifestId\x12:\n" +
	"\x05actor\x18\x03 \x01(\v2$.peers_touch.model.actor.v1.ActorRefR\x05actor\x12/\n" +
	"\x14home_station_peer_id\x18\x04 \x01(\tR\x11homeStationPeerId\x12+\n" +
	"\x11directory_version\x18\x05 \x01(\x04R\x10directoryVersion\x12a\n" +
	"\x10active_endpoints\x18\x06 \x03(\v26.peers_touch.model.actor.v1.ActorEndpointManifestEntryR\x0factiveEndpoints\x127\n" +
	"\tissued_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x129\n" +
	"\n" +
	"expires_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12$\n" +
	"\x0esigning_key_id\x18\t \x01(\tR\fsigningKeyId\x12+\n" +
	"\x11station_signature\x18\n" +
	" \x01(\fR\x10stationSignature\x129\n" +
	"\x19actor_identity_public_key\x18\v \x01(\fR\x16actorIdentityPublicKey\x122\n" +
	"\x15actor_profile_version\x18\f \x01(\x04R\x13actorProfileVersion\"]\n" +
	"\x1fGetActorEndpointManifestRequest\x12:\n" +
	"\x05actor\x18\x01 \x01(\v2$.peers_touch.model.actor.v1.ActorRefR\x05actor\"q\n" +
	" GetActorEndpointManifestResponse\x12M\n" +
	"\bmanifest\x18\x01 \x01(\v21.peers_touch.model.actor.v1.ActorEndpointManifestR\bmanifest\"\xb1\x06\n" +
	"\x05Actor\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x14\n" +
	"\x05inbox\x18\x05 \x01(\tR\x05inbox\x12\x16\n" +
	"\x06outbox\x18\x06 \x01(\tR\x06outbox\x12N\n" +
	"\tendpoints\x18\a \x03(\v20.peers_touch.model.actor.v1.Actor.EndpointsEntryR\tendpoints\x12\"\n" +
	"\fis_following\x18\b \x01(\bR\fis_following\x12\x16\n" +
	"\x06avatar\x18\n" +
	" \x01(\tR\x06avatar\x129\n" +
	"\x04kind\x18\v \x01(\x0e2%.peers_touch.model.actor.v1.ActorKindR\x04kind\x12*\n" +
	"\x10federated_handle\x18\f \x01(\tR\x10federated_handle\x122\n" +
	"\x14home_station_peer_id\x18\r \x01(\tR\x14home_station_peer_id\x120\n" +
	"\x13home_station_domain\x18\x0e \x01(\tR\x13home_station_domain\x12K\n" +
	"\n" +
	"visibility\x18\x0f \x01(\x0e2+.peers_touch.model.actor.v1.ActorVisibilityR\n" +
	"visibility\x12?\n" +
	"\x06origin\x18\x10 \x01(\x0e2'.peers_touch.model.actor.v1.ActorOriginR\x06origin\x12.\n" +
	"\x12signing_public_key\x18\x11 \x01(\fR\x12signing_public_key\x126\n" +
	"\x03ref\x18\x12 \x01(\v2$.peers_touch.model.actor.v1.ActorRefR\x03ref\x1a<\n" +
	"\x0eEndpointsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x01\x10\x02J\x04\b\t\x10\n" +
	"R\x02idR\bactor_id\"\xde\x03\n" +
	"\x1dVerifiedActorDeviceSigningKey\x12\x1d\n" +
	"\n" +
	"actor_ptid\x18\x01 \x01(\tR\tactorPtid\x12&\n" +
	"\x0factor_device_id\x18\x02 \x01(\tR\ractorDeviceId\x12/\n" +
	"\x14home_station_peer_id\x18\x03 \x01(\tR\x11homeStationPeerId\x12$\n" +
	"\x0esigning_key_id\x18\x04 \x01(\tR\fsigningKeyId\x12,\n" +
	"\x12ed25519_public_key\x18\x05 \x01(\fR\x10ed25519PublicKey\x12'\n" +
	"\x0fprofile_version\x18\x06 \x01(\x03R\x0eprofileVersion\x12n\n" +
	"\x13verification_source\x18\a \x01(\x0e2=.peers_touch.model.actor.v1.ActorSigningKeyVerificationSourceR\x12verificationSource\x12+\n" +
	"\x12valid_from_unix_ms\x18\b \x01(\x03R\x0fvalidFromUnixMs\x12+\n" +
	"\x12revoked_at_unix_ms\x18\t \x01(\x03R\x0frevokedAtUnixMs\"2\n" +
	"\bUserLink\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"0\n" +
	"\x0ePeersTouchInfo\x12\x1e\n" +
	"\n" +
	"network_id\x18\x01 \x01(\tR\n" +
	"network_id\"\x86\b\n" +
	"\fActorProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\fdisplay_name\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x12\n" +
	"\x04note\x18\x04 \x01(\tR\x04note\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\x12\x16\n" +
	"\x06header\x18\x06 \x01(\tR\x06header\x12\x16\n" +
	"\x06region\x18\a \x01(\tR\x06region\x12\x1a\n" +
	"\btimezone\x18\b \x01(\tR\btimezone\x12\x12\n" +
	"\x04tags\x18\t \x03(\tR\x04tags\x12:\n" +
	"\x05links\x18\n" +
	" \x03(\v2$.peers_touch.model.actor.v1.UserLinkR\x05links\x12\x10\n" +
	"\x03url\x18\v \x01(\tR\x03url\x12$\n" +
	"\rserver_domain\x18\f \x01(\tR\rserver_domain\x12(\n" +
	"\x0fkey_fingerprint\x18\r \x01(\tR\x0fkey_fingerprint\x12$\n" +
	"\rverifications\x18\x0e \x03(\tR\rverifications\x12L\n" +
	"\vpeers_touch\x18\x0f \x01(\v2*.peers_touch.model.actor.v1.PeersTouchInfoR\vpeers_touch\x12\x12\n" +
	"\x04acct\x18\x10 \x01(\tR\x04acct\x12\x16\n" +
	"\x06locked\x18\x11 \x01(\bR\x06locked\x12\x1e\n" +
	"\n" +
	"created_at\x18\x12 \x01(\tR\n" +
	"created_at\x12(\n" +
	"\x0ffollowers_count\x18\x13 \x01(\x03R\x0ffollowers_count\x12(\n" +
	"\x0ffollowing_count\x18\x14 \x01(\x03R\x0ffollowing_count\x12&\n" +
	"\x0estatuses_count\x18\x15 \x01(\x03R\x0estatuses_count\x12 \n" +
	"\vshow_counts\x18\x16 \x01(\bR\vshow_counts\x12\x18\n" +
	"\amoments\x18\x17 \x03(\tR\amoments\x12.\n" +
	"\x12default_visibility\x18\x18 \x01(\tR\x12default_visibility\x12@\n" +
	"\x1bmanually_approves_followers\x18\x19 \x01(\bR\x1bmanually_approves_followers\x12.\n" +
	"\x12message_permission\x18\x1a \x01(\tR\x12message_permission\x12*\n" +
	"\x10auto_expire_days\x18\x1b \x01(\x05R\x10auto_expire_days\x126\n" +
	"\x03ref\x18\x1c \x01(\v2$.peers_touch.model.actor.v1.ActorRefR\x03ref\"\xad\x05\n" +
	"\x14UpdateProfileRequest\x12'\n" +
	"\fdisplay_name\x18\x01 \x01(\tH\x00R\fdisplay_name\x88\x01\x01\x12\x17\n" +
	"\x04note\x18\x02 \x01(\tH\x01R\x04note\x88\x01\x01\x12\x1b\n" +
	"\x06avatar\x18\x03 \x01(\tH\x02R\x06avatar\x88\x01\x01\x12\x1b\n" +
	"\x06header\x18\x04 \x01(\tH\x03R\x06header\x88\x01\x01\x12\x1b\n" +
	"\x06region\x18\x05 \x01(\tH\x04R\x06region\x88\x01\x01\x12\x1f\n" +
	"\btimezone\x18\x06 \x01(\tH\x05R\btimezone\x88\x01\x01\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x12:\n" +
	"\x05links\x18\b \x03(\v2$.peers_touch.model.actor.v1.UserLinkR\x05links\x123\n" +
	"\x12default_visibility\x18\t \x01(\tH\x06R\x12default_visibility\x88\x01\x01\x12E\n" +
	"\x1bmanually_approves_followers\x18\n" +
	" \x01(\bH\aR\x1bmanually_approves_followers\x88\x01\x01\x123\n" +
	"\x12message_permission\x18\v \x01(\tH\bR\x12message_permission\x88\x01\x01\x12/\n" +
	"\x10auto_expire_days\x18\f \x01(\x05H\tR\x10auto_expire_days\x88\x01\x01B\x0f\n" +
	"\r_display_nameB\a\n" +
	"\x05_noteB\t\n" +
	"\a_avatarB\t\n" +
	"\a_headerB\t\n" +
	"\a_regionB\v\n" +
	"\t_timezoneB\x15\n" +
	"\x13_default_visibilityB\x1e\n" +
	"\x1c_manually_approves_followersB\x15\n" +
	"\x13_message_permissionB\x13\n" +
	"\x11_auto_expire_days\"Z\n" +
	"\tActorList\x127\n" +
	"\x05items\x18\x01 \x03(\v2!.peers_touch.model.actor.v1.ActorR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\"\n" +
	"\x12SearchUsersRequest\x12\f\n" +
	"\x01q\x18\x01 \x01(\tR\x01q\"\x0e\n" +
	"\fGetMeRequest*\xba\x01\n" +
	"\tActorKind\x12\x1a\n" +
	"\x16ACTOR_KIND_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ACTOR_KIND_PERSON\x10\x01\x12\x14\n" +
	"\x10ACTOR_KIND_GROUP\x10\x02\x12\x1b\n" +
	"\x17ACTOR_KIND_ORGANIZATION\x10\x03\x12\x16\n" +
	"\x12ACTOR_KIND_SERVICE\x10\x04\x12\x1a\n" +
	"\x16ACTOR_KIND_APPLICATION\x10\x05\x12\x13\n" +
	"\x0fACTOR_KIND_NODE\x10\x06*c\n" +
	"\vActorOrigin\x12\x1c\n" +
	"\x18ACTOR_ORIGIN_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ACTOR_ORIGIN_LOCAL\x10\x01\x12\x1e\n" +
	"\x1aACTOR_ORIGIN_REMOTE_CACHED\x10\x02*\x8e\x01\n" +
	"\x0fActorVisibility\x12 \n" +
	"\x1cACTOR_VISIBILITY_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17ACTOR_VISIBILITY_HIDDEN\x10\x01\x12\x1e\n" +
	"\x1aACTOR_VISIBILITY_BY_HANDLE\x10\x02\x12\x1c\n" +
	"\x18ACTOR_VISIBILITY_INDEXED\x10\x03*\xc4\x01\n" +
	"\x11ActorDeviceStatus\x12#\n" +
	"\x1fACTOR_DEVICE_STATUS_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dACTOR_DEVICE_STATUS_ENROLLING\x10\x01\x12\x1e\n" +
	"\x1aACTOR_DEVICE_STATUS_ACTIVE\x10\x02\x12&\n" +
	"\"ACTOR_DEVICE_STATUS_REVOKE_PENDING\x10\x03\x12\x1f\n" +
	"\x1bACTOR_DEVICE_STATUS_REVOKED\x10\x04*\x97\x02\n" +
	"!ActorSigningKeyVerificationSource\x125\n" +
	"1ACTOR_SIGNING_KEY_VERIFICATION_SOURCE_UNSPECIFIED\x10\x00\x12C\n" +
	"?ACTOR_SIGNING_KEY_VERIFICATION_SOURCE_LOCAL_DEVICE_REGISTRATION\x10\x01\x12:\n" +
	"6ACTOR_SIGNING_KEY_VERIFICATION_SOURCE_VERIFIED_PROFILE\x10\x02\x12:\n" +
	"6ACTOR_SIGNING_KEY_VERIFICATION_SOURCE_VERIFIED_LOCATOR\x10\x03BCZAgithub.com/peers-labs/peers-touch/station/frame/touch/model;modelb\x06proto3"

var (
	file_domain_actor_actor_proto_rawDescOnce sync.Once
	file_domain_actor_actor_proto_rawDescData []byte
)

func file_domain_actor_actor_proto_rawDescGZIP() []byte {
	file_domain_actor_actor_proto_rawDescOnce.Do(func() {
		file_domain_actor_actor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_actor_actor_proto_rawDesc), len(file_domain_actor_actor_proto_rawDesc)))
	})
	return file_domain_actor_actor_proto_rawDescData
}

var file_domain_actor_actor_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_domain_actor_actor_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_domain_actor_actor_proto_goTypes = []any{
	(ActorKind)(0),                            // 0: peers_touch.model.actor.v1.ActorKind
	(ActorOrigin)(0),                          // 1: peers_touch.model.actor.v1.ActorOrigin
	(ActorVisibility)(0),                      // 2: peers_touch.model.actor.v1.ActorVisibility
	(ActorDeviceStatus)(0),                    // 3: peers_touch.model.actor.v1.ActorDeviceStatus
	(ActorSigningKeyVerificationSource)(0),    // 4: peers_touch.model.actor.v1.ActorSigningKeyVerificationSource
	(*ActorRef)(nil),                          // 5: peers_touch.model.actor.v1.ActorRef
	(*ActorDeviceRef)(nil),                    // 6: peers_touch.model.actor.v1.ActorDeviceRef
	(*ActorDeviceCertificate)(nil),            // 7: peers_touch.model.actor.v1.ActorDeviceCertificate
	(*ActorDevice)(nil),                       // 8: peers_touch.model.actor.v1.ActorDevice
	(*EnrollActorDeviceRequest)(nil),          // 9: peers_touch.model.actor.v1.EnrollActorDeviceRequest
	(*EnrollActorDeviceResponse)(nil),         // 10: peers_touch.model.actor.v1.EnrollActorDeviceResponse
	(*ListActorDevicesRequest)(nil),           // 11: peers_touch.model.actor.v1.ListActorDevicesRequest
	(*ListActorDevicesResponse)(nil),          // 12: peers_touch.model.actor.v1.ListActorDevicesResponse
	(*RevokeActorDeviceRequest)(nil),          // 13: peers_touch.model.actor.v1.RevokeActorDeviceRequest
	(*RevokeActorDeviceResponse)(nil),         // 14: peers_touch.model.actor.v1.RevokeActorDeviceResponse
	(*ActorEndpointManifestEntry)(nil),        // 15: peers_touch.model.actor.v1.ActorEndpointManifestEntry
	(*ActorEndpointManifestSigningInput)(nil), // 16: peers_touch.model.actor.v1.ActorEndpointManifestSigningInput
	(*ActorEndpointManifest)(nil),             // 17: peers_touch.model.actor.v1.ActorEndpointManifest
	(*GetActorEndpointManifestRequest)(nil),   // 18: peers_touch.model.actor.v1.GetActorEndpointManifestRequest
	(*GetActorEndpointManifestResponse)(nil),  // 19: peers_touch.model.actor.v1.GetActorEndpointManifestResponse
	(*Actor)(nil),                             // 20: peers_touch.model.actor.v1.Actor
	(*VerifiedActorDeviceSigningKey)(nil),     // 21: peers_touch.model.actor.v1.VerifiedActorDeviceSigningKey
	(*UserLink)(nil),                          // 22: peers_touch.model.actor.v1.UserLink
	(*PeersTouchInfo)(nil),                    // 23: peers_touch.model.actor.v1.PeersTouchInfo
	(*ActorProfile)(nil),                      // 24: peers_touch.model.actor.v1.ActorProfile
	(*UpdateProfileRequest)(nil),              // 25: peers_touch.model.actor.v1.UpdateProfileRequest
	(*ActorList)(nil),                         // 26: peers_touch.model.actor.v1.ActorList
	(*SearchUsersRequest)(nil),                // 27: peers_touch.model.actor.v1.SearchUsersRequest
	(*GetMeRequest)(nil),                      // 28: peers_touch.model.actor.v1.GetMeRequest
	nil,                                       // 29: peers_touch.model.actor.v1.Actor.EndpointsEntry
	(*timestamppb.Timestamp)(nil),             // 30: google.protobuf.Timestamp
}
var file_domain_actor_actor_proto_depIdxs = []int32{
	0,  // 0: peers_touch.model.actor.v1.ActorRef.kind:type_name -> peers_touch.model.actor.v1.ActorKind
	5,  // 1: peers_touch.model.actor.v1.ActorDeviceRef.actor:type_name -> peers_touch.model.actor.v1.ActorRef
	6,  // 2: peers_touch.model.actor.v1.ActorDeviceCertificate.device:type_name -> peers_touch.model.actor.v1.ActorDeviceRef
	6,  // 3: peers_touch.model.actor.v1.ActorDevice.ref:type_name -> peers_touch.model.actor.v1.ActorDeviceRef
	3,  // 4: peers_touch.model.actor.v1.ActorDevice.status:type_name -> peers_touch.model.actor.v1.ActorDeviceStatus
	30, // 5: peers_touch.model.actor.v1.ActorDevice.enrolled_at:type_name -> google.protobuf.Timestamp
	30, // 6: peers_touch.model.actor.v1.ActorDevice.revoked_at:type_name -> google.protobuf.Timestamp
	7,  // 7: peers_touch.model.actor.v1.EnrollActorDeviceRequest.certificate:type_name -> peers_touch.model.actor.v1.ActorDeviceCertificate
	8,  // 8: peers_touch.model.actor.v1.EnrollActorDeviceResponse.device:type_name -> peers_touch.model.actor.v1.ActorDevice
	8,  // 9: peers_touch.model.actor.v1.ListActorDevicesResponse.devices:type_name -> peers_touch.model.actor.v1.ActorDevice
	8,  // 10: peers_touch.model.actor.v1.RevokeActorDeviceResponse.device:type_name -> peers_touch.model.actor.v1.ActorDevice
	6,  // 11: peers_touch.model.actor.v1.ActorEndpointManifestEntry.endpoint:type_name -> peers_touch.model.actor.v1.ActorDeviceRef
	5,  // 12: peers_touch.model.actor.v1.ActorEndpointManifestSigningInput.actor:type_name -> peers_touch.model.actor.v1.ActorRef
	15, // 13: peers_touch.model.actor.v1.ActorEndpointManifestSigningInput.active_endpoints:type_name -> peers_touch.model.actor.v1.ActorEndpointManifestEntry
	30, // 14: peers_touch.model.actor.v1.ActorEndpointManifestSigningInput.issued_at:type_name -> google.protobuf.Timestamp
	30, // 15: peers_touch.model.actor.v1.ActorEndpointManifestSigningInput.expires_at:type_name -> google.protobuf.Timestamp
	5,  // 16: peers_touch.model.actor.v1.ActorEndpointManifest.actor:type_name -> peers_touch.model.actor.v1.ActorRef
	15, // 17: peers_touch.model.actor.v1.ActorEndpointManifest.active_endpoints:type_name -> peers_touch.model.actor.v1.ActorEndpointManifestEntry
	30, // 18: peers_touch.model.actor.v1.ActorEndpointManifest.issued_at:type_name -> google.protobuf.Timestamp
	30, // 19: peers_touch.model.actor.v1.ActorEndpointManifest.expires_at:type_name -> google.protobuf.Timestamp
	5,  // 20: peers_touch.model.actor.v1.GetActorEndpointManifestRequest.actor:type_name -> peers_touch.model.actor.v1.ActorRef
	17, // 21: peers_touch.model.actor.v1.GetActorEndpointManifestResponse.manifest:type_name -> peers_touch.model.actor.v1.ActorEndpointManifest
	29, // 22: peers_touch.model.actor.v1.Actor.endpoints:type_name -> peers_touch.model.actor.v1.Actor.EndpointsEntry
	0,  // 23: peers_touch.model.actor.v1.Actor.kind:type_name -> peers_touch.model.actor.v1.ActorKind
	2,  // 24: peers_touch.model.actor.v1.Actor.visibility:type_name -> peers_touch.model.actor.v1.ActorVisibility
	1,  // 25: peers_touch.model.actor.v1.Actor.origin:type_name -> peers_touch.model.actor.v1.ActorOrigin
	5,  // 26: peers_touch.model.actor.v1.Actor.ref:type_name -> peers_touch.model.actor.v1.ActorRef
	4,  // 27: peers_touch.model.actor.v1.VerifiedActorDeviceSigningKey.verification_source:type_name -> peers_touch.model.actor.v1.ActorSigningKeyVerificationSource
	22, // 28: peers_touch.model.actor.v1.ActorProfile.links:type_name -> peers_touch.model.actor.v1.UserLink
	23, // 29: peers_touch.model.actor.v1.ActorProfile.peers_touch:type_name -> peers_touch.model.actor.v1.PeersTouchInfo
	5,  // 30: peers_touch.model.actor.v1.ActorProfile.ref:type_name -> peers_touch.model.actor.v1.ActorRef
	22, // 31: peers_touch.model.actor.v1.UpdateProfileRequest.links:type_name -> peers_touch.model.actor.v1.UserLink
	20, // 32: peers_touch.model.actor.v1.ActorList.items:type_name -> peers_touch.model.actor.v1.Actor
	33, // [33:33] is the sub-list for method output_type
	33, // [33:33] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_domain_actor_actor_proto_init() }
func file_domain_actor_actor_proto_init() {
	if File_domain_actor_actor_proto != nil {
		return
	}
	file_domain_actor_actor_proto_msgTypes[20].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_actor_actor_proto_rawDesc), len(file_domain_actor_actor_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_actor_actor_proto_goTypes,
		DependencyIndexes: file_domain_actor_actor_proto_depIdxs,
		EnumInfos:         file_domain_actor_actor_proto_enumTypes,
		MessageInfos:      file_domain_actor_actor_proto_msgTypes,
	}.Build()
	File_domain_actor_actor_proto = out.File
	file_domain_actor_actor_proto_goTypes = nil
	file_domain_actor_actor_proto_depIdxs = nil
}
