// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: domain/oauth/oauth.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OAuthClient struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ClientId         string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecretHash string                 `protobuf:"bytes,4,opt,name=client_secret_hash,json=clientSecretHash,proto3" json:"client_secret_hash,omitempty"`
	RedirectUri      string                 `protobuf:"bytes,5,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	Scopes           string                 `protobuf:"bytes,6,opt,name=scopes,proto3" json:"scopes,omitempty"` // space-delimited
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OAuthClient) Reset() {
	*x = OAuthClient{}
	mi := &file_domain_oauth_oauth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuthClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuthClient) ProtoMessage() {}

func (x *OAuthClient) ProtoReflect() protoreflect.Message {
	mi := &file_domain_oauth_oauth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuthClient.ProtoReflect.Descriptor instead.
func (*OAuthClient) Descriptor() ([]byte, []int) {
	return file_domain_oauth_oauth_proto_rawDescGZIP(), []int{0}
}

func (x *OAuthClient) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OAuthClient) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OAuthClient) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *OAuthClient) GetClientSecretHash() string {
	if x != nil {
		return x.ClientSecretHash
	}
	return ""
}

func (x *OAuthClient) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

func (x *OAuthClient) GetScopes() string {
	if x != nil {
		return x.Scopes
	}
	return ""
}

func (x *OAuthClient) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type OAuthAuthCode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CodeHash      string                 `protobuf:"bytes,1,opt,name=code_hash,json=codeHash,proto3" json:"code_hash,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Scopes        string                 `protobuf:"bytes,4,opt,name=scopes,proto3" json:"scopes,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Used          bool                   `protobuf:"varint,6,opt,name=used,proto3" json:"used,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OAuthAuthCode) Reset() {
	*x = OAuthAuthCode{}
	mi := &file_domain_oauth_oauth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuthAuthCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuthAuthCode) ProtoMessage() {}

func (x *OAuthAuthCode) ProtoReflect() protoreflect.Message {
	mi := &file_domain_oauth_oauth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuthAuthCode.ProtoReflect.Descriptor instead.
func (*OAuthAuthCode) Descriptor() ([]byte, []int) {
	return file_domain_oauth_oauth_proto_rawDescGZIP(), []int{1}
}

func (x *OAuthAuthCode) GetCodeHash() string {
	if x != nil {
		return x.CodeHash
	}
	return ""
}

func (x *OAuthAuthCode) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *OAuthAuthCode) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OAuthAuthCode) GetScopes() string {
	if x != nil {
		return x.Scopes
	}
	return ""
}

func (x *OAuthAuthCode) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *OAuthAuthCode) GetUsed() bool {
	if x != nil {
		return x.Used
	}
	return false
}

type OAuthToken struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccessTokenHash  string                 `protobuf:"bytes,1,opt,name=access_token_hash,json=accessTokenHash,proto3" json:"access_token_hash,omitempty"`
	RefreshTokenHash string                 `protobuf:"bytes,2,opt,name=refresh_token_hash,json=refreshTokenHash,proto3" json:"refresh_token_hash,omitempty"`
	TokenType        string                 `protobuf:"bytes,3,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"` // Bearer
	Scope            string                 `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	UserId           string                 `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ClientId         string                 `protobuf:"bytes,6,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OAuthToken) Reset() {
	*x = OAuthToken{}
	mi := &file_domain_oauth_oauth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuthToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuthToken) ProtoMessage() {}

func (x *OAuthToken) ProtoReflect() protoreflect.Message {
	mi := &file_domain_oauth_oauth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuthToken.ProtoReflect.Descriptor instead.
func (*OAuthToken) Descriptor() ([]byte, []int) {
	return file_domain_oauth_oauth_proto_rawDescGZIP(), []int{2}
}

func (x *OAuthToken) GetAccessTokenHash() string {
	if x != nil {
		return x.AccessTokenHash
	}
	return ""
}

func (x *OAuthToken) GetRefreshTokenHash() string {
	if x != nil {
		return x.RefreshTokenHash
	}
	return ""
}

func (x *OAuthToken) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *OAuthToken) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *OAuthToken) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OAuthToken) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *OAuthToken) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *OAuthToken) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// OAuthBridgeRequest is the payload from the external OAuth gateway
// to Station for silent registration / login.
type OAuthBridgeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Provider       string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	ProviderUserId string                 `protobuf:"bytes,2,opt,name=provider_user_id,json=providerUserId,proto3" json:"provider_user_id,omitempty"`
	Email          string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Username       string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	DisplayName    string                 `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AvatarUrl      string                 `protobuf:"bytes,6,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Ts             string                 `protobuf:"bytes,7,opt,name=ts,proto3" json:"ts,omitempty"`   // RFC3339 timestamp for HMAC
	Sig            string                 `protobuf:"bytes,8,opt,name=sig,proto3" json:"sig,omitempty"` // HMAC-SHA256 hex signature
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OAuthBridgeRequest) Reset() {
	*x = OAuthBridgeRequest{}
	mi := &file_domain_oauth_oauth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuthBridgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuthBridgeRequest) ProtoMessage() {}

func (x *OAuthBridgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_oauth_oauth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuthBridgeRequest.ProtoReflect.Descriptor instead.
func (*OAuthBridgeRequest) Descriptor() ([]byte, []int) {
	return file_domain_oauth_oauth_proto_rawDescGZIP(), []int{3}
}

func (x *OAuthBridgeRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *OAuthBridgeRequest) GetProviderUserId() string {
	if x != nil {
		return x.ProviderUserId
	}
	return ""
}

func (x *OAuthBridgeRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *OAuthBridgeRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *OAuthBridgeRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *OAuthBridgeRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *OAuthBridgeRequest) GetTs() string {
	if x != nil {
		return x.Ts
	}
	return ""
}

func (x *OAuthBridgeRequest) GetSig() string {
	if x != nil {
		return x.Sig
	}
	return ""
}

type OAuthBridgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	TokenType     string                 `protobuf:"bytes,4,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	ActorId       string                 `protobuf:"bytes,6,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	ActorIdNum    int64                  `protobuf:"varint,7,opt,name=actor_id_num,json=actorIdNum,proto3" json:"actor_id_num,omitempty"`
	Username      string                 `protobuf:"bytes,8,opt,name=username,proto3" json:"username,omitempty"`
	DisplayName   string                 `protobuf:"bytes,9,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Email         string                 `protobuf:"bytes,10,opt,name=email,proto3" json:"email,omitempty"`
	ActorRef      *ActorRef              `protobuf:"bytes,11,opt,name=actor_ref,proto3" json:"actor_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OAuthBridgeResponse) Reset() {
	*x = OAuthBridgeResponse{}
	mi := &file_domain_oauth_oauth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuthBridgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuthBridgeResponse) ProtoMessage() {}

func (x *OAuthBridgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_oauth_oauth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuthBridgeResponse.ProtoReflect.Descriptor instead.
func (*OAuthBridgeResponse) Descriptor() ([]byte, []int) {
	return file_domain_oauth_oauth_proto_rawDescGZIP(), []int{4}
}

func (x *OAuthBridgeResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *OAuthBridgeResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *OAuthBridgeResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *OAuthBridgeResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *OAuthBridgeResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *OAuthBridgeResponse) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *OAuthBridgeResponse) GetActorIdNum() int64 {
	if x != nil {
		return x.ActorIdNum
	}
	return 0
}

func (x *OAuthBridgeResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *OAuthBridgeResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *OAuthBridgeResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *OAuthBridgeResponse) GetActorRef() *ActorRef {
	if x != nil {
		return x.ActorRef
	}
	return nil
}

var File_domain_oauth_oauth_proto protoreflect.FileDescriptor

const file_domain_oauth_oauth_proto_rawDesc = "" +
	"\n" +
	"\x18domain/oauth/oauth.proto\x12\x1apeers_touch.model.oauth.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18domain/actor/actor.proto\"\xf2\x01\n" +
	"\vOAuthClient\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x12,\n" +
	"\x12client_secret_hash\x18\x04 \x01(\tR\x10clientSecretHash\x12!\n" +
	"\fredirect_uri\x18\x05 \x01(\tR\vredirectUri\x12\x16\n" +
	"\x06scopes\x18\x06 \x01(\tR\x06scopes\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xc9\x01\n" +
	"\rOAuthAuthCode\x12\x1b\n" +
	"\tcode_hash\x18\x01 \x01(\tR\bcodeHash\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x16\n" +
	"\x06scopes\x18\x04 \x01(\tR\x06scopes\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x12\n" +
	"\x04used\x18\x06 \x01(\bR\x04used\"\xc7\x02\n" +
	"\n" +
	"OAuthToken\x12*\n" +
	"\x11access_token_hash\x18\x01 \x01(\tR\x0faccessTokenHash\x12,\n" +
	"\x12refresh_token_hash\x18\x02 \x01(\tR\x10refreshTokenHash\x12\x1d\n" +
	"\n" +
	"token_type\x18\x03 \x01(\tR\ttokenType\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\x12\x1b\n" +
	"\tclient_id\x18\x06 \x01(\tR\bclientId\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expires_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xf0\x01\n" +
	"\x12OAuthBridgeRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12(\n" +
	"\x10provider_user_id\x18\x02 \x01(\tR\x0eproviderUserId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12!\n" +
	"\fdisplay_name\x18\x05 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x06 \x01(\tR\tavatarUrl\x12\x0e\n" +
	"\x02ts\x18\a \x01(\tR\x02ts\x12\x10\n" +
	"\x03sig\x18\b \x01(\tR\x03sig\"\x90\x03\n" +
	"\x13OAuthBridgeResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\x04 \x01(\tR\ttokenType\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\tR\texpiresAt\x12\x19\n" +
	"\bactor_id\x18\x06 \x01(\tR\aactorId\x12 \n" +
	"\factor_id_num\x18\a \x01(\x03R\n" +
	"actorIdNum\x12\x1a\n" +
	"\busername\x18\b \x01(\tR\busername\x12!\n" +
	"\fdisplay_name\x18\t \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05email\x18\n" +
	" \x01(\tR\x05email\x12B\n" +
	"\tactor_ref\x18\v \x01(\v2$.peers_touch.model.actor.v1.ActorRefR\tactor_refBCZAgithub.com/peers-labs/peers-touch/station/frame/touch/model;modelb\x06proto3"

var (
	file_domain_oauth_oauth_proto_rawDescOnce sync.Once
	file_domain_oauth_oauth_proto_rawDescData []byte
)

func file_domain_oauth_oauth_proto_rawDescGZIP() []byte {
	file_domain_oauth_oauth_proto_rawDescOnce.Do(func() {
		file_domain_oauth_oauth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_oauth_oauth_proto_rawDesc), len(file_domain_oauth_oauth_proto_rawDesc)))
	})
	return file_domain_oauth_oauth_proto_rawDescData
}

var file_domain_oauth_oauth_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_domain_oauth_oauth_proto_goTypes = []any{
	(*OAuthClient)(nil),           // 0: peers_touch.model.oauth.v1.OAuthClient
	(*OAuthAuthCode)(nil),         // 1: peers_touch.model.oauth.v1.OAuthAuthCode
	(*OAuthToken)(nil),            // 2: peers_touch.model.oauth.v1.OAuthToken
	(*OAuthBridgeRequest)(nil),    // 3: peers_touch.model.oauth.v1.OAuthBridgeRequest
	(*OAuthBridgeResponse)(nil),   // 4: peers_touch.model.oauth.v1.OAuthBridgeResponse
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*ActorRef)(nil),              // 6: peers_touch.model.actor.v1.ActorRef
}
var file_domain_oauth_oauth_proto_depIdxs = []int32{
	5, // 0: peers_touch.model.oauth.v1.OAuthClient.created_at:type_name -> google.protobuf.Timestamp
	5, // 1: peers_touch.model.oauth.v1.OAuthAuthCode.expires_at:type_name -> google.protobuf.Timestamp
	5, // 2: peers_touch.model.oauth.v1.OAuthToken.created_at:type_name -> google.protobuf.Timestamp
	5, // 3: peers_touch.model.oauth.v1.OAuthToken.expires_at:type_name -> google.protobuf.Timestamp
	6, // 4: peers_touch.model.oauth.v1.OAuthBridgeResponse.actor_ref:type_name -> peers_touch.model.actor.v1.ActorRef
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_domain_oauth_oauth_proto_init() }
func file_domain_oauth_oauth_proto_init() {
	if File_domain_oauth_oauth_proto != nil {
		return
	}
	file_domain_actor_actor_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_oauth_oauth_proto_rawDesc), len(file_domain_oauth_oauth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_oauth_oauth_proto_goTypes,
		DependencyIndexes: file_domain_oauth_oauth_proto_depIdxs,
		MessageInfos:      file_domain_oauth_oauth_proto_msgTypes,
	}.Build()
	File_domain_oauth_oauth_proto = out.File
	file_domain_oauth_oauth_proto_goTypes = nil
	file_domain_oauth_oauth_proto_depIdxs = nil
}
