// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: domain/secure_content/content.proto

package securecontent

import (
	model "github.com/peers-labs/peers-touch/station/frame/touch/model"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SecureContentOwnerDomain int32

const (
	SecureContentOwnerDomain_SECURE_CONTENT_OWNER_DOMAIN_UNSPECIFIED  SecureContentOwnerDomain = 0
	SecureContentOwnerDomain_SECURE_CONTENT_OWNER_DOMAIN_CONVERSATION SecureContentOwnerDomain = 1
	SecureContentOwnerDomain_SECURE_CONTENT_OWNER_DOMAIN_SOCIAL       SecureContentOwnerDomain = 2
)

// Enum value maps for SecureContentOwnerDomain.
var (
	SecureContentOwnerDomain_name = map[int32]string{
		0: "SECURE_CONTENT_OWNER_DOMAIN_UNSPECIFIED",
		1: "SECURE_CONTENT_OWNER_DOMAIN_CONVERSATION",
		2: "SECURE_CONTENT_OWNER_DOMAIN_SOCIAL",
	}
	SecureContentOwnerDomain_value = map[string]int32{
		"SECURE_CONTENT_OWNER_DOMAIN_UNSPECIFIED":  0,
		"SECURE_CONTENT_OWNER_DOMAIN_CONVERSATION": 1,
		"SECURE_CONTENT_OWNER_DOMAIN_SOCIAL":       2,
	}
)

func (x SecureContentOwnerDomain) Enum() *SecureContentOwnerDomain {
	p := new(SecureContentOwnerDomain)
	*p = x
	return p
}

func (x SecureContentOwnerDomain) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecureContentOwnerDomain) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_secure_content_content_proto_enumTypes[0].Descriptor()
}

func (SecureContentOwnerDomain) Type() protoreflect.EnumType {
	return &file_domain_secure_content_content_proto_enumTypes[0]
}

func (x SecureContentOwnerDomain) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SecureContentOwnerDomain.Descriptor instead.
func (SecureContentOwnerDomain) EnumDescriptor() ([]byte, []int) {
	return file_domain_secure_content_content_proto_rawDescGZIP(), []int{0}
}

type PayloadEncryptionSuite int32

const (
	PayloadEncryptionSuite_PAYLOAD_ENCRYPTION_SUITE_UNSPECIFIED PayloadEncryptionSuite = 0
	PayloadEncryptionSuite_PAYLOAD_ENCRYPTION_SUITE_AES_256_GCM PayloadEncryptionSuite = 1
)

// Enum value maps for PayloadEncryptionSuite.
var (
	PayloadEncryptionSuite_name = map[int32]string{
		0: "PAYLOAD_ENCRYPTION_SUITE_UNSPECIFIED",
		1: "PAYLOAD_ENCRYPTION_SUITE_AES_256_GCM",
	}
	PayloadEncryptionSuite_value = map[string]int32{
		"PAYLOAD_ENCRYPTION_SUITE_UNSPECIFIED": 0,
		"PAYLOAD_ENCRYPTION_SUITE_AES_256_GCM": 1,
	}
)

func (x PayloadEncryptionSuite) Enum() *PayloadEncryptionSuite {
	p := new(PayloadEncryptionSuite)
	*p = x
	return p
}

func (x PayloadEncryptionSuite) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayloadEncryptionSuite) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_secure_content_content_proto_enumTypes[1].Descriptor()
}

func (PayloadEncryptionSuite) Type() protoreflect.EnumType {
	return &file_domain_secure_content_content_proto_enumTypes[1]
}

func (x PayloadEncryptionSuite) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayloadEncryptionSuite.Descriptor instead.
func (PayloadEncryptionSuite) EnumDescriptor() ([]byte, []int) {
	return file_domain_secure_content_content_proto_rawDescGZIP(), []int{1}
}

type ContentPreKeyKind int32

const (
	ContentPreKeyKind_CONTENT_PREKEY_KIND_UNSPECIFIED    ContentPreKeyKind = 0
	ContentPreKeyKind_CONTENT_PREKEY_KIND_ENDPOINT       ContentPreKeyKind = 1
	ContentPreKeyKind_CONTENT_PREKEY_KIND_ACTOR_RECOVERY ContentPreKeyKind = 2
)

// Enum value maps for ContentPreKeyKind.
var (
	ContentPreKeyKind_name = map[int32]string{
		0: "CONTENT_PREKEY_KIND_UNSPECIFIED",
		1: "CONTENT_PREKEY_KIND_ENDPOINT",
		2: "CONTENT_PREKEY_KIND_ACTOR_RECOVERY",
	}
	ContentPreKeyKind_value = map[string]int32{
		"CONTENT_PREKEY_KIND_UNSPECIFIED":    0,
		"CONTENT_PREKEY_KIND_ENDPOINT":       1,
		"CONTENT_PREKEY_KIND_ACTOR_RECOVERY": 2,
	}
)

func (x ContentPreKeyKind) Enum() *ContentPreKeyKind {
	p := new(ContentPreKeyKind)
	*p = x
	return p
}

func (x ContentPreKeyKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContentPreKeyKind) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_secure_content_content_proto_enumTypes[2].Descriptor()
}

func (ContentPreKeyKind) Type() protoreflect.EnumType {
	return &file_domain_secure_content_content_proto_enumTypes[2]
}

func (x ContentPreKeyKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContentPreKeyKind.Descriptor instead.
func (ContentPreKeyKind) EnumDescriptor() ([]byte, []int) {
	return file_domain_secure_content_content_proto_rawDescGZIP(), []int{2}
}

type SecureResourceRef struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	OwnerDomain   SecureContentOwnerDomain `protobuf:"varint,1,opt,name=owner_domain,json=ownerDomain,proto3,enum=peers_touch.model.secure_content.v1.SecureContentOwnerDomain" json:"owner_domain,omitempty"`
	ContentId     string                   `protobuf:"bytes,2,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	Generation    uint64                   `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecureResourceRef) Reset() {
	*x = SecureResourceRef{}
	mi := &file_domain_secure_content_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecureResourceRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecureResourceRef) ProtoMessage() {}

func (x *SecureResourceRef) ProtoReflect() protoreflect.Message {
	mi := &file_domain_secure_content_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecureResourceRef.ProtoReflect.Descriptor instead.
func (*SecureResourceRef) Descriptor() ([]byte, []int) {
	return file_domain_secure_content_content_proto_rawDescGZIP(), []int{0}
}

func (x *SecureResourceRef) GetOwnerDomain() SecureContentOwnerDomain {
	if x != nil {
		return x.OwnerDomain
	}
	return SecureContentOwnerDomain_SECURE_CONTENT_OWNER_DOMAIN_UNSPECIFIED
}

func (x *SecureResourceRef) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *SecureResourceRef) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

type EncryptedPayload struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FormatVersion    uint32                 `protobuf:"varint,1,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`
	Resource         *SecureResourceRef     `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Suite            PayloadEncryptionSuite `protobuf:"varint,3,opt,name=suite,proto3,enum=peers_touch.model.secure_content.v1.PayloadEncryptionSuite" json:"suite,omitempty"`
	Nonce            []byte                 `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Ciphertext       []byte                 `protobuf:"bytes,5,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	CiphertextSha256 []byte                 `protobuf:"bytes,6,opt,name=ciphertext_sha256,json=ciphertextSha256,proto3" json:"ciphertext_sha256,omitempty"`
	AadSha256        []byte                 `protobuf:"bytes,7,opt,name=aad_sha256,json=aadSha256,proto3" json:"aad_sha256,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EncryptedPayload) Reset() {
	*x = EncryptedPayload{}
	mi := &file_domain_secure_content_content_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedPayload) ProtoMessage() {}

func (x *EncryptedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_domain_secure_content_content_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedPayload.ProtoReflect.Descriptor instead.
func (*EncryptedPayload) Descriptor() ([]byte, []int) {
	return file_domain_secure_content_content_proto_rawDescGZIP(), []int{1}
}

func (x *EncryptedPayload) GetFormatVersion() uint32 {
	if x != nil {
		return x.FormatVersion
	}
	return 0
}

func (x *EncryptedPayload) GetResource() *SecureResourceRef {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *EncryptedPayload) GetSuite() PayloadEncryptionSuite {
	if x != nil {
		return x.Suite
	}
	return PayloadEncryptionSuite_PAYLOAD_ENCRYPTION_SUITE_UNSPECIFIED
}

func (x *EncryptedPayload) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *EncryptedPayload) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *EncryptedPayload) GetCiphertextSha256() []byte {
	if x != nil {
		return x.CiphertextSha256
	}
	return nil
}

func (x *EncryptedPayload) GetAadSha256() []byte {
	if x != nil {
		return x.AadSha256
	}
	return nil
}

type RequiredContentRecipientSlot struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	RecipientSlotId        string                 `protobuf:"bytes,1,opt,name=recipient_slot_id,json=recipientSlotId,proto3" json:"recipient_slot_id,omitempty"`
	KeyKind                ContentPreKeyKind      `protobuf:"varint,2,opt,name=key_kind,json=keyKind,proto3,enum=peers_touch.model.secure_content.v1.ContentPreKeyKind" json:"key_kind,omitempty"`
	OneTimeKeyId           string                 `protobuf:"bytes,3,opt,name=one_time_key_id,json=oneTimeKeyId,proto3" json:"one_time_key_id,omitempty"`
	OneTimePublicKey       []byte                 `protobuf:"bytes,4,opt,name=one_time_public_key,json=oneTimePublicKey,proto3" json:"one_time_public_key,omitempty"`
	PrincipalBindingSha256 []byte                 `protobuf:"bytes,5,opt,name=principal_binding_sha256,json=principalBindingSha256,proto3" json:"principal_binding_sha256,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RequiredContentRecipientSlot) Reset() {
	*x = RequiredContentRecipientSlot{}
	mi := &file_domain_secure_content_content_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequiredContentRecipientSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequiredContentRecipientSlot) ProtoMessage() {}

func (x *RequiredContentRecipientSlot) ProtoReflect() protoreflect.Message {
	mi := &file_domain_secure_content_content_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequiredContentRecipientSlot.ProtoReflect.Descriptor instead.
func (*RequiredContentRecipientSlot) Descriptor() ([]byte, []int) {
	return file_domain_secure_content_content_proto_rawDescGZIP(), []int{2}
}

func (x *RequiredContentRecipientSlot) GetRecipientSlotId() string {
	if x != nil {
		return x.RecipientSlotId
	}
	return ""
}

func (x *RequiredContentRecipientSlot) GetKeyKind() ContentPreKeyKind {
	if x != nil {
		return x.KeyKind
	}
	return ContentPreKeyKind_CONTENT_PREKEY_KIND_UNSPECIFIED
}

func (x *RequiredContentRecipientSlot) GetOneTimeKeyId() string {
	if x != nil {
		return x.OneTimeKeyId
	}
	return ""
}

func (x *RequiredContentRecipientSlot) GetOneTimePublicKey() []byte {
	if x != nil {
		return x.OneTimePublicKey
	}
	return nil
}

func (x *RequiredContentRecipientSlot) GetPrincipalBindingSha256() []byte {
	if x != nil {
		return x.PrincipalBindingSha256
	}
	return nil
}

type ContentEncryptionPlan struct {
	state                       protoimpl.MessageState          `protogen:"open.v1"`
	FormatVersion               uint32                          `protobuf:"varint,1,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`
	PlanId                      string                          `protobuf:"bytes,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	Resource                    *SecureResourceRef              `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	Author                      *model.ActorDeviceRef           `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	AuthorizationSnapshotSha256 []byte                          `protobuf:"bytes,5,opt,name=authorization_snapshot_sha256,json=authorizationSnapshotSha256,proto3" json:"authorization_snapshot_sha256,omitempty"`
	RequiredSlots               []*RequiredContentRecipientSlot `protobuf:"bytes,6,rep,name=required_slots,json=requiredSlots,proto3" json:"required_slots,omitempty"`
	ObjectIds                   []string                        `protobuf:"bytes,7,rep,name=object_ids,json=objectIds,proto3" json:"object_ids,omitempty"`
	ExpiresAt                   *timestamppb.Timestamp          `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CanonicalPlanSha256         []byte                          `protobuf:"bytes,9,opt,name=canonical_plan_sha256,json=canonicalPlanSha256,proto3" json:"canonical_plan_sha256,omitempty"`
	StationSigningKeyId         string                          `protobuf:"bytes,10,opt,name=station_signing_key_id,json=stationSigningKeyId,proto3" json:"station_signing_key_id,omitempty"`
	StationSignature            []byte                          `protobuf:"bytes,11,opt,name=station_signature,json=stationSignature,proto3" json:"station_signature,omitempty"`
	DomainBindingSha256         []byte                          `protobuf:"bytes,12,opt,name=domain_binding_sha256,json=domainBindingSha256,proto3" json:"domain_binding_sha256,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *ContentEncryptionPlan) Reset() {
	*x = ContentEncryptionPlan{}
	mi := &file_domain_secure_content_content_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentEncryptionPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentEncryptionPlan) ProtoMessage() {}

func (x *ContentEncryptionPlan) ProtoReflect() protoreflect.Message {
	mi := &file_domain_secure_content_content_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentEncryptionPlan.ProtoReflect.Descriptor instead.
func (*ContentEncryptionPlan) Descriptor() ([]byte, []int) {
	return file_domain_secure_content_content_proto_rawDescGZIP(), []int{3}
}

func (x *ContentEncryptionPlan) GetFormatVersion() uint32 {
	if x != nil {
		return x.FormatVersion
	}
	return 0
}

func (x *ContentEncryptionPlan) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *ContentEncryptionPlan) GetResource() *SecureResourceRef {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *ContentEncryptionPlan) GetAuthor() *model.ActorDeviceRef {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *ContentEncryptionPlan) GetAuthorizationSnapshotSha256() []byte {
	if x != nil {
		return x.AuthorizationSnapshotSha256
	}
	return nil
}

func (x *ContentEncryptionPlan) GetRequiredSlots() []*RequiredContentRecipientSlot {
	if x != nil {
		return x.RequiredSlots
	}
	return nil
}

func (x *ContentEncryptionPlan) GetObjectIds() []string {
	if x != nil {
		return x.ObjectIds
	}
	return nil
}

func (x *ContentEncryptionPlan) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *ContentEncryptionPlan) GetCanonicalPlanSha256() []byte {
	if x != nil {
		return x.CanonicalPlanSha256
	}
	return nil
}

func (x *ContentEncryptionPlan) GetStationSigningKeyId() string {
	if x != nil {
		return x.StationSigningKeyId
	}
	return ""
}

func (x *ContentEncryptionPlan) GetStationSignature() []byte {
	if x != nil {
		return x.StationSignature
	}
	return nil
}

func (x *ContentEncryptionPlan) GetDomainBindingSha256() []byte {
	if x != nil {
		return x.DomainBindingSha256
	}
	return nil
}

type ContentKeyEnvelopeBinding struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	FormatVersion               uint32                 `protobuf:"varint,1,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`
	PlanId                      string                 `protobuf:"bytes,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	CanonicalPlanSha256         []byte                 `protobuf:"bytes,3,opt,name=canonical_plan_sha256,json=canonicalPlanSha256,proto3" json:"canonical_plan_sha256,omitempty"`
	Resource                    *SecureResourceRef     `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`
	RecipientSlotId             string                 `protobuf:"bytes,5,opt,name=recipient_slot_id,json=recipientSlotId,proto3" json:"recipient_slot_id,omitempty"`
	RecipientKeyKind            ContentPreKeyKind      `protobuf:"varint,6,opt,name=recipient_key_kind,json=recipientKeyKind,proto3,enum=peers_touch.model.secure_content.v1.ContentPreKeyKind" json:"recipient_key_kind,omitempty"`
	RecipientKeyId              string                 `protobuf:"bytes,7,opt,name=recipient_key_id,json=recipientKeyId,proto3" json:"recipient_key_id,omitempty"`
	PrincipalBindingSha256      []byte                 `protobuf:"bytes,8,opt,name=principal_binding_sha256,json=principalBindingSha256,proto3" json:"principal_binding_sha256,omitempty"`
	AuthorizationSnapshotSha256 []byte                 `protobuf:"bytes,9,opt,name=authorization_snapshot_sha256,json=authorizationSnapshotSha256,proto3" json:"authorization_snapshot_sha256,omitempty"`
	PayloadCiphertextSha256     []byte                 `protobuf:"bytes,10,opt,name=payload_ciphertext_sha256,json=payloadCiphertextSha256,proto3" json:"payload_ciphertext_sha256,omitempty"`
	ObjectDescriptorSetSha256   []byte                 `protobuf:"bytes,11,opt,name=object_descriptor_set_sha256,json=objectDescriptorSetSha256,proto3" json:"object_descriptor_set_sha256,omitempty"`
	PlanExpiresAt               *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=plan_expires_at,json=planExpiresAt,proto3" json:"plan_expires_at,omitempty"`
	Sender                      *model.ActorDeviceRef  `protobuf:"bytes,13,opt,name=sender,proto3" json:"sender,omitempty"`
	SenderSigningKeyId          string                 `protobuf:"bytes,14,opt,name=sender_signing_key_id,json=senderSigningKeyId,proto3" json:"sender_signing_key_id,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *ContentKeyEnvelopeBinding) Reset() {
	*x = ContentKeyEnvelopeBinding{}
	mi := &file_domain_secure_content_content_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentKeyEnvelopeBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentKeyEnvelopeBinding) ProtoMessage() {}

func (x *ContentKeyEnvelopeBinding) ProtoReflect() protoreflect.Message {
	mi := &file_domain_secure_content_content_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentKeyEnvelopeBinding.ProtoReflect.Descriptor instead.
func (*ContentKeyEnvelopeBinding) Descriptor() ([]byte, []int) {
	return file_domain_secure_content_content_proto_rawDescGZIP(), []int{4}
}

func (x *ContentKeyEnvelopeBinding) GetFormatVersion() uint32 {
	if x != nil {
		return x.FormatVersion
	}
	return 0
}

func (x *ContentKeyEnvelopeBinding) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *ContentKeyEnvelopeBinding) GetCanonicalPlanSha256() []byte {
	if x != nil {
		return x.CanonicalPlanSha256
	}
	return nil
}

func (x *ContentKeyEnvelopeBinding) GetResource() *SecureResourceRef {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *ContentKeyEnvelopeBinding) GetRecipientSlotId() string {
	if x != nil {
		return x.RecipientSlotId
	}
	return ""
}

func (x *ContentKeyEnvelopeBinding) GetRecipientKeyKind() ContentPreKeyKind {
	if x != nil {
		return x.RecipientKeyKind
	}
	return ContentPreKeyKind_CONTENT_PREKEY_KIND_UNSPECIFIED
}

func (x *ContentKeyEnvelopeBinding) GetRecipientKeyId() string {
	if x != nil {
		return x.RecipientKeyId
	}
	return ""
}

func (x *ContentKeyEnvelopeBinding) GetPrincipalBindingSha256() []byte {
	if x != nil {
		return x.PrincipalBindingSha256
	}
	return nil
}

func (x *ContentKeyEnvelopeBinding) GetAuthorizationSnapshotSha256() []byte {
	if x != nil {
		return x.AuthorizationSnapshotSha256
	}
	return nil
}

func (x *ContentKeyEnvelopeBinding) GetPayloadCiphertextSha256() []byte {
	if x != nil {
		return x.PayloadCiphertextSha256
	}
	return nil
}

func (x *ContentKeyEnvelopeBinding) GetObjectDescriptorSetSha256() []byte {
	if x != nil {
		return x.ObjectDescriptorSetSha256
	}
	return nil
}

func (x *ContentKeyEnvelopeBinding) GetPlanExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PlanExpiresAt
	}
	return nil
}

func (x *ContentKeyEnvelopeBinding) GetSender() *model.ActorDeviceRef {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *ContentKeyEnvelopeBinding) GetSenderSigningKeyId() string {
	if x != nil {
		return x.SenderSigningKeyId
	}
	return ""
}

type PreparedContentKeyEnvelope struct {
	state               protoimpl.MessageState     `protogen:"open.v1"`
	Binding             *ContentKeyEnvelopeBinding `protobuf:"bytes,1,opt,name=binding,proto3" json:"binding,omitempty"`
	BindingSha256       []byte                     `protobuf:"bytes,2,opt,name=binding_sha256,json=bindingSha256,proto3" json:"binding_sha256,omitempty"`
	HpkeEncapsulatedKey []byte                     `protobuf:"bytes,3,opt,name=hpke_encapsulated_key,json=hpkeEncapsulatedKey,proto3" json:"hpke_encapsulated_key,omitempty"`
	HpkeCiphertext      []byte                     `protobuf:"bytes,4,opt,name=hpke_ciphertext,json=hpkeCiphertext,proto3" json:"hpke_ciphertext,omitempty"`
	SenderSignature     []byte                     `protobuf:"bytes,5,opt,name=sender_signature,json=senderSignature,proto3" json:"sender_signature,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PreparedContentKeyEnvelope) Reset() {
	*x = PreparedContentKeyEnvelope{}
	mi := &file_domain_secure_content_content_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreparedContentKeyEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreparedContentKeyEnvelope) ProtoMessage() {}

func (x *PreparedContentKeyEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_domain_secure_content_content_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreparedContentKeyEnvelope.ProtoReflect.Descriptor instead.
func (*PreparedContentKeyEnvelope) Descriptor() ([]byte, []int) {
	return file_domain_secure_content_content_proto_rawDescGZIP(), []int{5}
}

func (x *PreparedContentKeyEnvelope) GetBinding() *ContentKeyEnvelopeBinding {
	if x != nil {
		return x.Binding
	}
	return nil
}

func (x *PreparedContentKeyEnvelope) GetBindingSha256() []byte {
	if x != nil {
		return x.BindingSha256
	}
	return nil
}

func (x *PreparedContentKeyEnvelope) GetHpkeEncapsulatedKey() []byte {
	if x != nil {
		return x.HpkeEncapsulatedKey
	}
	return nil
}

func (x *PreparedContentKeyEnvelope) GetHpkeCiphertext() []byte {
	if x != nil {
		return x.HpkeCiphertext
	}
	return nil
}

func (x *PreparedContentKeyEnvelope) GetSenderSignature() []byte {
	if x != nil {
		return x.SenderSignature
	}
	return nil
}

type ViewerContentKeyEnvelope struct {
	state   protoimpl.MessageState     `protogen:"open.v1"`
	Binding *ContentKeyEnvelopeBinding `protobuf:"bytes,1,opt,name=binding,proto3" json:"binding,omitempty"`
	// Types that are valid to be assigned to Recipient:
	//
	//	*ViewerContentKeyEnvelope_Endpoint
	//	*ViewerContentKeyEnvelope_RecoveryActor
	Recipient           isViewerContentKeyEnvelope_Recipient `protobuf_oneof:"recipient"`
	BindingSha256       []byte                               `protobuf:"bytes,4,opt,name=binding_sha256,json=bindingSha256,proto3" json:"binding_sha256,omitempty"`
	HpkeEncapsulatedKey []byte                               `protobuf:"bytes,5,opt,name=hpke_encapsulated_key,json=hpkeEncapsulatedKey,proto3" json:"hpke_encapsulated_key,omitempty"`
	HpkeCiphertext      []byte                               `protobuf:"bytes,6,opt,name=hpke_ciphertext,json=hpkeCiphertext,proto3" json:"hpke_ciphertext,omitempty"`
	SenderSignature     []byte                               `protobuf:"bytes,7,opt,name=sender_signature,json=senderSignature,proto3" json:"sender_signature,omitempty"`
	PrincipalEpoch      uint64                               `protobuf:"varint,8,opt,name=principal_epoch,json=principalEpoch,proto3" json:"principal_epoch,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ViewerContentKeyEnvelope) Reset() {
	*x = ViewerContentKeyEnvelope{}
	mi := &file_domain_secure_content_content_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewerContentKeyEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewerContentKeyEnvelope) ProtoMessage() {}

func (x *ViewerContentKeyEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_domain_secure_content_content_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewerContentKeyEnvelope.ProtoReflect.Descriptor instead.
func (*ViewerContentKeyEnvelope) Descriptor() ([]byte, []int) {
	return file_domain_secure_content_content_proto_rawDescGZIP(), []int{6}
}

func (x *ViewerContentKeyEnvelope) GetBinding() *ContentKeyEnvelopeBinding {
	if x != nil {
		return x.Binding
	}
	return nil
}

func (x *ViewerContentKeyEnvelope) GetRecipient() isViewerContentKeyEnvelope_Recipient {
	if x != nil {
		return x.Recipient
	}
	return nil
}

func (x *ViewerContentKeyEnvelope) GetEndpoint() *model.ActorDeviceRef {
	if x != nil {
		if x, ok := x.Recipient.(*ViewerContentKeyEnvelope_Endpoint); ok {
			return x.Endpoint
		}
	}
	return nil
}

func (x *ViewerContentKeyEnvelope) GetRecoveryActor() *model.ActorRef {
	if x != nil {
		if x, ok := x.Recipient.(*ViewerContentKeyEnvelope_RecoveryActor); ok {
			return x.RecoveryActor
		}
	}
	return nil
}

func (x *ViewerContentKeyEnvelope) GetBindingSha256() []byte {
	if x != nil {
		return x.BindingSha256
	}
	return nil
}

func (x *ViewerContentKeyEnvelope) GetHpkeEncapsulatedKey() []byte {
	if x != nil {
		return x.HpkeEncapsulatedKey
	}
	return nil
}

func (x *ViewerContentKeyEnvelope) GetHpkeCiphertext() []byte {
	if x != nil {
		return x.HpkeCiphertext
	}
	return nil
}

func (x *ViewerContentKeyEnvelope) GetSenderSignature() []byte {
	if x != nil {
		return x.SenderSignature
	}
	return nil
}

func (x *ViewerContentKeyEnvelope) GetPrincipalEpoch() uint64 {
	if x != nil {
		return x.PrincipalEpoch
	}
	return 0
}

type isViewerContentKeyEnvelope_Recipient interface {
	isViewerContentKeyEnvelope_Recipient()
}

type ViewerContentKeyEnvelope_Endpoint struct {
	Endpoint *model.ActorDeviceRef `protobuf:"bytes,2,opt,name=endpoint,proto3,oneof"`
}

type ViewerContentKeyEnvelope_RecoveryActor struct {
	RecoveryActor *model.ActorRef `protobuf:"bytes,3,opt,name=recovery_actor,json=recoveryActor,proto3,oneof"`
}

func (*ViewerContentKeyEnvelope_Endpoint) isViewerContentKeyEnvelope_Recipient() {}

func (*ViewerContentKeyEnvelope_RecoveryActor) isViewerContentKeyEnvelope_Recipient() {}

type ViewerContentCommitProof struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	FormatVersion               uint32                 `protobuf:"varint,1,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`
	DomainCommitId              string                 `protobuf:"bytes,2,opt,name=domain_commit_id,json=domainCommitId,proto3" json:"domain_commit_id,omitempty"`
	CanonicalPlanSha256         []byte                 `protobuf:"bytes,3,opt,name=canonical_plan_sha256,json=canonicalPlanSha256,proto3" json:"canonical_plan_sha256,omitempty"`
	Resource                    *SecureResourceRef     `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`
	Author                      *model.ActorDeviceRef  `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	AuthorizationSnapshotSha256 []byte                 `protobuf:"bytes,6,opt,name=authorization_snapshot_sha256,json=authorizationSnapshotSha256,proto3" json:"authorization_snapshot_sha256,omitempty"`
	DomainBindingSha256         []byte                 `protobuf:"bytes,7,opt,name=domain_binding_sha256,json=domainBindingSha256,proto3" json:"domain_binding_sha256,omitempty"`
	EncryptedPayloadSha256      []byte                 `protobuf:"bytes,8,opt,name=encrypted_payload_sha256,json=encryptedPayloadSha256,proto3" json:"encrypted_payload_sha256,omitempty"`
	ObjectDescriptorSetSha256   []byte                 `protobuf:"bytes,9,opt,name=object_descriptor_set_sha256,json=objectDescriptorSetSha256,proto3" json:"object_descriptor_set_sha256,omitempty"`
	MentionRoutingSha256        []byte                 `protobuf:"bytes,10,opt,name=mention_routing_sha256,json=mentionRoutingSha256,proto3" json:"mention_routing_sha256,omitempty"`
	SubtypeAuthoritySha256      []byte                 `protobuf:"bytes,11,opt,name=subtype_authority_sha256,json=subtypeAuthoritySha256,proto3" json:"subtype_authority_sha256,omitempty"`
	CommittedAt                 *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=committed_at,json=committedAt,proto3" json:"committed_at,omitempty"`
	StationSigningKeyId         string                 `protobuf:"bytes,13,opt,name=station_signing_key_id,json=stationSigningKeyId,proto3" json:"station_signing_key_id,omitempty"`
	StationSignature            []byte                 `protobuf:"bytes,14,opt,name=station_signature,json=stationSignature,proto3" json:"station_signature,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *ViewerContentCommitProof) Reset() {
	*x = ViewerContentCommitProof{}
	mi := &file_domain_secure_content_content_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewerContentCommitProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewerContentCommitProof) ProtoMessage() {}

func (x *ViewerContentCommitProof) ProtoReflect() protoreflect.Message {
	mi := &file_domain_secure_content_content_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewerContentCommitProof.ProtoReflect.Descriptor instead.
func (*ViewerContentCommitProof) Descriptor() ([]byte, []int) {
	return file_domain_secure_content_content_proto_rawDescGZIP(), []int{7}
}

func (x *ViewerContentCommitProof) GetFormatVersion() uint32 {
	if x != nil {
		return x.FormatVersion
	}
	return 0
}

func (x *ViewerContentCommitProof) GetDomainCommitId() string {
	if x != nil {
		return x.DomainCommitId
	}
	return ""
}

func (x *ViewerContentCommitProof) GetCanonicalPlanSha256() []byte {
	if x != nil {
		return x.CanonicalPlanSha256
	}
	return nil
}

func (x *ViewerContentCommitProof) GetResource() *SecureResourceRef {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *ViewerContentCommitProof) GetAuthor() *model.ActorDeviceRef {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *ViewerContentCommitProof) GetAuthorizationSnapshotSha256() []byte {
	if x != nil {
		return x.AuthorizationSnapshotSha256
	}
	return nil
}

func (x *ViewerContentCommitProof) GetDomainBindingSha256() []byte {
	if x != nil {
		return x.DomainBindingSha256
	}
	return nil
}

func (x *ViewerContentCommitProof) GetEncryptedPayloadSha256() []byte {
	if x != nil {
		return x.EncryptedPayloadSha256
	}
	return nil
}

func (x *ViewerContentCommitProof) GetObjectDescriptorSetSha256() []byte {
	if x != nil {
		return x.ObjectDescriptorSetSha256
	}
	return nil
}

func (x *ViewerContentCommitProof) GetMentionRoutingSha256() []byte {
	if x != nil {
		return x.MentionRoutingSha256
	}
	return nil
}

func (x *ViewerContentCommitProof) GetSubtypeAuthoritySha256() []byte {
	if x != nil {
		return x.SubtypeAuthoritySha256
	}
	return nil
}

func (x *ViewerContentCommitProof) GetCommittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CommittedAt
	}
	return nil
}

func (x *ViewerContentCommitProof) GetStationSigningKeyId() string {
	if x != nil {
		return x.StationSigningKeyId
	}
	return ""
}

func (x *ViewerContentCommitProof) GetStationSignature() []byte {
	if x != nil {
		return x.StationSignature
	}
	return nil
}

type StationContentSigningKeyAttestation struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	FormatVersion         uint32                 `protobuf:"varint,1,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`
	StationPeerId         string                 `protobuf:"bytes,2,opt,name=station_peer_id,json=stationPeerId,proto3" json:"station_peer_id,omitempty"`
	ProofSigningKeyId     string                 `protobuf:"bytes,3,opt,name=proof_signing_key_id,json=proofSigningKeyId,proto3" json:"proof_signing_key_id,omitempty"`
	ProofEd25519PublicKey []byte                 `protobuf:"bytes,4,opt,name=proof_ed25519_public_key,json=proofEd25519PublicKey,proto3" json:"proof_ed25519_public_key,omitempty"`
	AttestingSigningKeyId string                 `protobuf:"bytes,5,opt,name=attesting_signing_key_id,json=attestingSigningKeyId,proto3" json:"attesting_signing_key_id,omitempty"`
	IssuedAt              *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	ExpiresAt             *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	StationSignature      []byte                 `protobuf:"bytes,8,opt,name=station_signature,json=stationSignature,proto3" json:"station_signature,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *StationContentSigningKeyAttestation) Reset() {
	*x = StationContentSigningKeyAttestation{}
	mi := &file_domain_secure_content_content_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StationContentSigningKeyAttestation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StationContentSigningKeyAttestation) ProtoMessage() {}

func (x *StationContentSigningKeyAttestation) ProtoReflect() protoreflect.Message {
	mi := &file_domain_secure_content_content_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StationContentSigningKeyAttestation.ProtoReflect.Descriptor instead.
func (*StationContentSigningKeyAttestation) Descriptor() ([]byte, []int) {
	return file_domain_secure_content_content_proto_rawDescGZIP(), []int{8}
}

func (x *StationContentSigningKeyAttestation) GetFormatVersion() uint32 {
	if x != nil {
		return x.FormatVersion
	}
	return 0
}

func (x *StationContentSigningKeyAttestation) GetStationPeerId() string {
	if x != nil {
		return x.StationPeerId
	}
	return ""
}

func (x *StationContentSigningKeyAttestation) GetProofSigningKeyId() string {
	if x != nil {
		return x.ProofSigningKeyId
	}
	return ""
}

func (x *StationContentSigningKeyAttestation) GetProofEd25519PublicKey() []byte {
	if x != nil {
		return x.ProofEd25519PublicKey
	}
	return nil
}

func (x *StationContentSigningKeyAttestation) GetAttestingSigningKeyId() string {
	if x != nil {
		return x.AttestingSigningKeyId
	}
	return ""
}

func (x *StationContentSigningKeyAttestation) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *StationContentSigningKeyAttestation) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *StationContentSigningKeyAttestation) GetStationSignature() []byte {
	if x != nil {
		return x.StationSignature
	}
	return nil
}

var File_domain_secure_content_content_proto protoreflect.FileDescriptor

const file_domain_secure_content_content_proto_rawDesc = "" +
	"\n" +
	"#domain/secure_content/content.proto\x12#peers_touch.model.secure_content.v1\x1a\x18domain/actor/actor.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb4\x01\n" +
	"\x11SecureResourceRef\x12`\n" +
	"\fowner_domain\x18\x01 \x01(\x0e2=.peers_touch.model.secure_content.v1.SecureContentOwnerDomainR\vownerDomain\x12\x1d\n" +
	"\n" +
	"content_id\x18\x02 \x01(\tR\tcontentId\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\x04R\n" +
	"generation\"\xe2\x02\n" +
	"\x10EncryptedPayload\x12%\n" +
	"\x0eformat_version\x18\x01 \x01(\rR\rformatVersion\x12R\n" +
	"\bresource\x18\x02 \x01(\v26.peers_touch.model.secure_content.v1.SecureResourceRefR\bresource\x12Q\n" +
	"\x05suite\x18\x03 \x01(\x0e2;.peers_touch.model.secure_content.v1.PayloadEncryptionSuiteR\x05suite\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\fR\x05nonce\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x05 \x01(\fR\n" +
	"ciphertext\x12+\n" +
	"\x11ciphertext_sha256\x18\x06 \x01(\fR\x10ciphertextSha256\x12\x1d\n" +
	"\n" +
	"aad_sha256\x18\a \x01(\fR\taadSha256\"\xad\x02\n" +
	"\x1cRequiredContentRecipientSlot\x12*\n" +
	"\x11recipient_slot_id\x18\x01 \x01(\tR\x0frecipientSlotId\x12Q\n" +
	"\bkey_kind\x18\x02 \x01(\x0e26.peers_touch.model.secure_content.v1.ContentPreKeyKindR\akeyKind\x12%\n" +
	"\x0fone_time_key_id\x18\x03 \x01(\tR\foneTimeKeyId\x12-\n" +
	"\x13one_time_public_key\x18\x04 \x01(\fR\x10oneTimePublicKey\x128\n" +
	"\x18principal_binding_sha256\x18\x05 \x01(\fR\x16principalBindingSha256\"\xc1\x05\n" +
	"\x15ContentEncryptionPlan\x12%\n" +
	"\x0eformat_version\x18\x01 \x01(\rR\rformatVersion\x12\x17\n" +
	"\aplan_id\x18\x02 \x01(\tR\x06planId\x12R\n" +
	"\bresource\x18\x03 \x01(\v26.peers_touch.model.secure_content.v1.SecureResourceRefR\bresource\x12B\n" +
	"\x06author\x18\x04 \x01(\v2*.peers_touch.model.actor.v1.ActorDeviceRefR\x06author\x12B\n" +
	"\x1dauthorization_snapshot_sha256\x18\x05 \x01(\fR\x1bauthorizationSnapshotSha256\x12h\n" +
	"\x0erequired_slots\x18\x06 \x03(\v2A.peers_touch.model.secure_content.v1.RequiredContentRecipientSlotR\rrequiredSlots\x12\x1d\n" +
	"\n" +
	"object_ids\x18\a \x03(\tR\tobjectIds\x129\n" +
	"\n" +
	"expires_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x122\n" +
	"\x15canonical_plan_sha256\x18\t \x01(\fR\x13canonicalPlanSha256\x123\n" +
	"\x16station_signing_key_id\x18\n" +
	" \x01(\tR\x13stationSigningKeyId\x12+\n" +
	"\x11station_signature\x18\v \x01(\fR\x10stationSignature\x122\n" +
	"\x15domain_binding_sha256\x18\f \x01(\fR\x13domainBindingSha256\"\xd5\x06\n" +
	"\x19ContentKeyEnvelopeBinding\x12%\n" +
	"\x0eformat_version\x18\x01 \x01(\rR\rformatVersion\x12\x17\n" +
	"\aplan_id\x18\x02 \x01(\tR\x06planId\x122\n" +
	"\x15canonical_plan_sha256\x18\x03 \x01(\fR\x13canonicalPlanSha256\x12R\n" +
	"\bresource\x18\x04 \x01(\v26.peers_touch.model.secure_content.v1.SecureResourceRefR\bresource\x12*\n" +
	"\x11recipient_slot_id\x18\x05 \x01(\tR\x0frecipientSlotId\x12d\n" +
	"\x12recipient_key_kind\x18\x06 \x01(\x0e26.peers_touch.model.secure_content.v1.ContentPreKeyKindR\x10recipientKeyKind\x12(\n" +
	"\x10recipient_key_id\x18\a \x01(\tR\x0erecipientKeyId\x128\n" +
	"\x18principal_binding_sha256\x18\b \x01(\fR\x16principalBindingSha256\x12B\n" +
	"\x1dauthorization_snapshot_sha256\x18\t \x01(\fR\x1bauthorizationSnapshotSha256\x12:\n" +
	"\x19payload_ciphertext_sha256\x18\n" +
	" \x01(\fR\x17payloadCiphertextSha256\x12?\n" +
	"\x1cobject_descriptor_set_sha256\x18\v \x01(\fR\x19objectDescriptorSetSha256\x12B\n" +
	"\x0fplan_expires_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\rplanExpiresAt\x12B\n" +
	"\x06sender\x18\r \x01(\v2*.peers_touch.model.actor.v1.ActorDeviceRefR\x06sender\x121\n" +
	"\x15sender_signing_key_id\x18\x0e \x01(\tR\x12senderSigningKeyId\"\xa5\x02\n" +
	"\x1aPreparedContentKeyEnvelope\x12X\n" +
	"\abinding\x18\x01 \x01(\v2>.peers_touch.model.secure_content.v1.ContentKeyEnvelopeBindingR\abinding\x12%\n" +
	"\x0ebinding_sha256\x18\x02 \x01(\fR\rbindingSha256\x122\n" +
	"\x15hpke_encapsulated_key\x18\x03 \x01(\fR\x13hpkeEncapsulatedKey\x12'\n" +
	"\x0fhpke_ciphertext\x18\x04 \x01(\fR\x0ehpkeCiphertext\x12)\n" +
	"\x10sender_signature\x18\x05 \x01(\fR\x0fsenderSignature\"\xf2\x03\n" +
	"\x18ViewerContentKeyEnvelope\x12X\n" +
	"\abinding\x18\x01 \x01(\v2>.peers_touch.model.secure_content.v1.ContentKeyEnvelopeBindingR\abinding\x12H\n" +
	"\bendpoint\x18\x02 \x01(\v2*.peers_touch.model.actor.v1.ActorDeviceRefH\x00R\bendpoint\x12M\n" +
	"\x0erecovery_actor\x18\x03 \x01(\v2$.peers_touch.model.actor.v1.ActorRefH\x00R\rrecoveryActor\x12%\n" +
	"\x0ebinding_sha256\x18\x04 \x01(\fR\rbindingSha256\x122\n" +
	"\x15hpke_encapsulated_key\x18\x05 \x01(\fR\x13hpkeEncapsulatedKey\x12'\n" +
	"\x0fhpke_ciphertext\x18\x06 \x01(\fR\x0ehpkeCiphertext\x12)\n" +
	"\x10sender_signature\x18\a \x01(\fR\x0fsenderSignature\x12'\n" +
	"\x0fprincipal_epoch\x18\b \x01(\x04R\x0eprincipalEpochB\v\n" +
	"\trecipient\"\xbb\x06\n" +
	"\x18ViewerContentCommitProof\x12%\n" +
	"\x0eformat_version\x18\x01 \x01(\rR\rformatVersion\x12(\n" +
	"\x10domain_commit_id\x18\x02 \x01(\tR\x0edomainCommitId\x122\n" +
	"\x15canonical_plan_sha256\x18\x03 \x01(\fR\x13canonicalPlanSha256\x12R\n" +
	"\bresource\x18\x04 \x01(\v26.peers_touch.model.secure_content.v1.SecureResourceRefR\bresource\x12B\n" +
	"\x06author\x18\x05 \x01(\v2*.peers_touch.model.actor.v1.ActorDeviceRefR\x06author\x12B\n" +
	"\x1dauthorization_snapshot_sha256\x18\x06 \x01(\fR\x1bauthorizationSnapshotSha256\x122\n" +
	"\x15domain_binding_sha256\x18\a \x01(\fR\x13domainBindingSha256\x128\n" +
	"\x18encrypted_payload_sha256\x18\b \x01(\fR\x16encryptedPayloadSha256\x12?\n" +
	"\x1cobject_descriptor_set_sha256\x18\t \x01(\fR\x19objectDescriptorSetSha256\x124\n" +
	"\x16mention_routing_sha256\x18\n" +
	" \x01(\fR\x14mentionRoutingSha256\x128\n" +
	"\x18subtype_authority_sha256\x18\v \x01(\fR\x16subtypeAuthoritySha256\x12=\n" +
	"\fcommitted_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\vcommittedAt\x123\n" +
	"\x16station_signing_key_id\x18\r \x01(\tR\x13stationSigningKeyId\x12+\n" +
	"\x11station_signature\x18\x0e \x01(\fR\x10stationSignature\"\xb8\x03\n" +
	"#StationContentSigningKeyAttestation\x12%\n" +
	"\x0eformat_version\x18\x01 \x01(\rR\rformatVersion\x12&\n" +
	"\x0fstation_peer_id\x18\x02 \x01(\tR\rstationPeerId\x12/\n" +
	"\x14proof_signing_key_id\x18\x03 \x01(\tR\x11proofSigningKeyId\x127\n" +
	"\x18proof_ed25519_public_key\x18\x04 \x01(\fR\x15proofEd25519PublicKey\x127\n" +
	"\x18attesting_signing_key_id\x18\x05 \x01(\tR\x15attestingSigningKeyId\x127\n" +
	"\tissued_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x129\n" +
	"\n" +
	"expires_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12+\n" +
	"\x11station_signature\x18\b \x01(\fR\x10stationSignature*\x9d\x01\n" +
	"\x18SecureContentOwnerDomain\x12+\n" +
	"'SECURE_CONTENT_OWNER_DOMAIN_UNSPECIFIED\x10\x00\x12,\n" +
	"(SECURE_CONTENT_OWNER_DOMAIN_CONVERSATION\x10\x01\x12&\n" +
	"\"SECURE_CONTENT_OWNER_DOMAIN_SOCIAL\x10\x02*l\n" +
	"\x16PayloadEncryptionSuite\x12(\n" +
	"$PAYLOAD_ENCRYPTION_SUITE_UNSPECIFIED\x10\x00\x12(\n" +
	"$PAYLOAD_ENCRYPTION_SUITE_AES_256_GCM\x10\x01*\x82\x01\n" +
	"\x11ContentPreKeyKind\x12#\n" +
	"\x1fCONTENT_PREKEY_KIND_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cCONTENT_PREKEY_KIND_ENDPOINT\x10\x01\x12&\n" +
	"\"CONTENT_PREKEY_KIND_ACTOR_RECOVERY\x10\x02BXZVgithub.com/peers-labs/peers-touch/station/frame/core/types/securecontent;securecontentb\x06proto3"

var (
	file_domain_secure_content_content_proto_rawDescOnce sync.Once
	file_domain_secure_content_content_proto_rawDescData []byte
)

func file_domain_secure_content_content_proto_rawDescGZIP() []byte {
	file_domain_secure_content_content_proto_rawDescOnce.Do(func() {
		file_domain_secure_content_content_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_secure_content_content_proto_rawDesc), len(file_domain_secure_content_content_proto_rawDesc)))
	})
	return file_domain_secure_content_content_proto_rawDescData
}

var file_domain_secure_content_content_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_domain_secure_content_content_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_domain_secure_content_content_proto_goTypes = []any{
	(SecureContentOwnerDomain)(0),               // 0: peers_touch.model.secure_content.v1.SecureContentOwnerDomain
	(PayloadEncryptionSuite)(0),                 // 1: peers_touch.model.secure_content.v1.PayloadEncryptionSuite
	(ContentPreKeyKind)(0),                      // 2: peers_touch.model.secure_content.v1.ContentPreKeyKind
	(*SecureResourceRef)(nil),                   // 3: peers_touch.model.secure_content.v1.SecureResourceRef
	(*EncryptedPayload)(nil),                    // 4: peers_touch.model.secure_content.v1.EncryptedPayload
	(*RequiredContentRecipientSlot)(nil),        // 5: peers_touch.model.secure_content.v1.RequiredContentRecipientSlot
	(*ContentEncryptionPlan)(nil),               // 6: peers_touch.model.secure_content.v1.ContentEncryptionPlan
	(*ContentKeyEnvelopeBinding)(nil),           // 7: peers_touch.model.secure_content.v1.ContentKeyEnvelopeBinding
	(*PreparedContentKeyEnvelope)(nil),          // 8: peers_touch.model.secure_content.v1.PreparedContentKeyEnvelope
	(*ViewerContentKeyEnvelope)(nil),            // 9: peers_touch.model.secure_content.v1.ViewerContentKeyEnvelope
	(*ViewerContentCommitProof)(nil),            // 10: peers_touch.model.secure_content.v1.ViewerContentCommitProof
	(*StationContentSigningKeyAttestation)(nil), // 11: peers_touch.model.secure_content.v1.StationContentSigningKeyAttestation
	(*model.ActorDeviceRef)(nil),                // 12: peers_touch.model.actor.v1.ActorDeviceRef
	(*timestamppb.Timestamp)(nil),               // 13: google.protobuf.Timestamp
	(*model.ActorRef)(nil),                      // 14: peers_touch.model.actor.v1.ActorRef
}
var file_domain_secure_content_content_proto_depIdxs = []int32{
	0,  // 0: peers_touch.model.secure_content.v1.SecureResourceRef.owner_domain:type_name -> peers_touch.model.secure_content.v1.SecureContentOwnerDomain
	3,  // 1: peers_touch.model.secure_content.v1.EncryptedPayload.resource:type_name -> peers_touch.model.secure_content.v1.SecureResourceRef
	1,  // 2: peers_touch.model.secure_content.v1.EncryptedPayload.suite:type_name -> peers_touch.model.secure_content.v1.PayloadEncryptionSuite
	2,  // 3: peers_touch.model.secure_content.v1.RequiredContentRecipientSlot.key_kind:type_name -> peers_touch.model.secure_content.v1.ContentPreKeyKind
	3,  // 4: peers_touch.model.secure_content.v1.ContentEncryptionPlan.resource:type_name -> peers_touch.model.secure_content.v1.SecureResourceRef
	12, // 5: peers_touch.model.secure_content.v1.ContentEncryptionPlan.author:type_name -> peers_touch.model.actor.v1.ActorDeviceRef
	5,  // 6: peers_touch.model.secure_content.v1.ContentEncryptionPlan.required_slots:type_name -> peers_touch.model.secure_content.v1.RequiredContentRecipientSlot
	13, // 7: peers_touch.model.secure_content.v1.ContentEncryptionPlan.expires_at:type_name -> google.protobuf.Timestamp
	3,  // 8: peers_touch.model.secure_content.v1.ContentKeyEnvelopeBinding.resource:type_name -> peers_touch.model.secure_content.v1.SecureResourceRef
	2,  // 9: peers_touch.model.secure_content.v1.ContentKeyEnvelopeBinding.recipient_key_kind:type_name -> peers_touch.model.secure_content.v1.ContentPreKeyKind
	13, // 10: peers_touch.model.secure_content.v1.ContentKeyEnvelopeBinding.plan_expires_at:type_name -> google.protobuf.Timestamp
	12, // 11: peers_touch.model.secure_content.v1.ContentKeyEnvelopeBinding.sender:type_name -> peers_touch.model.actor.v1.ActorDeviceRef
	7,  // 12: peers_touch.model.secure_content.v1.PreparedContentKeyEnvelope.binding:type_name -> peers_touch.model.secure_content.v1.ContentKeyEnvelopeBinding
	7,  // 13: peers_touch.model.secure_content.v1.ViewerContentKeyEnvelope.binding:type_name -> peers_touch.model.secure_content.v1.ContentKeyEnvelopeBinding
	12, // 14: peers_touch.model.secure_content.v1.ViewerContentKeyEnvelope.endpoint:type_name -> peers_touch.model.actor.v1.ActorDeviceRef
	14, // 15: peers_touch.model.secure_content.v1.ViewerContentKeyEnvelope.recovery_actor:type_name -> peers_touch.model.actor.v1.ActorRef
	3,  // 16: peers_touch.model.secure_content.v1.ViewerContentCommitProof.resource:type_name -> peers_touch.model.secure_content.v1.SecureResourceRef
	12, // 17: peers_touch.model.secure_content.v1.ViewerContentCommitProof.author:type_name -> peers_touch.model.actor.v1.ActorDeviceRef
	13, // 18: peers_touch.model.secure_content.v1.ViewerContentCommitProof.committed_at:type_name -> google.protobuf.Timestamp
	13, // 19: peers_touch.model.secure_content.v1.StationContentSigningKeyAttestation.issued_at:type_name -> google.protobuf.Timestamp
	13, // 20: peers_touch.model.secure_content.v1.StationContentSigningKeyAttestation.expires_at:type_name -> google.protobuf.Timestamp
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_domain_secure_content_content_proto_init() }
func file_domain_secure_content_content_proto_init() {
	if File_domain_secure_content_content_proto != nil {
		return
	}
	file_domain_secure_content_content_proto_msgTypes[6].OneofWrappers = []any{
		(*ViewerContentKeyEnvelope_Endpoint)(nil),
		(*ViewerContentKeyEnvelope_RecoveryActor)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_secure_content_content_proto_rawDesc), len(file_domain_secure_content_content_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_secure_content_content_proto_goTypes,
		DependencyIndexes: file_domain_secure_content_content_proto_depIdxs,
		EnumInfos:         file_domain_secure_content_content_proto_enumTypes,
		MessageInfos:      file_domain_secure_content_content_proto_msgTypes,
	}.Build()
	File_domain_secure_content_content_proto = out.File
	file_domain_secure_content_content_proto_goTypes = nil
	file_domain_secure_content_content_proto_depIdxs = nil
}
