// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: domain/presence/presence.proto

package presence

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PresenceState int32

const (
	PresenceState_PRESENCE_STATE_UNSPECIFIED PresenceState = 0
	PresenceState_PRESENCE_STATE_ONLINE      PresenceState = 1
	PresenceState_PRESENCE_STATE_OFFLINE     PresenceState = 2
)

// Enum value maps for PresenceState.
var (
	PresenceState_name = map[int32]string{
		0: "PRESENCE_STATE_UNSPECIFIED",
		1: "PRESENCE_STATE_ONLINE",
		2: "PRESENCE_STATE_OFFLINE",
	}
	PresenceState_value = map[string]int32{
		"PRESENCE_STATE_UNSPECIFIED": 0,
		"PRESENCE_STATE_ONLINE":      1,
		"PRESENCE_STATE_OFFLINE":     2,
	}
)

func (x PresenceState) Enum() *PresenceState {
	p := new(PresenceState)
	*p = x
	return p
}

func (x PresenceState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PresenceState) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_presence_presence_proto_enumTypes[0].Descriptor()
}

func (PresenceState) Type() protoreflect.EnumType {
	return &file_domain_presence_presence_proto_enumTypes[0]
}

func (x PresenceState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PresenceState.Descriptor instead.
func (PresenceState) EnumDescriptor() ([]byte, []int) {
	return file_domain_presence_presence_proto_rawDescGZIP(), []int{0}
}

type PresenceHeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresenceHeartbeatRequest) Reset() {
	*x = PresenceHeartbeatRequest{}
	mi := &file_domain_presence_presence_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceHeartbeatRequest) ProtoMessage() {}

func (x *PresenceHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_presence_presence_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*PresenceHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_domain_presence_presence_proto_rawDescGZIP(), []int{0}
}

func (x *PresenceHeartbeatRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type PresenceOfflineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresenceOfflineRequest) Reset() {
	*x = PresenceOfflineRequest{}
	mi := &file_domain_presence_presence_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceOfflineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceOfflineRequest) ProtoMessage() {}

func (x *PresenceOfflineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_presence_presence_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceOfflineRequest.ProtoReflect.Descriptor instead.
func (*PresenceOfflineRequest) Descriptor() ([]byte, []int) {
	return file_domain_presence_presence_proto_rawDescGZIP(), []int{1}
}

func (x *PresenceOfflineRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type PresenceUpdateResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ActorId        string                 `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	SessionId      string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	State          PresenceState          `protobuf:"varint,3,opt,name=state,proto3,enum=peers_touch.model.presence.v1.PresenceState" json:"state,omitempty"`
	LeaseExpiresAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=lease_expires_at,json=leaseExpiresAt,proto3" json:"lease_expires_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PresenceUpdateResponse) Reset() {
	*x = PresenceUpdateResponse{}
	mi := &file_domain_presence_presence_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceUpdateResponse) ProtoMessage() {}

func (x *PresenceUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_presence_presence_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceUpdateResponse.ProtoReflect.Descriptor instead.
func (*PresenceUpdateResponse) Descriptor() ([]byte, []int) {
	return file_domain_presence_presence_proto_rawDescGZIP(), []int{2}
}

func (x *PresenceUpdateResponse) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *PresenceUpdateResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PresenceUpdateResponse) GetState() PresenceState {
	if x != nil {
		return x.State
	}
	return PresenceState_PRESENCE_STATE_UNSPECIFIED
}

func (x *PresenceUpdateResponse) GetLeaseExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LeaseExpiresAt
	}
	return nil
}

type PresenceQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorIds      []string               `protobuf:"bytes,1,rep,name=actor_ids,json=actorIds,proto3" json:"actor_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresenceQueryRequest) Reset() {
	*x = PresenceQueryRequest{}
	mi := &file_domain_presence_presence_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceQueryRequest) ProtoMessage() {}

func (x *PresenceQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_presence_presence_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceQueryRequest.ProtoReflect.Descriptor instead.
func (*PresenceQueryRequest) Descriptor() ([]byte, []int) {
	return file_domain_presence_presence_proto_rawDescGZIP(), []int{3}
}

func (x *PresenceQueryRequest) GetActorIds() []string {
	if x != nil {
		return x.ActorIds
	}
	return nil
}

type PresenceStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ActorId        string                 `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	State          PresenceState          `protobuf:"varint,2,opt,name=state,proto3,enum=peers_touch.model.presence.v1.PresenceState" json:"state,omitempty"`
	LastSeenAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	LeaseExpiresAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=lease_expires_at,json=leaseExpiresAt,proto3" json:"lease_expires_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PresenceStatus) Reset() {
	*x = PresenceStatus{}
	mi := &file_domain_presence_presence_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceStatus) ProtoMessage() {}

func (x *PresenceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_domain_presence_presence_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceStatus.ProtoReflect.Descriptor instead.
func (*PresenceStatus) Descriptor() ([]byte, []int) {
	return file_domain_presence_presence_proto_rawDescGZIP(), []int{4}
}

func (x *PresenceStatus) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *PresenceStatus) GetState() PresenceState {
	if x != nil {
		return x.State
	}
	return PresenceState_PRESENCE_STATE_UNSPECIFIED
}

func (x *PresenceStatus) GetLastSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenAt
	}
	return nil
}

func (x *PresenceStatus) GetLeaseExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LeaseExpiresAt
	}
	return nil
}

type PresenceQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statuses      []*PresenceStatus      `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresenceQueryResponse) Reset() {
	*x = PresenceQueryResponse{}
	mi := &file_domain_presence_presence_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceQueryResponse) ProtoMessage() {}

func (x *PresenceQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_presence_presence_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceQueryResponse.ProtoReflect.Descriptor instead.
func (*PresenceQueryResponse) Descriptor() ([]byte, []int) {
	return file_domain_presence_presence_proto_rawDescGZIP(), []int{5}
}

func (x *PresenceQueryResponse) GetStatuses() []*PresenceStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

var File_domain_presence_presence_proto protoreflect.FileDescriptor

const file_domain_presence_presence_proto_rawDesc = "" +
	"\n" +
	"\x1edomain/presence/presence.proto\x12\x1dpeers_touch.model.presence.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"2\n" +
	"\x18PresenceHeartbeatRequest\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"0\n" +
	"\x16PresenceOfflineRequest\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\xdc\x01\n" +
	"\x16PresenceUpdateResponse\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\tR\aactorId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12B\n" +
	"\x05state\x18\x03 \x01(\x0e2,.peers_touch.model.presence.v1.PresenceStateR\x05state\x12D\n" +
	"\x10lease_expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0eleaseExpiresAt\"3\n" +
	"\x14PresenceQueryRequest\x12\x1b\n" +
	"\tactor_ids\x18\x01 \x03(\tR\bactorIds\"\xf3\x01\n" +
	"\x0ePresenceStatus\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\tR\aactorId\x12B\n" +
	"\x05state\x18\x02 \x01(\x0e2,.peers_touch.model.presence.v1.PresenceStateR\x05state\x12<\n" +
	"\flast_seen_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSeenAt\x12D\n" +
	"\x10lease_expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0eleaseExpiresAt\"b\n" +
	"\x15PresenceQueryResponse\x12I\n" +
	"\bstatuses\x18\x01 \x03(\v2-.peers_touch.model.presence.v1.PresenceStatusR\bstatuses*f\n" +
	"\rPresenceState\x12\x1e\n" +
	"\x1aPRESENCE_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PRESENCE_STATE_ONLINE\x10\x01\x12\x1a\n" +
	"\x16PRESENCE_STATE_OFFLINE\x10\x02BOZMgithub.com/peers-labs/peers-touch/station/frame/touch/model/presence;presenceb\x06proto3"

var (
	file_domain_presence_presence_proto_rawDescOnce sync.Once
	file_domain_presence_presence_proto_rawDescData []byte
)

func file_domain_presence_presence_proto_rawDescGZIP() []byte {
	file_domain_presence_presence_proto_rawDescOnce.Do(func() {
		file_domain_presence_presence_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_presence_presence_proto_rawDesc), len(file_domain_presence_presence_proto_rawDesc)))
	})
	return file_domain_presence_presence_proto_rawDescData
}

var file_domain_presence_presence_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_domain_presence_presence_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_domain_presence_presence_proto_goTypes = []any{
	(PresenceState)(0),               // 0: peers_touch.model.presence.v1.PresenceState
	(*PresenceHeartbeatRequest)(nil), // 1: peers_touch.model.presence.v1.PresenceHeartbeatRequest
	(*PresenceOfflineRequest)(nil),   // 2: peers_touch.model.presence.v1.PresenceOfflineRequest
	(*PresenceUpdateResponse)(nil),   // 3: peers_touch.model.presence.v1.PresenceUpdateResponse
	(*PresenceQueryRequest)(nil),     // 4: peers_touch.model.presence.v1.PresenceQueryRequest
	(*PresenceStatus)(nil),           // 5: peers_touch.model.presence.v1.PresenceStatus
	(*PresenceQueryResponse)(nil),    // 6: peers_touch.model.presence.v1.PresenceQueryResponse
	(*timestamppb.Timestamp)(nil),    // 7: google.protobuf.Timestamp
}
var file_domain_presence_presence_proto_depIdxs = []int32{
	0, // 0: peers_touch.model.presence.v1.PresenceUpdateResponse.state:type_name -> peers_touch.model.presence.v1.PresenceState
	7, // 1: peers_touch.model.presence.v1.PresenceUpdateResponse.lease_expires_at:type_name -> google.protobuf.Timestamp
	0, // 2: peers_touch.model.presence.v1.PresenceStatus.state:type_name -> peers_touch.model.presence.v1.PresenceState
	7, // 3: peers_touch.model.presence.v1.PresenceStatus.last_seen_at:type_name -> google.protobuf.Timestamp
	7, // 4: peers_touch.model.presence.v1.PresenceStatus.lease_expires_at:type_name -> google.protobuf.Timestamp
	5, // 5: peers_touch.model.presence.v1.PresenceQueryResponse.statuses:type_name -> peers_touch.model.presence.v1.PresenceStatus
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_domain_presence_presence_proto_init() }
func file_domain_presence_presence_proto_init() {
	if File_domain_presence_presence_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_presence_presence_proto_rawDesc), len(file_domain_presence_presence_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_presence_presence_proto_goTypes,
		DependencyIndexes: file_domain_presence_presence_proto_depIdxs,
		EnumInfos:         file_domain_presence_presence_proto_enumTypes,
		MessageInfos:      file_domain_presence_presence_proto_msgTypes,
	}.Build()
	File_domain_presence_presence_proto = out.File
	file_domain_presence_presence_proto_goTypes = nil
	file_domain_presence_presence_proto_depIdxs = nil
}
