// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: domain/note/v1/note.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Note struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        string                 `protobuf:"bytes,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Note) Reset() {
	*x = Note{}
	mi := &file_domain_note_v1_note_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Note) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Note) ProtoMessage() {}

func (x *Note) ProtoReflect() protoreflect.Message {
	mi := &file_domain_note_v1_note_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Note.ProtoReflect.Descriptor instead.
func (*Note) Descriptor() ([]byte, []int) {
	return file_domain_note_v1_note_proto_rawDescGZIP(), []int{0}
}

func (x *Note) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

func (x *Note) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Note) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Note) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Note) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Note) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Note) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type ListNotesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PageSize       int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken      string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	OrderBy        string                 `protobuf:"bytes,3,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	IncludeDeleted bool                   `protobuf:"varint,4,opt,name=include_deleted,json=includeDeleted,proto3" json:"include_deleted,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListNotesRequest) Reset() {
	*x = ListNotesRequest{}
	mi := &file_domain_note_v1_note_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotesRequest) ProtoMessage() {}

func (x *ListNotesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_note_v1_note_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotesRequest.ProtoReflect.Descriptor instead.
func (*ListNotesRequest) Descriptor() ([]byte, []int) {
	return file_domain_note_v1_note_proto_rawDescGZIP(), []int{1}
}

func (x *ListNotesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListNotesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListNotesRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *ListNotesRequest) GetIncludeDeleted() bool {
	if x != nil {
		return x.IncludeDeleted
	}
	return false
}

type ListNotesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Note                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotesResponse) Reset() {
	*x = ListNotesResponse{}
	mi := &file_domain_note_v1_note_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotesResponse) ProtoMessage() {}

func (x *ListNotesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_note_v1_note_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotesResponse.ProtoReflect.Descriptor instead.
func (*ListNotesResponse) Descriptor() ([]byte, []int) {
	return file_domain_note_v1_note_proto_rawDescGZIP(), []int{2}
}

func (x *ListNotesResponse) GetItems() []*Note {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListNotesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetNoteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NoteId         string                 `protobuf:"bytes,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	IncludeDeleted bool                   `protobuf:"varint,2,opt,name=include_deleted,json=includeDeleted,proto3" json:"include_deleted,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetNoteRequest) Reset() {
	*x = GetNoteRequest{}
	mi := &file_domain_note_v1_note_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNoteRequest) ProtoMessage() {}

func (x *GetNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_note_v1_note_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNoteRequest.ProtoReflect.Descriptor instead.
func (*GetNoteRequest) Descriptor() ([]byte, []int) {
	return file_domain_note_v1_note_proto_rawDescGZIP(), []int{3}
}

func (x *GetNoteRequest) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

func (x *GetNoteRequest) GetIncludeDeleted() bool {
	if x != nil {
		return x.IncludeDeleted
	}
	return false
}

type GetNoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Note                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNoteResponse) Reset() {
	*x = GetNoteResponse{}
	mi := &file_domain_note_v1_note_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNoteResponse) ProtoMessage() {}

func (x *GetNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_note_v1_note_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNoteResponse.ProtoReflect.Descriptor instead.
func (*GetNoteResponse) Descriptor() ([]byte, []int) {
	return file_domain_note_v1_note_proto_rawDescGZIP(), []int{4}
}

func (x *GetNoteResponse) GetItem() *Note {
	if x != nil {
		return x.Item
	}
	return nil
}

type CreateNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNoteRequest) Reset() {
	*x = CreateNoteRequest{}
	mi := &file_domain_note_v1_note_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNoteRequest) ProtoMessage() {}

func (x *CreateNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_note_v1_note_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNoteRequest.ProtoReflect.Descriptor instead.
func (*CreateNoteRequest) Descriptor() ([]byte, []int) {
	return file_domain_note_v1_note_proto_rawDescGZIP(), []int{5}
}

func (x *CreateNoteRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateNoteRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CreateNoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Note                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNoteResponse) Reset() {
	*x = CreateNoteResponse{}
	mi := &file_domain_note_v1_note_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNoteResponse) ProtoMessage() {}

func (x *CreateNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_note_v1_note_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNoteResponse.ProtoReflect.Descriptor instead.
func (*CreateNoteResponse) Descriptor() ([]byte, []int) {
	return file_domain_note_v1_note_proto_rawDescGZIP(), []int{6}
}

func (x *CreateNoteResponse) GetItem() *Note {
	if x != nil {
		return x.Item
	}
	return nil
}

type UpdateNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        string                 `protobuf:"bytes,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Content       *string                `protobuf:"bytes,3,opt,name=content,proto3,oneof" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNoteRequest) Reset() {
	*x = UpdateNoteRequest{}
	mi := &file_domain_note_v1_note_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNoteRequest) ProtoMessage() {}

func (x *UpdateNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_note_v1_note_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNoteRequest.ProtoReflect.Descriptor instead.
func (*UpdateNoteRequest) Descriptor() ([]byte, []int) {
	return file_domain_note_v1_note_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateNoteRequest) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

func (x *UpdateNoteRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateNoteRequest) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

type UpdateNoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Note                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNoteResponse) Reset() {
	*x = UpdateNoteResponse{}
	mi := &file_domain_note_v1_note_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNoteResponse) ProtoMessage() {}

func (x *UpdateNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_note_v1_note_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNoteResponse.ProtoReflect.Descriptor instead.
func (*UpdateNoteResponse) Descriptor() ([]byte, []int) {
	return file_domain_note_v1_note_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateNoteResponse) GetItem() *Note {
	if x != nil {
		return x.Item
	}
	return nil
}

type DeleteNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        string                 `protobuf:"bytes,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNoteRequest) Reset() {
	*x = DeleteNoteRequest{}
	mi := &file_domain_note_v1_note_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNoteRequest) ProtoMessage() {}

func (x *DeleteNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_note_v1_note_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNoteRequest.ProtoReflect.Descriptor instead.
func (*DeleteNoteRequest) Descriptor() ([]byte, []int) {
	return file_domain_note_v1_note_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteNoteRequest) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

type DeleteNoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNoteResponse) Reset() {
	*x = DeleteNoteResponse{}
	mi := &file_domain_note_v1_note_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNoteResponse) ProtoMessage() {}

func (x *DeleteNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_note_v1_note_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNoteResponse.ProtoReflect.Descriptor instead.
func (*DeleteNoteResponse) Descriptor() ([]byte, []int) {
	return file_domain_note_v1_note_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteNoteResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type RestoreNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        string                 `protobuf:"bytes,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreNoteRequest) Reset() {
	*x = RestoreNoteRequest{}
	mi := &file_domain_note_v1_note_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreNoteRequest) ProtoMessage() {}

func (x *RestoreNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_note_v1_note_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreNoteRequest.ProtoReflect.Descriptor instead.
func (*RestoreNoteRequest) Descriptor() ([]byte, []int) {
	return file_domain_note_v1_note_proto_rawDescGZIP(), []int{11}
}

func (x *RestoreNoteRequest) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

type RestoreNoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Note                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreNoteResponse) Reset() {
	*x = RestoreNoteResponse{}
	mi := &file_domain_note_v1_note_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreNoteResponse) ProtoMessage() {}

func (x *RestoreNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_note_v1_note_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreNoteResponse.ProtoReflect.Descriptor instead.
func (*RestoreNoteResponse) Descriptor() ([]byte, []int) {
	return file_domain_note_v1_note_proto_rawDescGZIP(), []int{12}
}

func (x *RestoreNoteResponse) GetItem() *Note {
	if x != nil {
		return x.Item
	}
	return nil
}

type SearchNotesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	OrderBy       string                 `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchNotesRequest) Reset() {
	*x = SearchNotesRequest{}
	mi := &file_domain_note_v1_note_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchNotesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchNotesRequest) ProtoMessage() {}

func (x *SearchNotesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_note_v1_note_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchNotesRequest.ProtoReflect.Descriptor instead.
func (*SearchNotesRequest) Descriptor() ([]byte, []int) {
	return file_domain_note_v1_note_proto_rawDescGZIP(), []int{13}
}

func (x *SearchNotesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchNotesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchNotesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *SearchNotesRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

type SearchNotesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Note                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchNotesResponse) Reset() {
	*x = SearchNotesResponse{}
	mi := &file_domain_note_v1_note_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchNotesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchNotesResponse) ProtoMessage() {}

func (x *SearchNotesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_note_v1_note_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchNotesResponse.ProtoReflect.Descriptor instead.
func (*SearchNotesResponse) Descriptor() ([]byte, []int) {
	return file_domain_note_v1_note_proto_rawDescGZIP(), []int{14}
}

func (x *SearchNotesResponse) GetItems() []*Note {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SearchNotesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_domain_note_v1_note_proto protoreflect.FileDescriptor

const file_domain_note_v1_note_proto_rawDesc = "" +
	"\n" +
	"\x19domain/note/v1/note.proto\x12\x19peers_touch.model.note.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9b\x02\n" +
	"\x04Note\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\tR\x06noteId\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"\x92\x01\n" +
	"\x10ListNotesRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x19\n" +
	"\border_by\x18\x03 \x01(\tR\aorderBy\x12'\n" +
	"\x0finclude_deleted\x18\x04 \x01(\bR\x0eincludeDeleted\"r\n" +
	"\x11ListNotesResponse\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x1f.peers_touch.model.note.v1.NoteR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"R\n" +
	"\x0eGetNoteRequest\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\tR\x06noteId\x12'\n" +
	"\x0finclude_deleted\x18\x02 \x01(\bR\x0eincludeDeleted\"F\n" +
	"\x0fGetNoteResponse\x123\n" +
	"\x04item\x18\x01 \x01(\v2\x1f.peers_touch.model.note.v1.NoteR\x04item\"C\n" +
	"\x11CreateNoteRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"I\n" +
	"\x12CreateNoteResponse\x123\n" +
	"\x04item\x18\x01 \x01(\v2\x1f.peers_touch.model.note.v1.NoteR\x04item\"|\n" +
	"\x11UpdateNoteRequest\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\tR\x06noteId\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12\x1d\n" +
	"\acontent\x18\x03 \x01(\tH\x01R\acontent\x88\x01\x01B\b\n" +
	"\x06_titleB\n" +
	"\n" +
	"\b_content\"I\n" +
	"\x12UpdateNoteResponse\x123\n" +
	"\x04item\x18\x01 \x01(\v2\x1f.peers_touch.model.note.v1.NoteR\x04item\",\n" +
	"\x11DeleteNoteRequest\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\tR\x06noteId\".\n" +
	"\x12DeleteNoteResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"-\n" +
	"\x12RestoreNoteRequest\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\tR\x06noteId\"J\n" +
	"\x13RestoreNoteResponse\x123\n" +
	"\x04item\x18\x01 \x01(\v2\x1f.peers_touch.model.note.v1.NoteR\x04item\"\x81\x01\n" +
	"\x12SearchNotesRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12\x19\n" +
	"\border_by\x18\x04 \x01(\tR\aorderBy\"t\n" +
	"\x13SearchNotesResponse\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x1f.peers_touch.model.note.v1.NoteR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\xf4\x05\n" +
	"\vNoteService\x12f\n" +
	"\tListNotes\x12+.peers_touch.model.note.v1.ListNotesRequest\x1a,.peers_touch.model.note.v1.ListNotesResponse\x12`\n" +
	"\aGetNote\x12).peers_touch.model.note.v1.GetNoteRequest\x1a*.peers_touch.model.note.v1.GetNoteResponse\x12i\n" +
	"\n" +
	"CreateNote\x12,.peers_touch.model.note.v1.CreateNoteRequest\x1a-.peers_touch.model.note.v1.CreateNoteResponse\x12i\n" +
	"\n" +
	"UpdateNote\x12,.peers_touch.model.note.v1.UpdateNoteRequest\x1a-.peers_touch.model.note.v1.UpdateNoteResponse\x12i\n" +
	"\n" +
	"DeleteNote\x12,.peers_touch.model.note.v1.DeleteNoteRequest\x1a-.peers_touch.model.note.v1.DeleteNoteResponse\x12l\n" +
	"\vRestoreNote\x12-.peers_touch.model.note.v1.RestoreNoteRequest\x1a..peers_touch.model.note.v1.RestoreNoteResponse\x12l\n" +
	"\vSearchNotes\x12-.peers_touch.model.note.v1.SearchNotesRequest\x1a..peers_touch.model.note.v1.SearchNotesResponseBIZGgithub.com/peers-labs/peers-touch/apps/applets/note/service/model;modelb\x06proto3"

var (
	file_domain_note_v1_note_proto_rawDescOnce sync.Once
	file_domain_note_v1_note_proto_rawDescData []byte
)

func file_domain_note_v1_note_proto_rawDescGZIP() []byte {
	file_domain_note_v1_note_proto_rawDescOnce.Do(func() {
		file_domain_note_v1_note_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_note_v1_note_proto_rawDesc), len(file_domain_note_v1_note_proto_rawDesc)))
	})
	return file_domain_note_v1_note_proto_rawDescData
}

var file_domain_note_v1_note_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_domain_note_v1_note_proto_goTypes = []any{
	(*Note)(nil),                  // 0: peers_touch.model.note.v1.Note
	(*ListNotesRequest)(nil),      // 1: peers_touch.model.note.v1.ListNotesRequest
	(*ListNotesResponse)(nil),     // 2: peers_touch.model.note.v1.ListNotesResponse
	(*GetNoteRequest)(nil),        // 3: peers_touch.model.note.v1.GetNoteRequest
	(*GetNoteResponse)(nil),       // 4: peers_touch.model.note.v1.GetNoteResponse
	(*CreateNoteRequest)(nil),     // 5: peers_touch.model.note.v1.CreateNoteRequest
	(*CreateNoteResponse)(nil),    // 6: peers_touch.model.note.v1.CreateNoteResponse
	(*UpdateNoteRequest)(nil),     // 7: peers_touch.model.note.v1.UpdateNoteRequest
	(*UpdateNoteResponse)(nil),    // 8: peers_touch.model.note.v1.UpdateNoteResponse
	(*DeleteNoteRequest)(nil),     // 9: peers_touch.model.note.v1.DeleteNoteRequest
	(*DeleteNoteResponse)(nil),    // 10: peers_touch.model.note.v1.DeleteNoteResponse
	(*RestoreNoteRequest)(nil),    // 11: peers_touch.model.note.v1.RestoreNoteRequest
	(*RestoreNoteResponse)(nil),   // 12: peers_touch.model.note.v1.RestoreNoteResponse
	(*SearchNotesRequest)(nil),    // 13: peers_touch.model.note.v1.SearchNotesRequest
	(*SearchNotesResponse)(nil),   // 14: peers_touch.model.note.v1.SearchNotesResponse
	(*timestamppb.Timestamp)(nil), // 15: google.protobuf.Timestamp
}
var file_domain_note_v1_note_proto_depIdxs = []int32{
	15, // 0: peers_touch.model.note.v1.Note.created_at:type_name -> google.protobuf.Timestamp
	15, // 1: peers_touch.model.note.v1.Note.updated_at:type_name -> google.protobuf.Timestamp
	15, // 2: peers_touch.model.note.v1.Note.deleted_at:type_name -> google.protobuf.Timestamp
	0,  // 3: peers_touch.model.note.v1.ListNotesResponse.items:type_name -> peers_touch.model.note.v1.Note
	0,  // 4: peers_touch.model.note.v1.GetNoteResponse.item:type_name -> peers_touch.model.note.v1.Note
	0,  // 5: peers_touch.model.note.v1.CreateNoteResponse.item:type_name -> peers_touch.model.note.v1.Note
	0,  // 6: peers_touch.model.note.v1.UpdateNoteResponse.item:type_name -> peers_touch.model.note.v1.Note
	0,  // 7: peers_touch.model.note.v1.RestoreNoteResponse.item:type_name -> peers_touch.model.note.v1.Note
	0,  // 8: peers_touch.model.note.v1.SearchNotesResponse.items:type_name -> peers_touch.model.note.v1.Note
	1,  // 9: peers_touch.model.note.v1.NoteService.ListNotes:input_type -> peers_touch.model.note.v1.ListNotesRequest
	3,  // 10: peers_touch.model.note.v1.NoteService.GetNote:input_type -> peers_touch.model.note.v1.GetNoteRequest
	5,  // 11: peers_touch.model.note.v1.NoteService.CreateNote:input_type -> peers_touch.model.note.v1.CreateNoteRequest
	7,  // 12: peers_touch.model.note.v1.NoteService.UpdateNote:input_type -> peers_touch.model.note.v1.UpdateNoteRequest
	9,  // 13: peers_touch.model.note.v1.NoteService.DeleteNote:input_type -> peers_touch.model.note.v1.DeleteNoteRequest
	11, // 14: peers_touch.model.note.v1.NoteService.RestoreNote:input_type -> peers_touch.model.note.v1.RestoreNoteRequest
	13, // 15: peers_touch.model.note.v1.NoteService.SearchNotes:input_type -> peers_touch.model.note.v1.SearchNotesRequest
	2,  // 16: peers_touch.model.note.v1.NoteService.ListNotes:output_type -> peers_touch.model.note.v1.ListNotesResponse
	4,  // 17: peers_touch.model.note.v1.NoteService.GetNote:output_type -> peers_touch.model.note.v1.GetNoteResponse
	6,  // 18: peers_touch.model.note.v1.NoteService.CreateNote:output_type -> peers_touch.model.note.v1.CreateNoteResponse
	8,  // 19: peers_touch.model.note.v1.NoteService.UpdateNote:output_type -> peers_touch.model.note.v1.UpdateNoteResponse
	10, // 20: peers_touch.model.note.v1.NoteService.DeleteNote:output_type -> peers_touch.model.note.v1.DeleteNoteResponse
	12, // 21: peers_touch.model.note.v1.NoteService.RestoreNote:output_type -> peers_touch.model.note.v1.RestoreNoteResponse
	14, // 22: peers_touch.model.note.v1.NoteService.SearchNotes:output_type -> peers_touch.model.note.v1.SearchNotesResponse
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_domain_note_v1_note_proto_init() }
func file_domain_note_v1_note_proto_init() {
	if File_domain_note_v1_note_proto != nil {
		return
	}
	file_domain_note_v1_note_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_note_v1_note_proto_rawDesc), len(file_domain_note_v1_note_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_domain_note_v1_note_proto_goTypes,
		DependencyIndexes: file_domain_note_v1_note_proto_depIdxs,
		MessageInfos:      file_domain_note_v1_note_proto_msgTypes,
	}.Build()
	File_domain_note_v1_note_proto = out.File
	file_domain_note_v1_note_proto_goTypes = nil
	file_domain_note_v1_note_proto_depIdxs = nil
}
