import { MobileAcceptanceActionRegistry } from './actionRegistry';
import { mobileAcceptanceActions } from './actions';
import {
  type MobileAcceptanceAction,
  type MobileAcceptanceActionName,
  type MobileAcceptanceNamespace,
} from './contracts';

export function registerMobileAcceptanceAction<
  Name extends MobileAcceptanceActionName,
>(
  name: Name,
  action: MobileAcceptanceAction<Name>,
  registry: MobileAcceptanceActionRegistry,
): void {
  registry.register(name, action);
}

export function createMobileAcceptanceHarness(): MobileAcceptanceNamespace {
  const registry = new MobileAcceptanceActionRegistry();
  registerMobileAcceptanceAction(
    'build.identity',
    mobileAcceptanceActions['build.identity'],
    registry,
  );
  registerMobileAcceptanceAction(
    'runtime.prepareActorIdentity',
    mobileAcceptanceActions['runtime.prepareActorIdentity'],
    registry,
  );
  registerMobileAcceptanceAction(
    'station.add',
    mobileAcceptanceActions['station.add'],
    registry,
  );
  registerMobileAcceptanceAction(
    'station.replace',
    mobileAcceptanceActions['station.replace'],
    registry,
  );
  registerMobileAcceptanceAction(
    'station.select',
    mobileAcceptanceActions['station.select'],
    registry,
  );
  registerMobileAcceptanceAction(
    'access.submit',
    mobileAcceptanceActions['access.submit'],
    registry,
  );
  registerMobileAcceptanceAction(
    'oauth.start',
    mobileAcceptanceActions['oauth.start'],
    registry,
  );
  registerMobileAcceptanceAction(
    'oauth.status',
    mobileAcceptanceActions['oauth.status'],
    registry,
  );
  registerMobileAcceptanceAction(
    'oauth.cancel',
    mobileAcceptanceActions['oauth.cancel'],
    registry,
  );
  registerMobileAcceptanceAction(
    'oauth.replayHandle',
    mobileAcceptanceActions['oauth.replayHandle'],
    registry,
  );
  registerMobileAcceptanceAction(
    'oauth.negativeCallback',
    mobileAcceptanceActions['oauth.negativeCallback'],
    registry,
  );
  registerMobileAcceptanceAction(
    'lifecycle.snapshot',
    mobileAcceptanceActions['lifecycle.snapshot'],
    registry,
  );
  registerMobileAcceptanceAction(
    'lifecycle.waitReady',
    mobileAcceptanceActions['lifecycle.waitReady'],
    registry,
  );
  registerMobileAcceptanceAction(
    'lifecycle.suspend',
    mobileAcceptanceActions['lifecycle.suspend'],
    registry,
  );
  registerMobileAcceptanceAction(
    'lifecycle.resume',
    mobileAcceptanceActions['lifecycle.resume'],
    registry,
  );
  registerMobileAcceptanceAction(
    'lifecycle.restart',
    mobileAcceptanceActions['lifecycle.restart'],
    registry,
  );
  registerMobileAcceptanceAction(
    'lifecycle.nativeBridgeDiagnostic',
    mobileAcceptanceActions['lifecycle.nativeBridgeDiagnostic'],
    registry,
  );
  registerMobileAcceptanceAction(
    'lifecycle.secureStorageDeleteFailure',
    mobileAcceptanceActions['lifecycle.secureStorageDeleteFailure'],
    registry,
  );
  registerMobileAcceptanceAction(
    'lifecycle.scope.read',
    mobileAcceptanceActions['lifecycle.scope.read'],
    registry,
  );
  registerMobileAcceptanceAction(
    'navigation.snapshot',
    mobileAcceptanceActions['navigation.snapshot'],
    registry,
  );
  registerMobileAcceptanceAction(
    'navigation.apply',
    mobileAcceptanceActions['navigation.apply'],
    registry,
  );
  registerMobileAcceptanceAction(
    'platform.permission.check',
    mobileAcceptanceActions['platform.permission.check'],
    registry,
  );
  registerMobileAcceptanceAction(
    'platform.permission.request',
    mobileAcceptanceActions['platform.permission.request'],
    registry,
  );
  registerMobileAcceptanceAction(
    'platform.permission.checkAll',
    mobileAcceptanceActions['platform.permission.checkAll'],
    registry,
  );
  registerMobileAcceptanceAction(
    'platform.network.read',
    mobileAcceptanceActions['platform.network.read'],
    registry,
  );
  registerMobileAcceptanceAction(
    'session.logout',
    mobileAcceptanceActions['session.logout'],
    registry,
  );
  registerMobileAcceptanceAction(
    'native.deliverDeepLink',
    mobileAcceptanceActions['native.deliverDeepLink'],
    registry,
  );
  registerMobileAcceptanceAction(
    'projection.read',
    mobileAcceptanceActions['projection.read'],
    registry,
  );
  registerMobileAcceptanceAction(
    'federation.context.read',
    mobileAcceptanceActions['federation.context.read'],
    registry,
  );
  registerMobileAcceptanceAction(
    'messaging.createDirect',
    mobileAcceptanceActions['messaging.createDirect'],
    registry,
  );
  registerMobileAcceptanceAction(
    'messaging.createGroup',
    mobileAcceptanceActions['messaging.createGroup'],
    registry,
  );
  registerMobileAcceptanceAction(
    'messaging.attachment.stage',
    mobileAcceptanceActions['messaging.attachment.stage'],
    registry,
  );
  registerMobileAcceptanceAction(
    'messaging.attachment.open',
    mobileAcceptanceActions['messaging.attachment.open'],
    registry,
  );
  registerMobileAcceptanceAction(
    'messaging.send',
    mobileAcceptanceActions['messaging.send'],
    registry,
  );
  registerMobileAcceptanceAction(
    'messaging.interact',
    mobileAcceptanceActions['messaging.interact'],
    registry,
  );
  registerMobileAcceptanceAction(
    'messaging.read',
    mobileAcceptanceActions['messaging.read'],
    registry,
  );
  registerMobileAcceptanceAction(
    'messaging.typing',
    mobileAcceptanceActions['messaging.typing'],
    registry,
  );
  registerMobileAcceptanceAction(
    'messaging.reconcile',
    mobileAcceptanceActions['messaging.reconcile'],
    registry,
  );
  registerMobileAcceptanceAction(
    'messaging.command.read',
    mobileAcceptanceActions['messaging.command.read'],
    registry,
  );
  registerMobileAcceptanceAction(
    'messaging.search',
    mobileAcceptanceActions['messaging.search'],
    registry,
  );
  registerMobileAcceptanceAction(
    'messaging.projection.read',
    mobileAcceptanceActions['messaging.projection.read'],
    registry,
  );
  registerMobileAcceptanceAction(
    'social.people.search',
    mobileAcceptanceActions['social.people.search'],
    registry,
  );
  registerMobileAcceptanceAction(
    'reliability.fixture.configure',
    mobileAcceptanceActions['reliability.fixture.configure'],
    registry,
  );
  registerMobileAcceptanceAction(
    'reliability.friendRequest.submit',
    mobileAcceptanceActions['reliability.friendRequest.submit'],
    registry,
  );
  registerMobileAcceptanceAction(
    'reliability.snapshot',
    mobileAcceptanceActions['reliability.snapshot'],
    registry,
  );
  registerMobileAcceptanceAction(
    'reliability.reconcile',
    mobileAcceptanceActions['reliability.reconcile'],
    registry,
  );
  registerMobileAcceptanceAction(
    'reliability.command.action',
    mobileAcceptanceActions['reliability.command.action'],
    registry,
  );
  registerMobileAcceptanceAction(
    'reliability.draft.write',
    mobileAcceptanceActions['reliability.draft.write'],
    registry,
  );
  registerMobileAcceptanceAction(
    'reliability.draft.read',
    mobileAcceptanceActions['reliability.draft.read'],
    registry,
  );
  registerMobileAcceptanceAction(
    'reliability.draft.action',
    mobileAcceptanceActions['reliability.draft.action'],
    registry,
  );
  registerMobileAcceptanceAction(
    'reliability.reset',
    mobileAcceptanceActions['reliability.reset'],
    registry,
  );
  registerMobileAcceptanceAction(
    'recovery.snapshot',
    mobileAcceptanceActions['recovery.snapshot'],
    registry,
  );
  registerMobileAcceptanceAction(
    'social.request.send',
    mobileAcceptanceActions['social.request.send'],
    registry,
  );
  registerMobileAcceptanceAction(
    'social.request.accept',
    mobileAcceptanceActions['social.request.accept'],
    registry,
  );
  registerMobileAcceptanceAction(
    'social.contact.open',
    mobileAcceptanceActions['social.contact.open'],
    registry,
  );
  registerMobileAcceptanceAction(
    'social.reconcile',
    mobileAcceptanceActions['social.reconcile'],
    registry,
  );
  registerMobileAcceptanceAction(
    'social.projection.read',
    mobileAcceptanceActions['social.projection.read'],
    registry,
  );
  registerMobileAcceptanceAction(
    'moments.private.publishText',
    mobileAcceptanceActions['moments.private.publishText'],
    registry,
  );
  registerMobileAcceptanceAction(
    'moments.private.readText',
    mobileAcceptanceActions['moments.private.readText'],
    registry,
  );
  registerMobileAcceptanceAction(
    'moments.private.reconcile',
    mobileAcceptanceActions['moments.private.reconcile'],
    registry,
  );
  registerMobileAcceptanceAction(
    'moments.private.snapshot',
    mobileAcceptanceActions['moments.private.snapshot'],
    registry,
  );
  registerMobileAcceptanceAction(
    'moments.feed.read',
    mobileAcceptanceActions['moments.feed.read'],
    registry,
  );
  registerMobileAcceptanceAction(
    'moments.publish',
    mobileAcceptanceActions['moments.publish'],
    registry,
  );
  registerMobileAcceptanceAction(
    'moments.react',
    mobileAcceptanceActions['moments.react'],
    registry,
  );
  registerMobileAcceptanceAction(
    'moments.comment',
    mobileAcceptanceActions['moments.comment'],
    registry,
  );
  registerMobileAcceptanceAction(
    'moments.comments.read',
    mobileAcceptanceActions['moments.comments.read'],
    registry,
  );
  registerMobileAcceptanceAction(
    'storage.cache.seed',
    mobileAcceptanceActions['storage.cache.seed'],
    registry,
  );
  registerMobileAcceptanceAction(
    'storage.conversation-clear.seed',
    mobileAcceptanceActions['storage.conversation-clear.seed'],
    registry,
  );
  registerMobileAcceptanceAction(
    'storage.batch.scenario',
    mobileAcceptanceActions['storage.batch.scenario'],
    registry,
  );
  registerMobileAcceptanceAction(
    'storage.retention.seed',
    mobileAcceptanceActions['storage.retention.seed'],
    registry,
  );
  registerMobileAcceptanceAction(
    'settings.profile.read',
    mobileAcceptanceActions['settings.profile.read'],
    registry,
  );
  registerMobileAcceptanceAction(
    'settings.profile.update',
    mobileAcceptanceActions['settings.profile.update'],
    registry,
  );
  registerMobileAcceptanceAction(
    'settings.notifications.read',
    mobileAcceptanceActions['settings.notifications.read'],
    registry,
  );
  registerMobileAcceptanceAction(
    'settings.notifications.update',
    mobileAcceptanceActions['settings.notifications.update'],
    registry,
  );
  registerMobileAcceptanceAction(
    'settings.device.read',
    mobileAcceptanceActions['settings.device.read'],
    registry,
  );
  registerMobileAcceptanceAction(
    'settings.device.update',
    mobileAcceptanceActions['settings.device.update'],
    registry,
  );
  registerMobileAcceptanceAction(
    'getRealtimeDevice',
    mobileAcceptanceActions.getRealtimeDevice,
    registry,
  );
  registerMobileAcceptanceAction(
    'initiateCall',
    mobileAcceptanceActions.initiateCall,
    registry,
  );
  registerMobileAcceptanceAction(
    'callResolutionState',
    mobileAcceptanceActions.callResolutionState,
    registry,
  );
  registerMobileAcceptanceAction(
    'acceptCall',
    mobileAcceptanceActions.acceptCall,
    registry,
  );
  registerMobileAcceptanceAction(
    'rejectCall',
    mobileAcceptanceActions.rejectCall,
    registry,
  );
  registerMobileAcceptanceAction(
    'cleanup',
    mobileAcceptanceActions.cleanup,
    registry,
  );
  return registry.expose();
}

export function installMobileAcceptanceHarness(
  target: Window = window,
): void {
  if (target.__PEERS_MOBILE_ACCEPTANCE__) {
    throw new Error('acceptance.mobile.duplicateHarness');
  }
  target.__PEERS_MOBILE_ACCEPTANCE__ = createMobileAcceptanceHarness();
}
